### ISSUE TITLE
Allow multiple authenticators to be used simultaneously

### ISSUE THREAD

**Issue by pcastellazzi** [trinodb/trino#4486] opened 2020-07-17 22:12 UTC
As of now you can only configure one password authenticator. I would like to be able to use at least two of them at the same time.

My use case for this is as follows, we have users on our ActiveDirectory account, which are allowed multiple things including access to presto, and we have what we call service accounts, which are user/pass combinations used for communication between services, this are rotated often and usually generated on demand. I would like to be able to configure LDAP as the default authentication mechanism with a fallback to FILE for this service accounts.

The thread about this issue on [slack](https://prestosaql.slack.com/archives/CFLB9AMBN/p1594922734257100)

**Comment by lhofhansl** [comment] 2020-07-22 15:41
See also #4365

**Comment by phd3** [comment] 2020-07-22 16:00
@electrum I tried this out, there's one issue: returning headers from multiple password authenticators (ldap and file) to the authentication filter. Right now, we can only throw an `AuthenticationException` with one error message, and concatenation of error messages is not ideal.  

So this may require changing the flow of [this](https://github.com/prestosql/presto/blob/9be344cca0c6c3e704861bdca17c87ac335081ba/presto-main/src/main/java/io/prestosql/server/security/AuthenticationFilter.java#L79) try-catch block. we can get multiple headers from  `authenticate` instead of throwing an exception. this does not break SPI, since SPI password authenticators can still behave the same way. What are your thoughts?

**Comment by lhofhansl** [comment] 2020-07-22 17:26
@phd3 If we add a new authenticator and let it delegate to other authenticators, would we have the same problem?

**Comment by phd3** [comment] 2020-07-23 17:50
@lhofhansl  If we always try exactly one password authenticator for every user in #4365 , then we shouldn't have this problem. 

But this is a slightly different pattern that what is followed at top-level in `authenticationFilter`, where all authenticators are tried out until one of them succeeds.

**Comment by lhofhansl** [comment] 2020-08-11 21:36
FWIW, that's what I had in mind with #4365, you'd have to configure a new authenticator with all the authenticators you want to try.

**Comment by sopel39** [comment] 2021-03-09 10:24
Duplicate of: https://github.com/trinodb/trino/issues/1791

**Closed by sopel39** 2021-03-09 10:24 UTC
Labels: enhancement
