### ISSUE TITLE
Not able to select iceberg v2 format table

### ISSUE THREAD

**Issue by 0xffmeta** [trinodb/trino#14928] opened 2022-11-07 11:16 UTC
I have an iceberg v2 format table written by a flink job, but I'm not able to use the latest trino version(402) to select the table.

If not select those nested columns, it will return the result, but failed with `select *` or `select srcs, labels`.

With the same table, I can select by using trino 377.

```
io.trino.spi.TrinoException: Multiple entries with same key: 1=srcs.element and 1=labels.element
	at io.trino.plugin.iceberg.IcebergPageSource.getNextPage(IcebergPageSource.java:179)
	at io.trino.plugin.base.classloader.ClassLoaderSafeUpdatablePageSource.getNextPage(ClassLoaderSafeUpdatablePageSource.java:79)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:311)
	at io.trino.operator.Driver.processInternal(Driver.java:411)
	at io.trino.operator.Driver.lambda$process$10(Driver.java:314)
	at io.trino.operator.Driver.tryWithLock(Driver.java:706)
	at io.trino.operator.Driver.process(Driver.java:306)
	at io.trino.operator.Driver.processForDuration(Driver.java:277)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:739)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:515)
	at io.trino.$gen.Trino_402____20221107_035934_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: 1=srcs.element and 1=labels.element
	at org.apache.iceberg.relocated.com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:376)
	at org.apache.iceberg.relocated.com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:370)
	at org.apache.iceberg.relocated.com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:153)
	at org.apache.iceberg.relocated.com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:115)
	at org.apache.iceberg.relocated.com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:574)
	at org.apache.iceberg.relocated.com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:538)
	at org.apache.iceberg.types.IndexByName.byId(IndexByName.java:81)
	at org.apache.iceberg.types.TypeUtil.indexNameById(TypeUtil.java:160)
	at org.apache.iceberg.Schema.lazyIdToName(Schema.java:183)
	at org.apache.iceberg.Schema.<init>(Schema.java:112)
	at org.apache.iceberg.Schema.<init>(Schema.java:91)
	at org.apache.iceberg.Schema.<init>(Schema.java:83)
	at org.apache.iceberg.Schema.<init>(Schema.java:79)
	at io.trino.plugin.iceberg.IcebergUtil.schemaFromHandles(IcebergUtil.java:241)
	at io.trino.plugin.iceberg.delete.EqualityDeleteFilter.createPredicate(EqualityDeleteFilter.java:49)
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.lambda$createPageSource$7(IcebergPageSourceProvider.java:348)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662)
	at io.trino.plugin.iceberg.IcebergPageSourceProvider.lambda$createPageSource$8(IcebergPageSourceProvider.java:349)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183)
	at io.trino.plugin.iceberg.IcebergPageSource.getNextPage(IcebergPageSource.java:162)
	... 14 more

```

**Comment by ebyhr** [comment] 2022-11-07 11:18
Closing as duplicate of #14836

**Closed by ebyhr** 2022-11-07 11:18 UTC
