### ISSUE TITLE
Proposal to Add Basic Predicate Pushdown Support for ClickHouse VARCHAR Columns in Trino

### ISSUE THREAD

**Issue by zeropool** [trinodb/trino#18831] opened 2023-08-28 10:18 UTC
I would like to propose the addition of a simple predicate pushdown functionality for ClickHouse VARCHAR columns in the Trino project. Currently, ClickHouse is a popular columnar database known for its exceptional performance in handling massive datasets. However, it has come to my attention that Trino might lack some fundamental predicate pushdown capabilities when dealing with VARCHAR columns in ClickHouse. This could potentially lead to performance challenges. 

While I understand that Trino is a powerful and flexible distributed query engine, there might be room for improvement when handling ClickHouse VARCHAR columns. I believe that introducing predicate pushdown capabilities can foster better integration with ClickHouse, leading to enhanced query efficiency and an improved user experience.

**Comment by ebyhr** [comment] 2023-08-28 22:53
Closing as duplicate of #7100

**Closed by ebyhr** 2023-08-28 22:53 UTC
