### ISSUE TITLE
Flaky Iceberg TestIcebergV2 testOptimizeDuringWriteOperations

### ISSUE THREAD

**Issue by chenjian2664** [trinodb/trino#24131] opened 2024-11-14 03:37 UTC
https://github.com/trinodb/trino/actions/runs/11829608194/job/32961756024?pr=24075#step:5:2343

**Comment by ebyhr** [comment] 2024-11-14 04:58
Duplicate of #18697

**Closed by ebyhr** 2024-11-14 04:58 UTC
Labels: iceberg, Flaky Tests
