### ISSUE TITLE
TABLE_NOT_FOUND and GENERIC_INTERNAL_ERROR appear occasionally in ClickHouse connector

### ISSUE THREAD

**Issue by akenO8** [trinodb/trino#18351] opened 2023-07-20 03:40 UTC
trino version : 422
connector version : 21.11.10.1

I have a minute-by-minute insert job running continuously, Occasionally, the following error is reported:

first appear:
`TrinoUserError(type=USER_ERROR, name=TABLE_NOT_FOUND, message="Table \'clickhouse.tmp.tb1\' does not exist", query_id=xxx)`
then appear:

`TrinoQueryError(type=INTERNAL_ERROR, name=GENERIC_INTERNAL_ERROR, message="Failed to find remote schema name: Read timed out, server ClickHouseNode [uri=http://clickhouse_host:8123/default, options={use_binary_string=true}]@1690259577", query_id=yyy)`

I see no problem with the machine network.

could you please tell me what the problem might be? I would appreciate your advice.

**Comment by ebyhr** [comment] 2023-07-20 05:23
Please share the config property, query and the entire stacktrace.

**Comment by akenO8** [comment] 2023-07-20 06:22
> Please share the config property, query and the entire stacktrace.

property:
```
        "connector.name=clickhouse", 
        "connection-url=jdbc:clickhouse://ck-lb.data.onething.internal:8123", 
        "connection-user=trino", 
        "connection-password=TDMb3HK34F", 
        "case-insensitive-name-matching=true", 
        "clickhouse.map-string-as-varchar=true", 
        "insert.non-transactional-insert.enabled=true",
        "write.batch-size=20000"
```

no more stacktrace
```
2023-07-20T05:50:47.145+0800    INFO    dispatcher-query-2775   io.trino.event.QueryMonitor     TIMELINE: Query 20230719_215015_06821_escsh :: FAILED (TABLE_NOT_FOUND) :: elapsed 31467ms :: planning 31467ms :: waiting 0ms :: scheduling 0ms :: running 0ms :: finishing 0ms :: begin 2023-07-20T05:50:15.677+08:00 :: end 2023-07-20T05:50:47.144+08:00
...
...
...
2023-07-20T05:58:40.108+0800    INFO    dispatcher-query-2775   io.trino.event.QueryMonitor     TIMELINE: Query 20230719_215809_06836_escsh :: FAILED (GENERIC_INTERNAL_ERROR) :: elapsed 30806ms :: planning 30806ms :: waiting 0ms :: scheduling 0ms :: running 0ms :: finishing 0ms :: begin 2023-07-20T05:58:09.300+08:00 :: end 2023-07-20T05:58:40.106+08:00
```

**Comment by ebyhr** [comment] 2023-07-20 06:25
You can get the entire stacktrace from webui.

**Comment by akenO8** [comment] 2023-07-20 06:26
> You can get the entire stacktrace from webui.

Unfortunately, the query retention period has expired.

**Comment by ebyhr** [comment] 2023-07-20 07:53
I suppose increasing `socket_timeout` resolves the issue. Closing as duplicate of #13527

**Closed by ebyhr** 2023-07-20 07:53 UTC

**Comment by akenO8** [comment] 2023-08-17 07:43
I raised the socket_timeout to 300000, but the problem is still unresolved. These mistakes still happen sometimes.

The entire stacktrace:

`io.trino.spi.TrinoException: Failed to find remote schema name: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
, server ClickHouseNode [uri=http://ck_host:8123/default, options={socket_timeout=300000,use_binary_string=true}]@-375203184
	at io.trino.plugin.base.mapping.CachingIdentifierMapping.toRemoteSchemaName(CachingIdentifierMapping.java:109)
	at io.trino.plugin.jdbc.BaseJdbcClient.getTableHandle(BaseJdbcClient.java:213)
	at io.trino.plugin.jdbc.ForwardingJdbcClient.getTableHandle(ForwardingJdbcClient.java:88)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.lambda$getTableHandle$3(StatisticsAwareJdbcClient.java:109)
	at io.trino.plugin.jdbc.jmx.JdbcApiStats.wrap(JdbcApiStats.java:34)
	at io.trino.plugin.jdbc.jmx.StatisticsAwareJdbcClient.getTableHandle(StatisticsAwareJdbcClient.java:109)
	at io.trino.plugin.jdbc.CachingJdbcClient.lambda$getTableHandle$4(CachingJdbcClient.java:344)
	at io.trino.cache.EmptyCache.get(EmptyCache.java:94)
	at io.trino.plugin.jdbc.CachingJdbcClient.get(CachingJdbcClient.java:745)
	at io.trino.plugin.jdbc.CachingJdbcClient.getTableHandle(CachingJdbcClient.java:344)
	at io.trino.plugin.jdbc.CachingJdbcClient.lambda$getTableHandle$4(CachingJdbcClient.java:344)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4924)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3570)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2312)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2189)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2079)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4011)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4919)
	at io.trino.cache.EvictableCache.get(EvictableCache.java:112)
	at io.trino.plugin.jdbc.CachingJdbcClient.get(CachingJdbcClient.java:745)
	at io.trino.plugin.jdbc.CachingJdbcClient.getTableHandle(CachingJdbcClient.java:344)
	at io.trino.plugin.jdbc.DefaultJdbcMetadata.getTableHandle(DefaultJdbcMetadata.java:138)
	at io.trino.plugin.jdbc.DefaultJdbcMetadata.getTableHandle(DefaultJdbcMetadata.java:103)
	at io.trino.spi.connector.ConnectorMetadata.getTableHandle(ConnectorMetadata.java:122)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getTableHandle(ClassLoaderSafeConnectorMetadata.java:1074)
	at io.trino.tracing.TracingConnectorMetadata.getTableHandle(TracingConnectorMetadata.java:142)
	at io.trino.metadata.MetadataManager.lambda$getTableHandle$5(MetadataManager.java:282)
	at java.base/java.util.Optional.flatMap(Optional.java:289)
	at io.trino.metadata.MetadataManager.getTableHandle(MetadataManager.java:276)
	at io.trino.metadata.MetadataManager.getRedirectionAwareTableHandle(MetadataManager.java:1579)
	at io.trino.metadata.MetadataManager.getRedirectionAwareTableHandle(MetadataManager.java:1571)
	at io.trino.tracing.TracingMetadata.getRedirectionAwareTableHandle(TracingMetadata.java:1291)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.getTableHandle(StatementAnalyzer.java:5444)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:2218)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:488)
	at io.trino.sql.tree.Table.accept(Table.java:60)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:505)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:4503)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:2981)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:488)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:505)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.lambda$visitSetOperation$69(StatementAnalyzer.java:3080)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitSetOperation(StatementAnalyzer.java:3081)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitSetOperation(StatementAnalyzer.java:488)
	at io.trino.sql.tree.AstVisitor.visitUnion(AstVisitor.java:267)
	at io.trino.sql.tree.Union.accept(Union.java:57)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:505)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.lambda$visitSetOperation$69(StatementAnalyzer.java:3080)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitSetOperation(StatementAnalyzer.java:3081)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitSetOperation(StatementAnalyzer.java:488)
	at io.trino.sql.tree.AstVisitor.visitUnion(AstVisitor.java:267)
	at io.trino.sql.tree.Union.accept(Union.java:57)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:505)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:513)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1501)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:488)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:505)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:467)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:461)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitInsert(StatementAnalyzer.java:542)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitInsert(StatementAnalyzer.java:488)
	at io.trino.sql.tree.Insert.accept(Insert.java:68)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:505)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:467)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:97)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:86)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:270)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:205)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:844)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:153)
	at io.trino.$gen.Trino_422____20230802_122735_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:75)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.trino.spi.TrinoException: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
, server ClickHouseNode [uri=http://ck_host:8123/default, options={socket_timeout=300000,use_binary_string=true}]@-375203184
	at io.trino.plugin.jdbc.BaseJdbcClient.listSchemas(BaseJdbcClient.java:170)
	at io.trino.plugin.jdbc.JdbcRemoteIdentifiers.getRemoteSchemas(JdbcRemoteIdentifiers.java:48)
	at io.trino.plugin.base.mapping.CachingIdentifierMapping.toRemoteSchemaName(CachingIdentifierMapping.java:100)
	... 98 more
Caused by: java.sql.SQLException: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
, server ClickHouseNode [uri=http://ck_host:8123/default, options={socket_timeout=300000,use_binary_string=true}]@-375203184
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:85)
	at com.clickhouse.jdbc.SqlExceptionUtils.create(SqlExceptionUtils.java:31)
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:90)
	at com.clickhouse.jdbc.ClickHouseDatabaseMetaData.query(ClickHouseDatabaseMetaData.java:76)
	at com.clickhouse.jdbc.ClickHouseDatabaseMetaData.query(ClickHouseDatabaseMetaData.java:54)
	at com.clickhouse.jdbc.ClickHouseDatabaseMetaData.getSchemas(ClickHouseDatabaseMetaData.java:1257)
	at io.trino.plugin.jdbc.BaseJdbcClient.listSchemas(BaseJdbcClient.java:158)
	... 100 more
Caused by: java.io.IOException: <html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>

	at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:184)
	at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:227)
	at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:124)
	at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:280)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:282)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:294)
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:349)
	at com.clickhouse.client.ClickHouseClient.executeAndWait(ClickHouseClient.java:1056)
	at com.clickhouse.client.ClickHouseRequest.executeAndWait(ClickHouseRequest.java:2154)
	at com.clickhouse.jdbc.ClickHouseDatabaseMetaData.query(ClickHouseDatabaseMetaData.java:74)
	... 103 more`
