### ISSUE TITLE
Support renaming a field in Delta Lake 

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#18163] opened 2023-07-07 05:37 UTC
For Delta Lake tables with column mapping mode set to id or name Trino should support renaming nested fields

Relates to https://github.com/trinodb/trino/issues/12638

The SQL parser needs to be extended as well to support referencing nested fields when doing such operations

```
trino> alter table delta.tiny.test3 rename column b.c to crenamed;
Query 20230707_045702_00018_v7kmf failed: line 1:45: mismatched input '.'. Expecting: 'TO'
io.trino.sql.parser.ParsingException: line 1:45: mismatched input '.'. Expecting: 'TO'
	at io.trino.sql.parser.ErrorHandler.syntaxError(ErrorHandler.java:109)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:327)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:139)
	at io.trino.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:5501)
```
PoC for dropping nested fields via `DROP COLUMN`  https://github.com/trinodb/trino/pull/16002

**Comment by ebyhr** [comment] 2023-07-07 05:57
Closing as duplicate of #18097

**Closed by ebyhr** 2023-07-07 05:57 UTC
Labels: delta-lake
