### ISSUE TITLE
Conflicting information between SQL connector documentation and its helm charts

### ISSUE THREAD

**Issue by Lddeiva** [trinodb/trino#18631] opened 2023-08-10 13:22 UTC
Hi All,

I am trying to deploy Trino with SQL connector. The documentation says we have to keep the `.properties`  file within the `etc/catalog` directory.

![image](https://github.com/trinodb/trino/assets/61077834/2434f539-34be-4016-9227-b8d98546db48)

But, if you look at the helm charts they mount the `.properties` files at `etc/trino/catalog` directory.

**values.yaml**
![image](https://github.com/trinodb/trino/assets/61077834/fa24de98-adfa-444d-9ac1-0b7a264f64cb)

**deployment-coordinator.yaml**
![image](https://github.com/trinodb/trino/assets/61077834/fd7afbd5-f3b0-45be-8415-d5274aca34e0)

Can the documentation or code be updated to fix this conflicting information?

**Comment by ebyhr** [comment] 2023-08-14 05:47
Closing as duplicate of #12494

**Closed by ebyhr** 2023-08-14 05:47 UTC
