### ISSUE TITLE
Iceberg table created by flink in hive is not visible by presto when using "show tables" under specified schema of iceberg catalog

### ISSUE THREAD

**Issue by rocketguan** [trinodb/trino#6610] opened 2021-01-15 00:46 UTC
ceberg table created by flink (with flink sql 1.11.1) is not visible by presto (tested with trino version 351) when using "show tables" under specified schema of iceberg catalog, After checked the metadata of the iceberg table created by flink, but can not display in trino!

**Comment by hashhar** [comment] 2021-01-15 06:55
Can you please take a look at https://github.com/trinodb/trino/issues/1592 and confirm if the cause seems to be the same?

cc: @electrum @lxynov

**Comment by findepi** [comment] 2021-07-12 09:55
@rocketguan @lxynov does the issue still exist?

**Comment by findepi** [comment] 2021-07-16 10:30
Was this fixed by @phd3 's https://github.com/trinodb/trino/pull/7642 ?

**Comment by findepi** [comment] 2021-07-23 10:55
@rocketguan i am tempted to close the issue as obsolete. Can you please verify whether this works in your environment now?

**Comment by wilsonpenha** [comment] 2022-02-08 03:06
I can see a similar issue from Trino-370 where I can not see the table I created on hive as it says it is Not an Iceberg table: myschema.constants, from hive I can see both tables created from trino and from hive.

**Comment by wilsonpenha** [comment] 2022-02-08 03:09
trino:myschema> show create table constants;
Query 20220208_030829_00022_u3b29 failed: Not an Iceberg table: myschema.constants

**Comment by findepi** [comment] 2022-02-08 09:25
> trino:myschema> show create table constants; Query 20220208_030829_00022_u3b29 failed: Not an Iceberg table: myschema.constants

This will be solved by https://github.com/trinodb/trino/issues/10245

**Comment by findepi** [comment] 2022-02-08 09:25
Closing per https://github.com/trinodb/trino/issues/6610#issuecomment-885559256

**Closed by findepi** 2022-02-08 09:25 UTC
Labels: bug
