### ISSUE TITLE
Flaky test io.trino.tests.product.hive.TestHiveBucketedTables.testBucketingWithUnsupportedDataTypes

### ISSUE THREAD

**Issue by joshthoward** [trinodb/trino#9353] opened 2021-09-23 18:41 UTC
The test `io.trino.tests.product.hive.TestHiveBucketedTables.testBucketingWithUnsupportedDataTypes` is failing pretty reliably on master. See [this](https://github.com/trinodb/trino/pull/9157/checks?check_run_id=3679356122#step:6:6612) as an example. The change that introduced this was https://github.com/trinodb/trino/pull/8986.

**Comment by hashhar** [comment] 2021-09-23 18:53
Copying logs here since they'll eventually expire:

```
tests               | 2021-09-23 01:31:41 INFO: FAILURE     /    io.trino.tests.product.hive.TestHiveBucketedTables.testBucketingWithUnsupportedDataTypes [BUCKETED_V2, n_struct] (Groups: ) took 2.1 seconds
tests               | 2021-09-23 01:31:41 SEVERE: Failure cause:
tests               | io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
tests               | 	at io.trino.tests.product.hive.TestHiveBucketedTables.populateRowToHiveTable(TestHiveBucketedTables.java:470)
tests               | 	at io.trino.tests.product.hive.TestHiveBucketedTables.testBucketingWithUnsupportedDataTypes(TestHiveBucketedTables.java:355)
tests               | 	at jdk.internal.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
tests               | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
tests               | 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
tests               | 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
tests               | 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
tests               | 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
tests               | 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
tests               | 	at java.base/java.lang.Thread.run(Thread.java:829)
tests               | Caused by: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
tests               | 	at org.apache.hive.jdbc.HiveStatement.execute(HiveStatement.java:275)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:128)
tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:112)
tests               | 	... 15 more
tests               | 	Suppressed: java.lang.Exception: Query: INSERT INTO TABLE table_with_unsupported_bucketing_types_3nmqmuazc4j9 SELECT 1,CAST(1 AS DECIMAL(9, 2)),CAST('2015-01-01T00:01:00.15' AS TIMESTAMP),'char value',unhex('00010203'),create_union(0, 1, 'union value'),named_struct('field1', 1, 'field2', 'Field2') FROM (SELECT 'foo') x
tests               | 		at io.trino.tempto.query.JdbcQueryExecutor.executeQueryNoParams(JdbcQueryExecutor.java:136)
tests               | 		... 16 more
```

**Comment by hashhar** [comment] 2021-09-23 18:55
Seems we needs logs from the Hadoop container to find the cause of failure since MapRed task failing with error code 2 is as generic as it can get and it can fail for multiple reasons - wrongly written files, unexpected table layout (incorrectly named bucketed files etc.).

**Comment by hashhar** [comment] 2021-09-23 18:56
Closing as duplicate of https://github.com/trinodb/trino/issues/9263 though.

**Closed by hashhar** 2021-09-23 18:56 UTC
