### ISSUE TITLE
iceberg connector cannot perform write operations when use Nessie catalog

### ISSUE THREAD

**Issue by junshiwang** [trinodb/trino#17813] opened 2023-06-09 02:21 UTC
if table propeties has nessie.commit.id,  cannot perform any write operations

![image](https://github.com/trinodb/trino/assets/17975325/5bcc5372-a0f1-4748-a1fe-842d872ad25d)

```[tasklist]
### Tasks
```

**Comment by junshiwang** [comment] 2023-06-09 02:23
trino log
![image](https://github.com/trinodb/trino/assets/17975325/7c1cdbd6-572e-4702-bdc1-0f1ff706e0ba)

**Comment by ajantha-bhat** [comment] 2023-06-22 11:05
Hi saw this ticket today. 

@junshiwang:  can you please provide a step how the table was created? **was it from spark?**

Because I tried creating the table locally in Trino with Nessie, It can insert the data 

```
trino:db1> CREATE TABLE yearly_clicks (
        ->     year,
        ->     clicks
        -> )
        -> WITH (
        ->     partitioning = ARRAY['year']
        -> )
        -> AS VALUES
        ->     (2021, 10000),
        ->     (2022, 20000);
CREATE TABLE: 2 rows

Query 20230622_110108_00007_5c9cy, FINISHED, 1 node
Splits: 50 total, 50 done (100.00%)
2.73 [0 rows, 0B] [0 rows/s, 0B/s]

trino:db1> select * from "yearly_clicks$properties";
         key          | value 
----------------------+-------
 write.format.default | ORC   
(1 row)

Query 20230622_110127_00008_5c9cy, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0.28 [1 rows, 33B] [3 rows/s, 119B/s]

trino:db1> insert into yearly_clicks select 2021, 22;
INSERT: 1 row

Query 20230622_110403_00009_5c9cy, FINISHED, 1 node
Splits: 50 total, 50 done (100.00%)
1.44 [0 rows, 0B] [0 rows/s, 0B/s]

trino:db1> insert into yearly_clicks select 2021, 22;
INSERT: 1 row

Query 20230622_110405_00010_5c9cy, FINISHED, 1 node
Splits: 50 total, 50 done (100.00%)
0.91 [0 rows, 0B] [0 rows/s, 0B/s]

trino:db1> select * from yearly_clicks;
 year | clicks 
------+--------
 2022 |  20000 
 2021 |     22 
 2021 |  10000 
 2021 |     22 
(4 rows)

Query 20230622_110420_00011_5c9cy, FINISHED, 1 node
Splits: 4 total, 4 done (100.00%)
0.48 [4 rows, 1.62KB] [8 rows/s, 3.37KB/s]

trino:db1> select * from "yearly_clicks$properties";
         key          | value 
----------------------+-------
 write.format.default | ORC   
(1 row)

Query 20230622_110423_00012_5c9cy, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0.23 [1 rows, 33B] [4 rows/s, 143B/s]
```

**Comment by ajantha-bhat** [comment] 2023-06-22 16:46
I was able to reproduce locally this only when I Trino tries to write to a Spark created Iceberg table using Nessie catalog. 
Analysis in progress.

**Comment by ajantha-bhat** [comment] 2023-06-23 08:56
Problem:
Cannot insert the data on Spark written Iceberg tables with Nessie catalog from Trino. 

Analysis: 
Spark sets the table property `NESSIE_COMMIT_ID_PROPERTY` in `IcebergNessieTableOperations#loadTableMetadata`. 
Then `NessieIcebergClient.commitTable` uses this property. 

In Trino, this property is never set but used in  `NessieIcebergClient.commitTable` as it is a common code.  Hence, the commit id is old and doesn't allow new commits.

Solution: 
Move `IcebergNessieTableOperations#loadTableMetadata` as a static method to `NessieIcebergClient` and use it in both Spark and Trino integration.
So, this fix needs a Iceberg side Nessie change and we need to wait for the Iceberg release :(

Note: alternative solution is to duplicate the `IcebergNessieTableOperations#loadTableMetadata` in Trino's `IcebergNessieTableOperations` but we cannot get the reference as `UpdateableReference` is not a public class and it still needs changes at Iceberg side. Compared to this, I prefer the above static method to `NessieIcebergClient`

**Comment by ajantha-bhat** [comment] 2023-06-23 09:12
As a quick fix,
I can probably remove `NESSIE_COMMIT_ID_PROPERTY` if exists from the Table property during committing from Trino (so it uses the latest reference state from the client)

But the other functionalities (like disabling GC) from `NessieTableOperations#loadTableMetadata` is still needed for Trino in the long run and can be updated with the next Iceberg version bump.

**Comment by nastra** [comment] 2023-06-23 09:40
I added a fix for this a while ago in https://github.com/nastra/trino/commit/34455ed43cb66b1dd2fc804292280ecf6238ab84 and forgot to follow-up after Nessie support was merged to Trino. The changes are obviously outdated, but it should give enough info on how to fix this @ajantha-bhat

**Comment by ajantha-bhat** [comment] 2023-06-23 10:39
> I added a fix for this a while ago in https://github.com/nastra/trino/commit/34455ed43cb66b1dd2fc804292280ecf6238ab84 and forgot to follow-up after Nessie support was merged to Trino. The changes are obviously outdated, but it should give enough info on how to fix this @ajantha-bhat

This approach seems to be what I mentioned as an alternate solution above in the note. This still needs an Iceberg side change of changing `UpdateableReference` to Public. Maybe that is why you depend on a snapshot Iceberg version in that fork. 

But instead of changing `UpdateableReference` to Public, I prefer moving the  `NessieTableOperations#loadTableMetadata` which also avoids replicating same at the Trino side.

**Comment by ajantha-bhat** [comment] 2023-07-07 01:53
Iceberg side fix https://github.com/apache/iceberg/pull/7893 is merged. With a new Iceberg release, we can work on a PR at Trino side to fix this issue.

**Comment by marvin-roesch** [comment] 2023-08-14 10:03
@ajantha-bhat What is the current state of this? We have mixed write access to some of our tables from Trino and Spark and this is currently blocking us from migrating to Iceberg. Iceberg has had a release since your PR was merged (1.3.1), but it doesn't appear to include the change. Do you know a rough estimate for when these changes might land in an Iceberg release?

**Comment by ajantha-bhat** [comment] 2023-08-21 02:14
@marvin-roesch: Yeah, we need Iceberg 1.4.0 release for this to work. 1.3.1 didn't include this change.  
Iceberg usually takes 2-3 months for a new version release. 

As a temporary workaround, maybe you can try removing this table property(`nessie.commit.id`) from spark. So that it can be queried from Trino.

**Comment by ajantha-bhat** [comment] 2023-11-27 05:07
@junshiwang: https://github.com/trinodb/trino/pull/19524 fixes this bug. 
If it is useful for you, please comment on the PR that it is needed. So, it can be taken as priority for review.

**Closed** 2023-12-15 07:04 UTC
Labels: bug, iceberg
