### ISSUE TITLE
Trino error while querying for DELETE and INSERT after inserting semicolon at end of query

### ISSUE THREAD

**Issue by PoojaGowda164** [trinodb/trino#19271] opened 2023-10-05 05:04 UTC
I'm trying to connect to trino and querying to delete rows and inserting rows for my Alteryx workflow. getting error after adding semicolon at the end of query which is a blocking currently the workflow. The same query works after removing semicolon. [After adding semicolon getting error](https://i.stack.imgur.com/STZkE.png) [Removing semicolon works fine](https://i.stack.imgur.com/zu05o.png)

I tried connecting to trino datasource using trino driver. example query DELETE FROM test_semicolon_pg without semicolon at end which works fine. but i expect the query should work fine even after adding adding semicolon at end of the query.

**Comment by ebyhr** [comment] 2023-10-05 08:43
Closing as duplicate of #18472

**Closed by ebyhr** 2023-10-05 08:43 UTC
