### ISSUE TITLE
Feature Request: Support non-integer types for the sequence table function

### ISSUE THREAD

**Issue by danielyahn** [trinodb/trino#24375] opened 2024-12-04 22:08 UTC
The [array sequence function supports](https://trino.io/docs/current/functions/array.html#sequence) support sequence of dates and timestamps. Could we have similar support with the [sequence table function](https://trino.io/docs/current/functions/array.html#sequence)?

**Comment by ebyhr** [comment] 2024-12-05 00:49
Closing as a duplicate of #20811

**Closed by ebyhr** 2024-12-05 00:49 UTC
