### ISSUE TITLE
failed to run the trino 426

### ISSUE THREAD

**Issue by chenrui333** [trinodb/trino#18983] opened 2023-09-10 14:26 UTC
While regression testing trino with some recent formulae upgrades, we found that the trino 418 (the current formula) and 426 both do not start, it just hangs with there.

This is the trino-server command that I am using (`config.properties` has been updated using an open port other than 8080)

```
$ /opt/homebrew/Cellar/trino/426/bin/trino-server run --verbose --config /Users/rui/Downloads/brew/trino/config.properties
config_path     = /Users/rui/Downloads/brew/trino/config.properties
data_dir        = /opt/homebrew/var/trino/data
etc_dir         = /opt/homebrew/Cellar/trino/426/libexec/etc
install_path    = /opt/homebrew/Cellar/trino/426/libexec
jvm_config      = /opt/homebrew/Cellar/trino/426/libexec/etc/jvm.config
jvm_options     = []
launcher_config = /opt/homebrew/Cellar/trino/426/libexec/bin/launcher.properties
launcher_log    = /opt/homebrew/var/trino/data/var/log/launcher.log
log_levels      = /opt/homebrew/Cellar/trino/426/libexec/etc/log.properties
log_levels_set  = False
node_config     = /opt/homebrew/Cellar/trino/426/libexec/etc/node.properties
pid_file        = /opt/homebrew/var/trino/data/var/run/launcher.pid
properties      = {'node.environment': 'homebrew', 'node.data-dir': '/opt/homebrew/var/trino/data'}
server_log      = /opt/homebrew/var/trino/data/var/log/server.log
verbose         = True

['java', '-cp', '/opt/homebrew/Cellar/trino/426/libexec/lib/*', '-server', '-XX:InitialRAMPercentage=80', '-XX:MaxRAMPercentage=80', '-XX:G1HeapRegionSize=32M', '-XX:+ExplicitGCInvokesConcurrent', '-XX:+HeapDumpOnOutOfMemoryError', '-XX:+ExitOnOutOfMemoryError', '-XX:-OmitStackTraceInFastThrow', '-XX:ReservedCodeCacheSize=256M', '-XX:PerMethodRecompilationCutoff=10000', '-XX:PerBytecodeRecompilationCutoff=10000', '-Djdk.attach.allowAttachSelf=true', '-Djdk.nio.maxCachedBufferSize=2000000', '-XX:+UnlockDiagnosticVMOptions', '-XX:+UseAESCTRIntrinsics', '-XX:-G1UsePreventiveGC', '-Dnode.environment=homebrew', '-Dnode.data-dir=/opt/homebrew/var/trino/data', '-Dlog.levels-file=/opt/homebrew/Cellar/trino/426/libexec/etc/log.properties', '-Dconfig=/Users/rui/Downloads/brew/trino/config.properties', 'io.trino.server.TrinoServer']
```

**Comment by martint** [comment] 2023-09-13 17:33
Can you get a thread dump of the process when it's hung?

**Comment by iMichka** [comment] 2023-11-04 19:46
I wanted to investigate this, but right now I am even stuck before being able to get a thread dump. I'm a maintainer of the Homebrew project and would like to get this issue fixed.

I am on macOS Ventura (Intel), and I ran:
`trino-server run --verbose`

This started 2 `cfprefsd` processes that ate 100% of CPU. While trying to kill the processes, it froze my Mac and had to do a hard reboot.

Are you maybe aware of this issue? I could not find anything related in the other issues.

**Comment by hashhar** [comment] 2023-11-06 07:13
> This started 2 cfprefsd processes that ate 100% of CPU. While trying to kill the processes, it froze my Mac and had to do a hard reboot.

Sounds like a JDK bug. What JDK are you using, Azul Zulu? See https://bugs.openjdk.org/browse/CODETOOLS-7903447.
Try with Temurin and see if you still have the issue.

**Comment by iMichka** [comment] 2023-11-07 22:37
It's happening with openjdk 11 and 17, which we provide in Homebrew.

Yes, the bug description is 100% this one, thanks for finding that out: https://bugs.openjdk.org/browse/CODETOOLS-7903447
I'll add a comment there too, to raise awareness.

Is there some entry point / mechanism / code in trino that would trigger this? Just to see if we can build a small reproducible example with minimal code.

**Comment by pavibhai** [comment] 2024-02-27 04:54
> Is there some entry point / mechanism / code in trino that would trigger this? Just to see if we can build a small reproducible example with minimal code.

@iMichka 

I have run into the same issue while testing Trino using JDK 17 from Homebrew. The symptoms are exactly as you called out
```This started 2 cfprefsd processes that ate 100% of CPU. While trying to kill the processes, it froze my Mac and had to do a hard reboot.```

In terms of the minimal test. I was able to get the failure with something as simple as this
```java
import io.trino.spi.connector.SchemaTableName

new SchemaTableName("schema1", "table1");
```

The above does require the following dependency that I used.
```
group: io.trino
artifact: trino-spi
version: 423 <did not try but might have the issue with other versions as well>
```

It fails with Homebrew JDK 17.0.10 but when I download the [17.0.2 archive](https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_macos-aarch64_bin.tar.gz) from jdk.net it runs successfully. Hope this helps.

Please do let me know if I can share any more detail.

**Comment by mosabua** [comment] 2024-05-06 20:45
Closing this since new Trino version now use Java 21. With 447 the requirement will change to Java 22. Please file a new issues if you have problems with these.

**Closed by mosabua** 2024-05-06 20:45 UTC
