### ISSUE TITLE
can't access trino-parsable data type using `describe` or using `information_schema.columns`

### ISSUE THREAD

**Issue by cpcloud** [trinodb/trino#21264] opened 2024-03-26 12:19 UTC
Accessing the type information from a struct column that contains a field with spaces in it returns a data type string that cannot be parsed by trino itself.

We rely on this type information in [Ibis](https://github.com/ibis-project/ibis) and right now we're unable to support structs with fields that contain spaces due to this behavior.

```
❯ trino --catalog memory --schema default
trino:default> create table t (x row("foo bar" bigint));
CREATE TABLE
trino:default> describe t;
 Column |        Type         | Extra | Comment
--------+---------------------+-------+---------
 x      | row(foo bar bigint) |       |
(1 row)

Query 20240326_121820_07186_nxepw, FINISHED, 1 node
Splits: 19 total, 19 done (100.00%)
0.14 [1 rows, 67B] [7 rows/s, 489B/s]

trino:default> create table s (x row(foo bar bigint));
Query 20240326_121827_07192_nxepw failed: line 1:31: mismatched input 'bigint'. Expecting: ')', ','
create table s (x row(foo bar bigint))

trino:default> select version();
 _col0
-------
 443
(1 row)

Query 20240326_121840_07202_nxepw, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0.03 [0 rows, 0B] [0 rows/s, 0B/s]
```

Is there a higher-fidelity way to access this information? How do retrieve the quoted fields?

**Comment by ebyhr** [comment] 2024-03-26 13:33
Closing as duplicate of https://github.com/trinodb/trino/issues/19442

**Closed by ebyhr** 2024-03-26 13:33 UTC
