### ISSUE TITLE
Error is logged when no stats for table on Postgres 14+

### ISSUE THREAD

**Issue by guyco33** [trinodb/trino#17065] opened 2023-04-17 12:59 UTC
On Postgres version 14, [reltuples](https://www.postgresql.org/docs/14/catalog-pg-class.html) contains `-1` If the table has never yet been vacuumed or analyzed, so connector should return empty statistics
https://github.com/trinodb/trino/blob/87828e197e13a285aad96454e47ee795f02eaf95/plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java#L916-L921

**Comment by ebyhr** [comment] 2023-04-17 22:35
Closing as duplicate of #17061

**Closed by ebyhr** 2023-04-17 22:35 UTC
