### ISSUE TITLE
Query Clickhouse is pretty slow

### ISSUE THREAD

**Issue by njalan** [trinodb/trino#22153] opened 2024-05-27 07:31 UTC
I am using clickhouse 406 and the same query is completed 1 second in clickhouse but it takes more than 1 minutes in trino.
Below is the query:
select * from  test
where  date(dt) >= date'2024-05-25'
and paramName  = cast('xxxxx' as varbinary)
order by dt desc
limit 100;

**Comment by ebyhr** [comment] 2024-05-27 08:04
The cause should be missing predicate pushdown. Closing as duplicate of #7100.

**Closed by ebyhr** 2024-05-27 08:04 UTC
