### ISSUE TITLE
Support S3A proxy configuration properties

### ISSUE THREAD

**Issue by chancez** [trinodb/trino#1132] opened 2019-07-16 17:23 UTC
I'm trying to get Presto to work in an restricted network, but have the ability to use S3/GCS using an http/https proxy. 

There's some options like `fs.s3a.proxy.host` in the hadoop `core-site.xml` that would be useful if Presto could support these options in the Hive connector's S3 configuration properties.

**Comment by yuokada** [comment] 2019-07-26 09:32
How about below variables?  Do we need to add more variables yet?

- fs.s3a.proxy.host		  
- fs.s3a.proxy.port		  
- fs.s3a.proxy.username
- fs.s3a.proxy.password
- fs.s3a.proxy.domain

**Comment by chancez** [comment] 2019-07-26 16:57
That seems sufficient.

**Comment by tooptoop4** [comment] 2020-01-18 08:45
@chancez did u solve this?

**Comment by chancez** [comment] 2020-01-20 19:07
I'm not using Presto currently as I've changed jobs. I haven't fixed this.

**Comment by tooptoop4** [comment] 2020-01-24 11:31
So i checked prestodb 220 does not use proxy but prestosql does (it gets it from linux env variables). After running a hive query you can see in the server.log: 2020-01-24T10:12:57.755Z        INFO    hive-hive-0     com.amazonaws.http.AmazonHttpClient     Configuring Proxy. Proxy Host: redact Proxy Port: redact

Problem is it does not allow setting them to empty.
I tried in presto jvm.config:
-Dhttp.proxyHost=
-Dhttp.proxyPort=
-Dhttps.proxyHost=
-Dhttps.proxyPort=

Query 20200124_111055_00000_rnt6x failed: Host name may not be empty
io.prestosql.spi.PrestoException: Host name may not be empty
        at io.prestosql.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:216)
        at io.prestosql.plugin.hive.util.ResumableTasks$1.run(ResumableTasks.java:38)
        at io.prestosql.$gen.Presto_328__0_220____20200124_111038_2.run(Unknown Source)
        at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Host name may not be empty
        at org.apache.http.util.Args.containsNoBlanks(Args.java:84)
        at org.apache.http.HttpHost.<init>(HttpHost.java:80)
        at com.amazonaws.http.apache.SdkProxyRoutePlanner.<init>(SdkProxyRoutePlanner.java:43)
        at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.addProxyConfig(ApacheHttpClientFactory.java:94)
        at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:75)
        at com.amazonaws.http.apache.client.impl.ApacheHttpClientFactory.create(ApacheHttpClientFactory.java:38)
        at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:324)
        at com.amazonaws.http.AmazonHttpClient.<init>(AmazonHttpClient.java:308)
        at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:229)
        at com.amazonaws.AmazonWebServiceClient.<init>(AmazonWebServiceClient.java:215)
        at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:682)
        at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:35)
        at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:32)
        at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:64)
        at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:28)
        at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
        at io.prestosql.plugin.hive.s3.PrestoS3FileSystem.createAmazonS3Client(PrestoS3FileSystem.java:756)
        at io.prestosql.plugin.hive.s3.PrestoS3FileSystem.initialize(PrestoS3FileSystem.java:252)
        at org.apache.hadoop.fs.PrestoFileSystemCache.createFileSystem(PrestoFileSystemCache.java:125)
        at org.apache.hadoop.fs.PrestoFileSystemCache.getInternal(PrestoFileSystemCache.java:92)
        at org.apache.hadoop.fs.PrestoFileSystemCache.get(PrestoFileSystemCache.java:65)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:361)
        at io.prestosql.plugin.hive.HdfsEnvironment.lambda$getFileSystem$0(HdfsEnvironment.java:71)
        at io.prestosql.plugin.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
        at io.prestosql.plugin.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:70)
        at io.prestosql.plugin.hive.HdfsEnvironment.getFileSystem(HdfsEnvironment.java:64)
        at io.prestosql.plugin.hive.BackgroundHiveSplitLoader.loadPartition(BackgroundHiveSplitLoader.java:306)
        at io.prestosql.plugin.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:280)
        at io.prestosql.plugin.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:105)
        at io.prestosql.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:209)
        ... 6 more

I saw then saw https://github.com/aws/aws-sdk-java/commit/54d9b9bdc6b622788d465e5fabc5f6b00b083ec8 handles setting no proxy

**Comment by timflannagan1** [comment] 2020-03-14 01:12
Can this be closed now that #3016 has been merged?

**Comment by tooptoop4** [comment] 2020-03-14 08:47
@timflannagan1 it has not been included in 331 release notes

**Comment by hashhar** [comment] 2022-03-04 22:33
@aczajkowski implemented ability to proxy connections to S3 in https://github.com/trinodb/trino/pull/11255.

Please reopen if it doesn't address the usecase.

**Closed by hashhar** 2022-03-04 22:33 UTC
Labels: enhancement
