### ISSUE TITLE
Flaky test testNonDeltaTablesCannotBeAccessed & testHiveViewsCannotBeAccessed in TestDeltaLakeMinioAndHmsConnectorSmokeTest: "Schema 'test_schema....' does not exist"

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#19799] opened 2023-11-17 15:55 UTC
https://github.com/trinodb/trino/actions/runs/6905645416/job/18789278949?pr=19797

```
Error:  Tests run: 127, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 145.8 s <<< FAILURE! -- in io.trino.plugin.deltalake.TestDeltaLakeMinioAndHmsConnectorSmokeTest
Error:  io.trino.plugin.deltalake.TestDeltaLakeMinioAndHmsConnectorSmokeTest.testNonDeltaTablesCannotBeAccessed -- Time elapsed: 13.90 s <<< ERROR!
io.trino.testing.QueryFailedException: line 1:1: Schema 'test_schemauf1ow1a40h' does not exist
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:133)
	at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:502)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:495)
	at io.trino.testing.AbstractTestQueryFramework.computeActual(AbstractTestQueryFramework.java:313)
	at io.trino.testing.AbstractTestQueryFramework.computeScalar(AbstractTestQueryFramework.java:323)
	at io.trino.testing.AbstractTestQueryFramework.computeScalar(AbstractTestQueryFramework.java:318)
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.testNonDeltaTablesCannotBeAccessed(BaseDeltaLakeConnectorSmokeTest.java:497)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1351)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:422)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:651)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
	Suppressed: java.lang.Exception: SQL: SHOW TABLES FROM test_schemauf1ow1a40h LIKE 'hive_table'
		at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:506)
		... 17 more
Caused by: io.trino.spi.TrinoException: line 1:1: Schema 'test_schemauf1ow1a40h' does not exist
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
	at io.trino.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowTables(ShowQueriesRewrite.java:290)
	at io.trino.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowTables(ShowQueriesRewrite.java:229)
	at io.trino.sql.tree.ShowTables.accept(ShowTables.java:72)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.rewrite.ShowQueriesRewrite.rewrite(ShowQueriesRewrite.java:226)
	at io.trino.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:54)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:92)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:86)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:274)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:209)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:850)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:153)
	at io.trino.$gen.Trino_testversion____20231117_152301_6598.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by findepi** [comment] 2023-11-17 15:55
cc @ebyhr

**Comment by findepi** [comment] 2023-11-17 16:29
https://github.com/trinodb/trino/actions/runs/6906231508/job/18790888931?pr=19800 

```
Error:  io.trino.plugin.deltalake.TestDeltaLakeMinioAndHmsConnectorSmokeTest.testNonDeltaTablesCannotBeAccessed -- Time elapsed: 14.70 s <<< ERROR!
io.trino.testing.QueryFailedException: line 1:1: Schema 'test_schema1xhz29z987' does not exist
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:133)
	at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:502)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:495)
	at io.trino.testing.AbstractTestQueryFramework.computeActual(AbstractTestQueryFramework.java:313)
	at io.trino.testing.AbstractTestQueryFramework.computeScalar(AbstractTestQueryFramework.java:323)
	at io.trino.testing.AbstractTestQueryFramework.computeScalar(AbstractTestQueryFramework.java:318)
	at io.trino.plugin.deltalake.BaseDeltaLakeConnectorSmokeTest.testNonDeltaTablesCannotBeAccessed(BaseDeltaLakeConnectorSmokeTest.java:497)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1351)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:422)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:651)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
	Suppressed: java.lang.Exception: SQL: SHOW TABLES FROM test_schema1xhz29z987 LIKE 'hive_table'
		at io.trino.testing.DistributedQueryRunner.executeWithQueryId(DistributedQueryRunner.java:506)
		... 17 more
Caused by: io.trino.spi.TrinoException: line 1:1: Schema 'test_schema1xhz29z987' does not exist
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
	at io.trino.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowTables(ShowQueriesRewrite.java:290)
	at io.trino.sql.rewrite.ShowQueriesRewrite$Visitor.visitShowTables(ShowQueriesRewrite.java:229)
	at io.trino.sql.tree.ShowTables.accept(ShowTables.java:72)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.rewrite.ShowQueriesRewrite.rewrite(ShowQueriesRewrite.java:226)
	at io.trino.sql.rewrite.StatementRewrite.rewrite(StatementRewrite.java:54)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:92)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:86)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:274)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:209)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:850)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:153)
	at io.trino.$gen.Trino_testversion____20231117_160947_6515.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:76)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by findepi** [comment] 2023-11-17 16:34
cc @martint since the test was last changed in https://github.com/trinodb/trino/pull/19769
(the throwing line was also changed, but this doesn't seem to be the direct cause)

**Comment by martint** [comment] 2023-11-17 18:30
The only thing that changed were moving to JUnit, running tests in parallel and using AssertJ. My guess is that there's an inherent race condition between the lines that create the database/schema via Hive and the query via Trino that might be triggered by things taking a bit longer due to other tests running in parallel. What guarantees does `runOnHive()` have in terms of its effects by the time the call returns?

```java
hiveHadoop.runOnHive("CREATE DATABASE " + schemaName);
hiveHadoop.runOnHive(format("CREATE TABLE %s.%s (id BIGINT)", schemaName, tableName));
ssertThat(computeScalar(format("SHOW TABLES FROM %s LIKE '%s'", schemaName, tableName))).isEqualTo(tableName);
```

**Comment by findepi** [comment] 2023-11-17 19:18
i believe `runOnHive` is synchronous.

**Comment by ebyhr** [comment] 2023-11-18 01:49
`hive.metastore-cache-ttl` in `BaseDeltaLakeConnectorSmokeTest` might be the cause.

**Comment by ebyhr** [comment] 2023-11-21 22:55
Reopened as testHiveViewsCannotBeAccessed also hit the issue. 
```
Error:    TestDeltaLakeAdlsConnectorSmokeTest>BaseDeltaLakeConnectorSmokeTest.testHiveViewsCannotBeAccessed:485->AbstractTestQueryFramework.computeScalar:318->AbstractTestQueryFramework.computeScalar:323->AbstractTestQueryFramework.computeActual:313 » QueryFailed line 1:1: Schema 'test_schema02z2vdwcqs' does not exist
```

https://github.com/trinodb/trino/actions/runs/6946701831/job/18899350033

**Comment by ebyhr** [comment] 2024-02-05 08:08
https://github.com/trinodb/trino/actions/runs/7780749536/job/21214070438

**Comment by findepi** [comment] 2024-02-06 10:33
https://github.com/trinodb/trino/actions/runs/7788194138/job/21237299009?pr=20582

```
Error:  Errors: 
Error:    TestDeltaLakeMinioAndHmsConnectorSmokeTest>BaseDeltaLakeConnectorSmokeTest.testHiveViewsCannotBeAccessed:517->AbstractTestQueryFramework.computeScalar:319->AbstractTestQueryFramework.computeScalar:324->AbstractTestQueryFramework.computeActual:314 » QueryFailed line 1:1: Schema 'test_schemamu9uqh6mgz' does not exist
[INFO] 
Error:  Tests run: 979, Failures: 0, Errors: 1, Skipped: 31
```

**Closed** 2024-02-21 11:49 UTC
Labels: bug

**Comment by findepi** [comment] 2024-02-26 16:17
@pajaks thank you for fixing this!
