### ISSUE TITLE
SHOW VIEWS method

### ISSUE THREAD

**Issue by Guesswhoisback99** [trinodb/trino#16910] opened 2023-04-06 09:51 UTC
I'd like to ask for `SHOW VIEWS` method. Have you consider to implement `SHOW VIEWS` in the same way as `SHOW TABLES` is done?

Motivation, when I want to remove all views I have to query `SELECT table_name FROM information_schema.views`

**Comment by ebyhr** [comment] 2023-04-06 10:00
Closing as duplicate of #2999

**Closed by ebyhr** 2023-04-06 10:00 UTC
