### ISSUE TITLE
Slow scan performance on Iceberg table with many small files due to 1-1 mapping IcebergSplit to Iceberg single FileScanTask

### ISSUE THREAD

**Issue by khaitranq** [trinodb/trino#12162] opened 2022-04-27 21:27 UTC
My perf experiment:
- Trino Cluster with 8 EC2 instances
- Two Iceberg tables with same content but different file settings: table A with 146K files, 1MB each and table B with 1460 files, 100MB each.
- Scan on table A (`select count(*) from A`) is 25 times slower than scan on table B (`select count(*) from B`)

Root cause:
- Currently [each Iceberg split is mapped to a single data file scan](https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java#L379), so scan table A created 146K splits while scan table B created only 1460 splits. The overheads of scheduling and reading small files dominate the actual useful work here.
- Iceberg table scan can [group small files together](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/BaseTableScan.java#L207) into `CombinedScanTask` using [binpacking ](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/util/TableScanUtil.java#L77). However, in `IcebergSplitSource`, we [flat this combined scan tasks into individual file scans,](https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java#L170) loosing the advantage of bin packing in Iceberg table scan.

Suggested solution:
- Change IcebergSplit structure to work with multiple file scans
- Map CombinedScanTask, instead of single FileScanTask, to each IcebergSplit

**Comment by rdblue** [comment] 2022-04-27 21:36
@khaitranq, have you tested using combined splits in Trino to see if that does fix the problem? It could be that the problem is simply the latency to S3 for that many files and that the task grouping doesn't matter.

If you don't want to modify Trino to test, you could try running the combined test case in Spark, although Spark does really bad with lots of splits.

**Comment by khaitranq** [comment] 2022-04-27 21:41
@rdblue We don't have that issue with Spark as Spark uses combined scan tasks. Trino cannot use combined split as each IcebergSplit is mapped into single FileScanTask, as I shared the code pointers above.

**Comment by khaitranq** [comment] 2022-04-27 21:42
With Spark, scan table A and scan table B have similar performance (scan table B was actually a bit better, but not with such wide gap as in Trino)

**Comment by alexjo2144** [comment] 2022-04-28 19:07
Does the bin packing have any tuning parameters? I'm just thinking there are clearly situations where combing splits would be better, but for small tables with only a few files we want them separate.

**Comment by khaitranq** [comment] 2022-04-28 19:13
Yes, I believe you can use a weight function to control the bin size. I found an example here:
https://github.com/apache/iceberg/blob/0.13.x/core/src/main/java/org/apache/iceberg/util/TableScanUtil.java#L71

Is that correct, @rdblue ?

**Comment by rdblue** [comment] 2022-04-28 19:50
@alexjo2144, Split combining is one of the tuning settings that Iceberg moves to table config. The primary way to configure this is by setting `read.split.target-size` in table properties. You can also tune `read.split.open-file-cost` and `read.split.planning-lookback`.

In Spark, we also allow overriding this using scan options at runtime. That would probably be done through session properties in Trino, right? Maybe introduce a convention for creating properties, like `db.table.target-split-size` or something? I definitely recommend allowing overriding this per table. The per-query settings can do the wrong thing when a query scans a large table and a small table, or even a small part of a large table.

**Comment by alexjo2144** [comment] 2022-05-03 21:18
I did some experimenting with this today, big caveat is that this is just a single node setup running on my computer not a real environment, but that said...

I created a copy of the tpch orders table with the data divided over ~160 files. Using the bin packed approach to bundle several files into the same split rather than the current approach improved query runtime pretty dramatically. Reducing the runtime of `select sum(totalprice) from orders` from ~1 sec to ~260 ms.

**Comment by khaitranq** [comment] 2022-05-04 02:41
Excellent! @alexjo2144. So how many slits did you get before (probably 160?) and after using bin-packing?

**Comment by alexjo2144** [comment] 2022-05-12 22:13
I just pushed a draft PR with an initial approach. Thanks @przemekak for offering to help with benchmarking the problem.

**Comment by FrommyMind** [comment] 2023-09-01 09:55
> 



> I did some experimenting with this today, big caveat is that this is just a single node setup running on my computer not a real environment, but that said...
> 
> I created a copy of the tpch orders table with the data divided over ~160 files. Using the bin packed approach to bundle several files into the same split rather than the current approach improved query runtime pretty dramatically. Reducing the runtime of `select sum(totalprice) from orders` from ~1 sec to ~260 ms.
> 
> Here's my POC: [alexjo2144@efa30d1]
(https://github.com/alexjo2144/trino/commit/efa30d1fec9b6593a39552f897e72ec533c0e619)

@alexjo2144 
the link you shared here is not working, could you please give a new link?
Thansk a lot.

**Comment by alexjo2144** [comment] 2023-09-08 14:21
Hey @FrommyMind, I don't have a link to that exact code anymore but I the original issue we were trying to solve here was addressed by attaching weights to Iceberg splits. This enables the Trino engine to bundle small reads together similarly to how Iceberg's bin packing works. Here's the PR that included that: https://github.com/trinodb/trino/pull/12579

I am going to go ahead and close this

**Closed by alexjo2144** 2023-09-08 14:21 UTC
Labels: performance
