### ISSUE TITLE
Investigate why `TestBigQueryAvroConnectorTest.testSelectInformationSchemaColumns` took 15 minutes

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#15612] opened 2023-01-05 10:39 UTC
https://github.com/trinodb/trino/actions/runs/3844470384/jobs/6547614598

```
INFO	pool-3-thread-2	io.trino.testng.services.ProgressLoggingListener	[TEST SUCCESS]
io.trino.plugin.bigquery.TestBigQueryAvroConnectorTest.testSelectInformationSchemaColumns; (took: 15 minutes and 46 seconds)
```

This may relate to #10741

**Comment by ebyhr** [comment] 2023-01-05 10:40
It's about 9 minutes in https://github.com/trinodb/trino/actions/runs/3838262766/jobs/6535279415
```
Test io.trino.plugin.bigquery.TestBigQueryAvroConnectorTest.testSelectInformationSchemaColumns took 8.92m
```

**Comment by findepi** [comment] 2023-01-05 13:03
is `testSelectInformationSchemaColumns` related to avro usage? since we're covering metadata queries there, maybe we can skip it for avro?

cc @hashhar

**Comment by hashhar** [comment] 2023-01-05 13:49
This is probably because we have view expiration set to 1 day and we accumulate a lot of those. Currently I see >500 views materialized with over 2.8k columns.

We *can* skip the info schema test in Avro and only run it in Arrow (or other way around) but it just hides the cause.

**Comment by hashhar** [comment] 2023-01-05 13:51
It's interesting because in `BigQueryQueryRunner` we do set view expiration to be 30m but in the BigQuery project itself I see objects with 24 hour expiration. I'll check and send PR accordingly.

**Comment by hashhar** [comment] 2023-03-03 07:08
This is fixed by cleaning up old leftovers and making sure all query runners with BigQuery use a 30m view expiration instead of default of 24 hour.

**Closed by hashhar** 2023-03-03 07:08 UTC
Labels: test
