### ISSUE TITLE
Support SET SESSION AUTHORIZATION

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#2512] opened 2020-01-15 09:02 UTC
This is follow up of https://github.com/prestosql/presto/pull/2309#issuecomment-571781252

This could be used to set session user or set session extra credential.

>We'd want this to use standard syntax like SET SESSION AUTHORIZATION. The SQL standard doesn't seem to define the access model and leaves it up to the implementation:
>
>If V is not equal to the current value of the SQL-session user identifier of the current SQL-session context, then the restrictions on the permissible values for V are implementation-defined.
>
>It's more complicated because there are two different models, similar to setuid vs seteuid in UNIX. The PostgreSQL implementation is like seteuid -- the access check is based on the originally authenticated user. Thus, it is possible to temporarily become an unprivileged user, then switch back.
>
>The model you want is like setuid -- the access check is based on the current user. Thus, switching users permanently revokes all of privileges of the current user. For example, user A could switch to user B, but then would not be allowed to switch back to A.

PostgreSql docs: https://www.postgresql.org/docs/current/sql-set-session-authorization.html

**Comment by phd3** [comment] 2023-02-14 00:13
From https://github.com/trinodb/trino/pull/2671#issuecomment-677905852

Relevant parts of the SQL spec:

> ## 4.40.1.1 SQL-session authorization identifiers
>
> An SQL-session has a user identifier called the SQL-session user identifier. When an SQL-session is initiated, the SQL-session user identifier is determined in an implementation-defined manner, unless the session is initiated using a `<connect statement>`. The value of the SQL-session user identifier can never be the null value. The SQL-session user identifier can be determined by using SESSION_USER.
>
> An SQL-session context contains a time-varying sequence of cells, known as the authorization stack, each cell of which contains a user identifier, a role name, or both. This stack is maintained using a “last-in, first-out” discipline, and effectively only the top cell is visible. When an SQL-session is started, by explicit or implicit execution of a `<connect statement>`, the authorization stack is initialized with one cell, which contains only the user identifier known as the SQL-session user identifier; a role name, known as the SQL-session role name may be added subsequently.
>
> Execution of a `<routine invocation>`, `<externally-invoked procedure>`, triggered action, `<execute statement>`, or `<direct SQL statement>` X pushes a new cell onto the top of the authorization stack. This new cell might be a copy of the existing top cell, a routine authorization identifier, or the authorization identifier of a module owner, schema owner, or prepared statement owner, as prescribed by the applicable General Rules. After execution of X completes, the top cell is removed.
>
> The contents of the top cell in the authorization stack of the current SQL-session context determine the privileges for the execution of each SQL-statement. The user identifier, if any, in this cell is known as the current user identifier; the role name, if any, is known as the current role name. They may be determined using CURRENT_USER and CURRENT_ROLE, respectively.
>
> At a given time, there may be no current user identifier or no current role name, but at least one or the other is always present.
>   NOTE 103 — The privileges granted to PUBLIC are available to all of the `<authorization identifier>`s in the SQL-environment.
>
>The `<set session user identifier statement>` changes the value of the current user identifier and of the SQL- session user identifier. The `<set role statement>` changes the value of the current role name.
>
>The term current authorization identifier denotes an authorization identifier in the top cell of the authorization stack.


> ## 19.2 `<set session user identifier statement>`
>
> 1) If a `<set session user identifier statement>` is executed and an SQL-transaction is currently active, then an exception condition is raised: invalid transaction state — active SQL-transaction.
> 2) Let S be `<value specification>` and let V be the character string that is the value of `TRIM ( BOTH ' ' FROM S )`
> 3) If V does not conform to the Format and Syntax Rules of an <authorization identifier>, then an exception condition is raised: invalid authorization specification.
> 4) If V is not equal to the current value of the SQL-session user identifier of the current SQL-session context, then the restrictions on the permissible values for V are implementation-defined.
> 5) If the current user identifier and the current role name are restricted from setting the user identifier to V, then an exception condition is raised: invalid authorization specification.
> 6) The SQL-session user identifier of the current SQL-session context is set to V.
> 7) The current user identifier is set to V.
> 8) The current role name is removed.
>    NOTE 723 — The current role name is also the SQL-session role name.


To summarize:
* There's a session user that's established when the session starts. That can be obtained with the SESSION_USER expression.
* There's a an authorization stack that starts with a single cell when the session is initiated. Actions such as calling a routine, or executing a query push a new cell on the stack -- the value of the cell can came from a variety of places, but typically, it's a copy of the current cell. 
* Cells in the authorization stack can contain a user, a role or both. The values can be inspected via the CURRENT_USER and CURRENT_ROLE expressions, respectively.
* The value of the user identifier in the current cell can be changed via `SET SESSION AUTHORIZATION`. It is implementation-defined whether the current user is allowed to change the current user to the desired one.

**Comment by phd3** [comment] 2023-03-06 22:49
@martint Wanted to discuss about `roles` and `authorizationUser`. Based on the spec above, would the following behavior make sense ?


Terminology: in Trino world, we will have the following in the "Identity" : original user (i.e. X-Trino-User), authorization user (i.e. X-Trino-Authorization-User introduced), and roles (R).
* if client sends originalUser=S, role=R and query is `SET SESSION AUTHORIZATION T` => check if (user=S, role=R) is allowed to impersonate T. If the check succeeds, the query is success and next query executes as `(user=T, role={})`.
* for next queries, client will send originalUser=S, user=T, roles=R  (any query) => then R is ignored after impersonation check, and identity will not use any roles.
* RESET SESSION AUTH will revert to `(user=S, role=R)`.
* If client sends originalUser=S, authorizationUser=T and query is `SET ROLE x` => the role gets validated against S. (This part seems a bit iffy to me - but not sure if there's a better solution. May be SET ROLE spec will make it clear? )

The above seems to be consistent with the fact that we don't propagate roles in view session. It also removes role as mentioned in spec. (i.e. It assumes that when client sends originalUser=S, authorizationUser=T, role=R =>  S is setting role R and then (S,R) is setting authorization user T. rather than S setting T and then S/T setting R. ) However - one disadvantage is that - we're essentially not allowing roles to be used corresponding to the authorization user.

**Comment by phd3** [comment] 2023-03-06 22:50
FWIW - I looked at Postgres doc and it seems they consider the authorization user to determine what is alllowed in SET ROLE. But I'm not sure if they're entirely following the spec as they seem to change current_user even with SET ROLE - which Trino isn't doing. 

> SET ROLE has effects comparable to [SET SESSION AUTHORIZATION](https://www.postgresql.org/docs/current/sql-set-session-authorization.html), but the privilege checks involved are quite different. Also, SET SESSION AUTHORIZATION determines which roles are allowable for later SET ROLE commands, whereas changing roles with SET ROLE does not change the set of roles allowed to a later SET ROLE.

https://www.postgresql.org/docs/current/sql-set-role.html 
https://www.postgresql.org/docs/current/sql-set-session-authorization.html

**Comment by baohe-zhang** [comment] 2023-03-07 19:02
I did some investigation on how other databases handle roles handover during set session authorization.

PostgreSQL
PostgreSQL has 2 concepts of users, session_user and current_user. The session_user is normally the user who initiated the current database connection; but superusers can change this setting with SET SESSION AUTHORIZATION. The current_user is the user identifier that is applicable for permission checking. Normally it is equal to the session user, but it can be changed with SET ROLE. And the SET ROLE permission check is based on the session_user.

RESET ROLE sets the current user identifier to the current session user identifier.
RESET SESSION AUTHORIZATION reset the session and current user identifiers to be the originally authenticated user name.

Example:
// login in as u1, session_user=u1, current_user=u1

SET ROLE r1; // Check if session_user u1 can set role r1, if yes session_user=u1, current_user=r1

SET SESSION AUTHORIZATION u2; // Check if the original session_user u1 has the superuser privilege, if yes session_user=u2, current_user=u2

SET ROLE r2; // Check if current session_user u2 can set role r2, if yes session_user=u2, current_user=r2

RESET ROLE; // session_user=u2, current_user=u2

RESET SESSION AUTHORIZATION; // session_user=u1, current_user=u1

IBM DB2
IBM DB2 has 2 concepts of users, SYSTEM_USER and SESSION_USER. SYSTEM_USER is the authenticated user and can't be changed during the connection. SESSION_USER is the authorization ID and is used for data access authorization. SESSION_USER can be updated by the SET SESSION AUTHORIZATION command and the check is based on SYSTEM_USER's impersonation privilege.

In IBM DB2, all roles that are granted to a user are always enabled and cannot be disabled. The SET ROLE command is to verify whether the authorization ID (SESSION_USER) is a member of a specific role.

// login in as u1, SYSTEM_USER=u1, SESSION_USER=u1, ROLE=<all u1's roles>

SET SESSION AUTHORIZATION u2; // Check if the SYSTEM_USER u1 has the privilege to impersonate u2, if yes SYSTEM_USER=u1, SESSION_USER=u2, ROLE=<all u2's roles>

SET SESSION AUTHORIZATION SYSTEM_USER; // Switch back to SYSTEM_USER u1. SYSTEM_USER=u1, SESSION_USER=u1, ROLE=<all u1's roles>

MySQL, Oracle, SQL Server
SET SESSION AUTHORIZATION is not supported.

**Comment by phd3** [comment] 2023-03-09 02:07
SET ROLE spec - courtesy Martin:

<img width="613" alt="image" src="https://user-images.githubusercontent.com/6829746/223897293-6b0a8d51-7b31-4085-a810-db4145eb57bd.png">

**Comment by phd3** [comment] 2023-03-09 04:31
@martint Given this specs above - did another attempt at defining the behavior. would the following be reasonable ? (Using this terminology : X-Trino-User=sessionUser, X-Trino-Authorization-User=authorizationUser, X-Trino-Role=role)

* AuthorizationUser and sessionUser is the same if the former is not explicitly given by client
* Role is logically always tied to the authorizationUser
* For an incoming query - if headers corresponding to sessionUser, authorizationUser are different and role R is present:
   * check if (user, role=None) can set authorizationUser
   * check if authorizationUser can set role R.
   * Run a query with identity (user=authorizationUser, role=R). [If no roles - then use authorizationUser’s enabled roles]
* When SET ROLE R is executed: 
   * check against authorizationUser value. 
   * Set Role header.
   * Next queries execute using (authorizationUser, role=R)
* When RESET ROLE is executed:
   * No changes to the authorizationUser. 
   * Remove role.
* When SET SESSION AUTHORIZATION X is executed => 
   * If sessionUser is the same as authorizationUser:
     * Check for impersonation of X against existing (sessionUser, role) 
     * If so - set the header. Remove role. Next queries execute as (x, none).
    * Else:
      * Check for impersonation against existing (sessionUser, none).
      * If so - set the header. Remove role. next queries execute as (x, none).
* When RESET SESSION AUTHORIZATION is executed:
   * If sessionUser != authorization user: 
      * Remove Authorization user. 
      * Also remove the role.
      * Next queries should run as sessionUser.
   * else:
       * like above % Keep the role as is.

**Comment by baohe-zhang** [comment] 2023-03-21 20:40
Hi @martint @kokosing , Could you review the behavior of the handover of the role proposed by @phd3 when you get a chance?

**Comment by kokosing** [comment] 2023-03-22 10:36
```
When SET SESSION AUTHORIZATION X is executed =>
 - If sessionUser is the same as authorizationUser:
    - Check for impersonation of X against existing (sessionUser, role)
```
Shouldn't we have  `Check for impersonation of X against existing (sessionUser, none)` as `Role is logically always tied to the authorizationUser`?

**Comment by baohe-zhang** [comment] 2023-03-23 23:42
Hi @kokosing 
```
SET SESSION AUTHORIZATION u1;
SET ROLE r1;
SET SESSION AUTHORIZATION u2;
SET ROLE r2;
```
`SET SESSION AUTHORIZATION u2; ` in this case would fail as well. 

```
When SET SESSION AUTHORIZATION X is executed =>
If sessionUser is the same as authorizationUser:
Check for impersonation of X against existing (sessionUser, role)
If so - set the header. Remove role. Next queries execute as (x, none).
Else:
Check for impersonation against existing (sessionUser, none).
If so - set the header. Remove role. next queries execute as (x, none).
```
In this case, the authorizationUser is u1, and is different from the session user, hence the set session authorization u2 will only check against (sessionUser, none), instead of (sessionUser, role). And the check will fail as sessionUser can't impersonate u2.

**Comment by baohe-zhang** [comment] 2023-03-27 22:20
@kokosing Can I go ahead and implement the behavior of roles as suggested by phd3?

**Comment by kokosing** [comment] 2023-03-29 18:57
I would like to hear also opinion about this from @dain and @martint . This is security related feature so I would prefer to be sure we are going in correct direction.

**Comment by baohe-zhang** [comment] 2023-04-19 21:23
Below is a state changes matrix that's derived from the behavior defined above https://github.com/trinodb/trino/issues/2512#issuecomment-1461263474

please review it when you get a chance. @phd3 @martint @kokosing 

execution | check against | X-Trino-User (sessionUser) | X-Trino-Authorization-User (authorizationUser) | X-Trino-Role (role)
-- | -- | -- | -- | --
login as U |   | U | None | None
SET ROLE R | check against authorizationUser if it's non-empty and is different from sessionUser, otherwise sessionUser | remain unchanged | remain unchanged | R
RESET ROLE |   | remain unchanged | remain unchanged | None
SET AUTHORIZATION X | check against sessionUser if authorizationUser is non-empty and is different from sessionUser, otherwise sessionUser and role | remain unchanged | X | None
RESET AUTHORIZATION |   | remain unchanged | None | None if authorizationUser is non empty and is different from sessionUser, otherwise remain unchanged

**Comment by phd3** [comment] 2023-05-07 23:58
Thanks @baohe-zhang . I made some edits to the table above (removed authorization-role req, tied role to current user, and added checks with more verbosity):

| Step | Command                      | New authorization Checks for this query | Authorization checks for next select 1 query           | SELECT SESSION_USER (Not implemented in trino yet, but expected behavior) | SELECT CURRENT_USER (=> means implied from session user) | SELECT CURRENT_ROLE  (Not implemented in trino yet, but expected behavior) | Output of “Show Roles”  (Follows current role) | Output of “Show current roles” Here “current” just means enabled.  (Follows current role) |
|------|------------------------------|-----------------------------------------|--------------------------------------------------------|---------------------------------------------------------------------------|----------------------------------------------------------|----------------------------------------------------------------------------|------------------------------------------------|-------------------------------------------------------------------------------------------|
| 1    | Login as user u1             | NA                                      | NA                                                     | u1                                                                        | => u1                                                    | => Empty                                                                   | [r11, r12]                                     | Emptyset                                                                                  |
| 2    | SET ROLE r11                 | Can u1 set the role r11?                | Can u1 set the role r11?                               | u1                                                                        | => u1                                                    | => r11                                                                     | [r11, r12]                                     | [r11]                                                                                     |
| 3    | SET SESSION AUTHORIZATION u2 | Can (u1, r11) impersonate u2?           | Can (u1, ALL) impersonate u2?                          | u1                                                                        | u2                                                       | Empty (SET SESSION AUTH removes current role)                              | [r21, r22]                                     | []                                                                                        |
| 4    | SET ROLE r21                 | Can u2 set the role r21?                | Can (u1,ALL) impersonate  u2? Can u2 set the role r21? | u1                                                                        | u2                                                       | r21                                                                        | [r21, r22]                                     | [r21]                                                                                     |
| 5    | SET SESSION AUTHORIZATION u3 | Can (u1, ALL) impersonate u3?           | Can (u1,ALL) impersonate  u3?                          | u1                                                                        | u3                                                       | Empty                                                                      | [r31, r32]                                     | []                                                                                        |
| 7    | RESET SESSION AUTHORIZATION  | -                                       | -                                                      | u1                                                                        | => u1                                                    | => Empty                                                                   | [r11, r12]                                     | []                                                                                        |

**Comment by phd3** [comment] 2023-05-07 23:58
@martint I think this covers the spec in a reasonable way. Please feel free to check out the table above showing the "state" for intended behavior. Some key points below:

* When the user joins, they’ve some login user `U1`. The “Role” is always tied to the “current user”. Initially that’s the same as the session user. So `Set Role` statement considers U1’s enabled roles.
* `SET SESSION AUTHORIZATION U2` removes current role if any. This is aligned with Bullet-8 in the spec. Further `SET ROLE` operations consider `U2`’s enabled roles.
* `SET SESSION AUTHORIZATION` considers original session user for impersonation checks. `RESET SESSION AUTHORIZATION` sets current user back to original session user. 
* `Show Roles` and `Show Current Roles` commands in Trino demonstrate the roles tied to the authorization users as seen in the table.
* `CURRENT_USER` implementation in this PR should reflect the desired changes shown above.
* `SELECT SESSION_USER` is not currently implemented. We can choose to always implement that to reflect U1. However, this will violate this statement in the spec.
* `SELECT CURRENT_ROLE` is not currently implemented. But when we do - we should display the current user’s roles as shown in table.
* `SET SESSION AUTHORIZATION` or `SET ROLE` within a transaction is rejected.

**Comment by phd3** [comment] 2023-05-07 23:58
The only thing we're violating from the spec is the following, which asks that when with SET SESSION AUTHORIZATION - we should change session user as well.  

```
The <set session user identifier statement> changes the value of the current user identifier and of the SQL- session user identifier. The <set role statement> changes the value of the current role name.
```

IMO since we don't really have a persisted session - we should just keep the same original session user around. If you think it's strongly needed - we can implement the `SELECT SESSION_USER` to return the authorization user if needed.

**Comment by baohe-zhang** [comment] 2023-05-09 20:57
@phd3 Thanks for defining the behaviors! I would like to add some use cases of SET SESSION AUTHORZAITION in trino's context:

- Drop superuser privilege
A superuser u1 can run SET SESSION AUTHORIZATION u2 to temporarily become an unprivileged user u2. After that, the privileges for the execution of each SQL statement will be determined by the unprivileged user u2. The end user can later switch back to the superuser by running RESET SESSION AUTHORIZATION. This feature can effectively avoid the incidents such as an intern drops a production dataset by mistake.

- Impersonate as a service account to obtain table access
For example, The Trino team at LinkedIn has a service account trino_dev, and trino_dev has permanent access to some datasets that contain trino operational data. A developer who is a member of the trino_dev can run SET SESSION AUTHORIZATION trino_dev to impersonate as trino_dev and run queries on behalf of trino_dev. In that case, a developer under the trino team can access the trino operation data without explicitly requesting the related dataset access permissions.

**Comment by baohe-zhang** [comment] 2023-05-12 06:48
Here is the link to the design doc of this feature: https://docs.google.com/document/d/1aG0VU0mSv4CkG-DUNqbkhzWCvdD-uLLpirKG_O9sCSo/edit?usp=sharing

**Comment by martint** [comment] 2023-06-06 23:17
Can you remind me of what `(u1, ALL)` means in the table above? What is `ALL` in that context?

One discrepancy I'm observing vs the SQL spec:

For `SET SESSION AUTHORIZATION`:
> The **SQL-session user identifier** of the current SQL-session context is set to V.
> The current user identifier is set to V.
> The current role name is removed.

I think I finally understand what the purpose of `SET SESSION AUTHORIZATION` is in the SQL spec. It's meant for changing the user of the session the client is interacting with, nothing more -- the current user identifier is updated as a side effect of that action. 

The only way the session user identifier and the current user identifier can differ is within the context of the invocation of a function or routine. That will cause the current user stack to get one level deeper and will fill in the top of the stack with according to a couple of different rules depending on whether the function is external, whether its authorization model is `DEFINER` and its associated authorization identifier.

In light of that, I think we may need to adjust the model to include a Trino-specific "saved session authorization" that gets set to the current value of the session user identifier when SET SESSION AUTHORIZATION is invoked, and gets restored when RESET SESSION AUTHORIZATION is called.

**Comment by baohe-zhang** [comment] 2023-06-07 00:15
Hi @martint 
Here (u1, ALL), ALL means all of user u1's granted roles. We do the authorization checks against the combination of u1 and all of its roles.  

For Trino-specific "saved session authorization" , let's say if the logged-in user `u1` executes `SET SESSION AUTHORIZATION u2`, then both `SELECT SESSION_USER` and `SELECT CURRENT_USER` should return `u2`. Later when the user executes `RESET SESSION AUTHORIZATION`, both `SELECT SESSION_USER` and `SELECT CURRENT_USER` should return `u1`. Is my understanding correct?

**Comment by phd3** [comment] 2023-06-07 15:28
@martint Trying to understand this better: In the current PR model, we've the pre-existing `X-Trino-User` and the newly introduced `X-Trino-Authorization-User`. If we define the mapping to SQL spec's `SESSION_USER` as `X-Trino-Authorization-User != null ? X-Trino-Authorization-User : X-Trino-User`, then it'll have the same behavior as what you mentioned right?

In the adjustment you proposed, looks like the difference is that we introduce a new holder for the "original" user rather than for the "new" user. So the mapping of `SESSION_USER` and `CURRENT_USER` is cleaner and more direct mapping to `X-Trino-User`. The new "saved" user (e.g. `X-Trino-Saved-Session-Authorization`) will only be used for initial impersonation checks (principal -> saved and saved -> x-trino-user). Roles will be tied to `X-Trino-User`.

So overall, the table above will remain the same except SESSION_USER/CURRENT_USER columns will be identical.

However, for user-attribution/auditing, I think it's useful that this "saved user" still makes it to query completion events. So we should still propagate it through the query lifecycle in the session. 

wdyt?

**Comment by findepi** [comment] 2023-09-01 08:26
Support SET SESSION AUTHORIZATION and RESET SESSION AUTHORIZATION #16067 was merged.

**Closed** 2023-09-01 08:34 UTC
Labels: enhancement, syntax-needs-review
