### ISSUE TITLE
SQL with CURRENT_TIME fails when connecting to the Presto server using 348 or latest presto JDBC driver

### ISSUE THREAD

**Issue by AdarshdeepCheema** [trinodb/trino#6618] opened 2021-01-15 20:27 UTC
Connect to any Presto DB server( In our case it is Presto 350 version of Database), using the presto 348 or latest JDBC driver.

Execute the SQL similar to mentioned below:
Select CURRENT_TIME, Column_From_Table1 from Table1

Error: Error executing query
SQLState:  null
ErrorCode: 0

NOTE: this issue is not happening when using 347 or earlier released JDBC driver.

**Comment by martint** [comment] 2021-01-15 20:42
Does the query fail if you run it from the CLI? Can you provide the full stacktrace of the error?

**Comment by AdarshdeepCheema** [comment] 2021-01-15 20:50
I am running it in Squirrel, That is the only error I am seeing in Squirrel. 
How can I get the trace ?

**Comment by martint** [comment] 2021-01-15 21:02
I'm not familiar with Squirrel, so I wouldn't know. 

Let's try to narrow it down further. Can you try the following query?

```
SELECT current_time
```

**Comment by AdarshdeepCheema** [comment] 2021-01-15 21:07
Same issue, only when using 348 + jdbc driver version

**Comment by martint** [comment] 2021-01-15 21:27
I just tried this and I'm not able to reproduce it. 

Do you see any errors on the server logs?

**Comment by AdarshdeepCheema** [comment] 2021-01-18 21:03
We do not see any log getting generated on the server-side, when we run the SQL in Squirrel(third party tool) as well as when we try to use current_time in any SQL using our Cognos BI tool.

Running the command for the CLI as the following results:
presto> SELECT current_time;
       _col0
--------------------
 09:29:56.220-05:00
(1 row)
Query 20210118_142955_01134_ujgmy, FINISHED, 1 node
Splits: 17 total, 17 done (100.00%)
0.08 [0 rows, 0B] [0 rows/s, 0B/s]
presto>

**Comment by AdarshdeepCheema** [comment] 2021-03-17 18:44
just an FYI: it also happens when we use current_date,current_timestamp,localtime,localtimestamp

I tried trino 353 jdbc as well and it also shows the same issue.

**Comment by findepi** [comment] 2021-03-17 19:05
> I tried trino 353 jdbc as well and it also shows the same issue.

Trino 353 JDBC driver is not compatible with releases before <= 350.
Can i assume you upgrade the server to 353 as well?

Can you share the error your seeing in Squirrel?

**Comment by AdarshdeepCheema** [comment] 2021-03-18 01:29
Sorry.. I did not know that Trino 353 JDBC driver is not compatible with 350 sever. But I was able to connect and I was seeing the same error when connected to Server 350 with 348 jdbc driver 

Error in squirrel when using 348 and latest driver with 350 servers:
**Error: Error executing query
SQLState: null
ErrorCode: 0**

**Comment by findepi** [comment] 2021-03-19 11:24
you can check the Trino server UI exposed over http. this will get you query history and failure stacktrace as well

**Comment by hashhar** [comment] 2024-02-26 11:35
![Screenshot 2024-02-26 at 5 04 01 PM](https://github.com/trinodb/trino/assets/10473142/cec95db2-8834-4263-b330-7392184d46fb)

I can no longer reproduce the issue.

Closing, feel free to re-open if you still run into this issue.

Note that for some data types to show properly you need to enable handling Unknown types in Squirrel by going to File > Global Preferences > Data Type Controls > check the box under Unknown DataTypes section. Otherwise you may see results like below.

![Screenshot 2024-02-26 at 5 02 27 PM](https://github.com/trinodb/trino/assets/10473142/0574b0dd-4388-43c1-ac04-84fc247a9101)

**Closed by hashhar** 2024-02-26 11:35 UTC
Labels: bug
