### ISSUE TITLE
Fault-tolerant tests have flaky init

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#14035] opened 2022-09-07 14:54 UTC
Fault-tolerant / faulttolerant. For example `TestHiveTaskFailureRecoveryTest.init` failed in https://github.com/trinodb/trino/runs/8228073689?check_suite_focus=true with 

```
Error:  io.trino.faulttolerant.hive.TestHiveTaskFailureRecoveryTest.init  Time elapsed: 225.711 s  <<< FAILURE!
java.lang.RuntimeException: 
Error fetching next at http://127.0.0.1:40205/v1/statement/executing/20220907_135132_00013_vg4hy/y379558b510cc93ad493389051f1603855f39b07b/1 returned an invalid response: JsonResponse{statusCode=500, statusMessage=Internal Server Error, headers={content-length=[1016], content-type=[text/plain], date=[Wed, 07 Sep 2022 13:51:34 GMT]}, hasValue=false} [Error: java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.common.util.concurrent.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1543)
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:586)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:240)
	at com.google.common.util.concurrent.Futures.getDone(Futures.java:1181)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1130)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
]
	at io.trino.client.StatementClientV1.requestFailedException(StatementClientV1.java:453)
	at io.trino.client.StatementClientV1.advance(StatementClientV1.java:392)
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:99)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:480)
	at io.trino.plugin.hive.HiveQueryRunner.copyTableBucketed(HiveQueryRunner.java:375)
	at io.trino.plugin.hive.HiveQueryRunner.copyTpchTablesBucketed(HiveQueryRunner.java:339)
	at io.trino.plugin.hive.HiveQueryRunner$Builder.populateData(HiveQueryRunner.java:279)
	at io.trino.plugin.hive.HiveQueryRunner$Builder.build(HiveQueryRunner.java:258)
	at io.trino.plugin.hive.s3.S3HiveQueryRunner$Builder.build(S3HiveQueryRunner.java:150)
	at io.trino.faulttolerant.hive.TestHiveTaskFailureRecoveryTest.createQueryRunner(TestHiveTaskFailureRecoveryTest.java:71)
	at io.trino.faulttolerant.BaseFailureRecoveryTest.createQueryRunner(BaseFailureRecoveryTest.java:107)
	at io.trino.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:95)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: SQL: CREATE TABLE orders WITH (bucketed_by=array['custkey'], bucket_count=11) AS SELECT * FROM tpch.tiny.orders
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:483)
		... 21 more
```

**Comment by findepi** [comment] 2022-09-07 14:54
@linzebing @arhimondr @losipiuk is it a duplicate of any other existing issue?
I couldn't find any, but you may know better

**Comment by ebyhr** [comment] 2022-09-07 21:25
https://github.com/trinodb/trino/runs/8229808681

**Comment by ebyhr** [comment] 2022-09-08 07:51
https://github.com/trinodb/trino/runs/8243366011

**Comment by findepi** [comment] 2022-09-23 14:27
https://github.com/trinodb/trino/actions/runs/3112718741/jobs/5046822323

```
Error:  Tests run: 933, Failures: 1, Errors: 0, Skipped: 932, Time elapsed: 166.37 s <<< FAILURE! - in TestSuite
Error:  io.trino.faulttolerant.hive.TestHiveFaultTolerantExecutionJoinQueries.init  Time elapsed: 127.453 s  <<< FAILURE!
java.lang.RuntimeException: 
Error fetching next at http://127.0.0.1:34337/v1/statement/executing/20220923_133957_00006_2wfp6/y4ae55a208cec9acab0a48c9398e5aa65873d5273/1 returned an invalid response: JsonResponse{statusCode=500, statusMessage=Internal Server Error, headers={content-length=[1016], content-type=[text/plain], date=[Fri, 23 Sep 2022 13:39:58 GMT]}, hasValue=false} [Error: java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.common.util.concurrent.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1543)
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:586)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:547)
	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:91)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:240)
	at com.google.common.util.concurrent.Futures.getDone(Futures.java:1181)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1130)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
]
	at io.trino.client.StatementClientV1.requestFailedException(StatementClientV1.java:453)
	at io.trino.client.StatementClientV1.advance(StatementClientV1.java:392)
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:99)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:480)
	at io.trino.testing.QueryAssertions.copyTable(QueryAssertions.java:339)
	at io.trino.testing.QueryAssertions.copyTable(QueryAssertions.java:331)
	at io.trino.testing.QueryAssertions.copyTpchTables(QueryAssertions.java:323)
	at io.trino.plugin.hive.HiveQueryRunner$Builder.populateData(HiveQueryRunner.java:273)
	at io.trino.plugin.hive.HiveQueryRunner$Builder.build(HiveQueryRunner.java:258)
	at io.trino.faulttolerant.hive.TestHiveFaultTolerantExecutionJoinQueries.createQueryRunner(TestHiveFaultTolerantExecutionJoinQueries.java:53)
	at io.trino.testing.AbstractTestFaultTolerantExecutionJoinQueries.createQueryRunner(AbstractTestFaultTolerantExecutionJoinQueries.java:25)
	at io.trino.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:95)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: SQL: CREATE TABLE IF NOT EXISTS lineitem AS SELECT * FROM tpch.tiny.lineitem
		at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:483)
		... 21 more
```

**Comment by linzebing** [comment] 2022-09-23 17:24
I'm assuming https://github.com/trinodb/trino/issues/13946 is the same issue with this one. I will try to take a look.

**Comment by arhimondr** [comment] 2022-09-26 20:23
Closing as a duplicate of https://github.com/trinodb/trino/issues/13946

**Closed by arhimondr** 2022-09-26 20:23 UTC
Labels: bug, test
