### ISSUE TITLE
Nested null values inside columns with row type cause java.lang.IllegalArgumentException: ColumnarRow field size X is not equal to columnWriters size Y

### ISSUE THREAD

**Issue by davseitsev** [trinodb/trino#9264] opened 2021-09-16 14:45 UTC
The issue happens here 
https://github.com/trinodb/trino/blob/aeb753aed2f04d6a6d520edb5645f03bb24e1721/lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java#L331 
where null blocks are initiated with default value. 
`field.getType()` is used as a default type for each block. In fact this is a type of parent field. We should use something like `field.getType().getTypeParameters().get(i)`

It causes following exception when Presto tries to write these pages to parquet file:
```
java.lang.IllegalArgumentException: ColumnarRow field size 6 is not equal to columnWriters size 3
	at org.apache.parquet.Preconditions.checkArgument(Preconditions.java:73)
	at io.trino.parquet.writer.StructColumnWriter.writeBlock(StructColumnWriter.java:51)
	at io.trino.parquet.writer.StructColumnWriter.writeBlock(StructColumnWriter.java:65)
```

Trino version 364

**Comment by findepi** [comment] 2021-09-16 14:54
cc @alexjo2144 @losipiuk @joshthoward

**Comment by losipiuk** [comment] 2021-11-05 09:56
I see that you observed issue on non-vanilla Trino:
```
	at com.wixpress.presto.parquet.ParquetPageSink.writePage(ParquetPageSink.java:194)
	at com.wixpress.presto.parquet.ParquetPageSink.doAppend(ParquetPageSink.java:148)
	at com.wixpress.presto.parquet.ParquetPageSink.appendPage(ParquetPageSink.java:345)
```

Also `io.prestosql` packages suggest you are using a very old version of Trino.

Please confirm the issue is still present on a recent vanilla release of Trino, and reopen issue if necessary.

**Comment by davseitsev** [comment] 2021-11-05 10:06
@losipiuk  I don't really understand why you are closing the issue. What's the difference which version of Presto/Trino do I use if I specified a link to the latest version with class name line of code with the issue. Could you explain please?

**Comment by davseitsev** [comment] 2021-11-05 10:24
Edited and removed confusing stack trace.

**Comment by findepi** [comment] 2021-11-08 09:23
> Edited and removed confusing stack trace.

Thanks!

Can you please provide repro steps, if you have them, and the full stacktrace?

**Comment by davseitsev** [comment] 2021-11-08 09:59
Yes I do have full stack trace, but please do not close the issue again because of old (346) non-vanilla Trino version.

```
java.lang.IllegalArgumentException: ColumnarRow field size 6 is not equal to columnWriters size 3
	at org.apache.parquet.Preconditions.checkArgument(Preconditions.java:73)
	at io.prestosql.parquet.writer.StructColumnWriter.writeBlock(StructColumnWriter.java:51)
	at io.prestosql.parquet.writer.StructColumnWriter.writeBlock(StructColumnWriter.java:65)
	at io.prestosql.parquet.writer.StructColumnWriter.writeBlock(StructColumnWriter.java:65)
	at io.prestosql.parquet.writer.ArrayColumnWriter.writeBlock(ArrayColumnWriter.java:50)
	at io.prestosql.parquet.writer.ParquetWriter.writeChunk(ParquetWriter.java:164)
	at io.prestosql.parquet.writer.ParquetWriter.write(ParquetWriter.java:154)
	at io.prestosql.plugin.hive.parquet.ParquetFileWriter.appendRows(ParquetFileWriter.java:110)
	at com.wixpress.bi.presto.parquet.worker.ParquetNewPageSink.writePage(ParquetNewPageSink.java:194)
	at com.wixpress.bi.presto.parquet.worker.ParquetNewPageSink.doAppend(ParquetNewPageSink.java:148)
	at com.wixpress.bi.presto.parquet.worker.ParquetNewPageSink.appendPage(ParquetNewPageSink.java:345)
	at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.appendPage(ClassLoaderSafeConnectorPageSink.java:69)
	at io.prestosql.operator.TableWriterOperator.addInput(TableWriterOperator.java:257)
	at io.prestosql.operator.Driver.processInternal(Driver.java:384)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_346____20210830_093110_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

The issue is still present in master branch. You can make sure about this if you look closer at following block of code:
https://github.com/trinodb/trino/blob/aeb753aed2f04d6a6d520edb5645f03bb24e1721/lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java#L329-L333
Here we iterate over struct fields and initiate `null` ones with default value. As you can see we initiate all null fields of a struct with the same type: `field.getType()`, which is actually type of parent field.
We should initiate each field with its own type: `field.getType().getTypeParameters().get(i)`.

I don't have usable steps to reproduce the issue, it happened on production data. 
We had a table with complex type field like this:
```
{
  optional group variants (LIST) {
    repeated group list {
      optional group element {
        optional binary id_ (STRING);
        optional group choices (MAP) {
          repeated group map {
            optional binary key (STRING);
            optional binary value (STRING);
          }
        }
        optional group variant {
          optional double wght;
          optional binary skx (STRING);
          optional boolean visible;
          optional group pcData {
            optional double dstdPrice;
            optional double p;
            optional group formatted {
              optional binary p (STRING);
              optional binary dstdPrice (STRING);
              optional binary prPerUnit (STRING);
            }
            optional double prPerUnit;
            optional binary name (STRING);
          }
          optional group convertedPcData {
            optional double dstdPrice;
            optional double p;
            optional group formatted {
              optional binary p (STRING);
              optional binary dstdPrice (STRING);
              optional binary prPerUnit (STRING);
            }
            optional double prPerUnit;
            optional binary name (STRING);
          }
          optional group capData {
            optional double item;
            optional double pf;
            optional double pfMargin;
          }
        }
      }
    }
  }
}
```
and CTAS queries failed when there were a lot of null values in `formatted` field.

**Comment by findepi** [comment] 2021-11-08 12:20
@davseitsev i sounds like you know how to fix the issue, feel free to just raise a PR.
however, I do not.  The stacktrace you pasted still shows `com.wixpress.bi.presto.parquet.worker.ParquetNewPageSink` on the stack. I don't have access to this class and I don't know what it is doing. Even if you shared this class with me, there is probably no point in me trying to understand what it does...

in any case, the action seems to be on your side: you can either fix the problem, or provide repro steps that are applicable to vanilla Trino (or Presto). Either way, the issue is not actionable for anyone else, so it's seems there is no point in currently keeping it open. Therefore closing until any of the above.

**Comment by davseitsev** [comment] 2021-11-08 14:11
Fresh stack trace from Trino 363
```
java.lang.IllegalArgumentException: ColumnarRow field size 6 is not equal to columnWriters size 3
	at org.apache.parquet.Preconditions.checkArgument(Preconditions.java:77)
	at io.trino.parquet.writer.StructColumnWriter.writeBlock(StructColumnWriter.java:51)
	at io.trino.parquet.writer.StructColumnWriter.writeBlock(StructColumnWriter.java:65)
	at io.trino.parquet.writer.StructColumnWriter.writeBlock(StructColumnWriter.java:65)
	at io.trino.parquet.writer.ArrayColumnWriter.writeBlock(ArrayColumnWriter.java:50)
	at io.trino.parquet.writer.ParquetWriter.writeChunk(ParquetWriter.java:158)
	at io.trino.parquet.writer.ParquetWriter.write(ParquetWriter.java:148)
	at io.trino.plugin.hive.parquet.ParquetFileWriter.appendRows(ParquetFileWriter.java:113)
	at io.trino.plugin.iceberg.IcebergPageSink.writePage(IcebergPageSink.java:265)
	at io.trino.plugin.iceberg.IcebergPageSink.doAppend(IcebergPageSink.java:218)
	at io.trino.plugin.iceberg.IcebergPageSink.lambda$appendPage$0(IcebergPageSink.java:156)
	at io.trino.plugin.hive.authentication.HdfsAuthentication.lambda$doAs$0(HdfsAuthentication.java:26)
	at io.trino.plugin.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:25)
	at io.trino.plugin.hive.authentication.HdfsAuthentication.doAs(HdfsAuthentication.java:25)
	at io.trino.plugin.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:103)
	at io.trino.plugin.iceberg.IcebergPageSink.appendPage(IcebergPageSink.java:156)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.appendPage(ClassLoaderSafeConnectorPageSink.java:69)
	at io.trino.operator.TableWriterOperator.addInput(TableWriterOperator.java:263)
	at io.trino.operator.Driver.processInternal(Driver.java:393)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:292)
	at io.trino.operator.Driver.tryWithLock(Driver.java:685)
	at io.trino.operator.Driver.processFor(Driver.java:285)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_363____20211108_134233_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by joshthoward** [comment] 2021-11-09 22:15
@davseitsev Can you please share reproduction steps? 

I have tried
```
trino> CREATE TABLE hive.temp_schema.temp_nested_row_table (a_row ROW(x INTEGER, y ROW(z INTEGER, w REAL))) WITH (format='parquet');
// A couple of inserts like 
trino> INSERT INTO hive.temp_schema.temp_nested_row_table VALUES ROW(CAST(ROW(NULL, ROW(NULL, 2e0)) AS ROW(x INTEGER, y ROW(INTEGER, REAL))));
trino> SELECT * FROM hive.temp_schema.temp_nested_row_table;
            a_row
-----------------------------
 {x=1, y={z=1, w=2.0}}
 {x=1, y={z=NULL, w=NULL}}
 {x=NULL, y={z=NULL, w=2.0}}
```
and it seems to be working.

**Comment by davseitsev** [comment] 2021-11-10 08:17
I managed to reproduce it in following way:

**On Trino**
```sql
DROP TABLE IF EXISTS iceberg.test.struct_sample;

CREATE TABLE iceberg.test.struct_sample AS
SELECT CAST(
    ROW(1, ROW(2, 3)) AS
    ROW(foo BIGINT, a_sub_struct ROW(x BIGINT, y BIGINT))
) AS a_struct;
```

**On Spark**
```sql
ALTER TABLE iceberg.test.struct_sample ADD COLUMN a_struct.a_sub_struct_2 STRUCT<z: BIGINT>
```

**On Trino**
```sql
INSERT INTO iceberg.test.struct_sample
SELECT CAST(
    ROW(1, ROW(2, 3), ROW(4)) AS
    ROW(foo BIGINT,
        a_sub_struct ROW(x BIGINT, y BIGINT),
        a_sub_struct_2 ROW(z BIGINT)
    )
) AS a_struct;
```

And following query fails **on Trino** with message: `ColumnarRow field size 3 is not equal to columnWriters size 1`
```sql
DROP TABLE IF EXISTS iceberg.test.struct_sample_copy;
CREATE TABLE iceberg.test.struct_sample_copy AS SELECT * FROM iceberg.test.struct_sample;
```

There might be another ways to reproduce it but this is what I came up with while analyzing problematic line of code.

**Comment by losipiuk** [comment] 2021-11-10 12:37
Thanks for the repro steps @davseitsev  ❤️

**Closed** 2021-11-22 10:39 UTC
Labels: bug
