### ISSUE TITLE
"Query not registered" failure on simple queries

### ISSUE THREAD

**Issue by Pluies** [trinodb/trino#20698] opened 2024-02-14 09:01 UTC
Hi there,

We've been running into intermittent issues where very simple queries fail with the following stacktrace:
```
java.lang.IllegalStateException: Query not registered: 20240213_115355_04372_n4eke
	at io.trino.metadata.LanguageFunctionManager.getQueryFunctions(LanguageFunctionManager.java:138)
	at io.trino.metadata.LanguageFunctionManager.serializeFunctionsForWorkers(LanguageFunctionManager.java:185)
	at io.trino.sql.planner.PlanFragmenter.createSubPlans(PlanFragmenter.java:127)
	at io.trino.execution.SqlQueryExecution.doPlanQuery(SqlQueryExecution.java:492)
	at io.trino.execution.SqlQueryExecution.planQuery(SqlQueryExecution.java:466)
	at io.trino.execution.SqlQueryExecution.start(SqlQueryExecution.java:404)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:264)
	at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:145)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(LocalDispatchQuery.java:129)
	at io.airlift.concurrent.MoreFutures.lambda$addSuccessCallback$12(MoreFutures.java:568)
	at io.airlift.concurrent.MoreFutures$3.onSuccess(MoreFutures.java:543)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1133)
	at io.trino.$gen.Trino_435_264_g74ecdf0____20240212_132618_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

![image](https://github.com/trinodb/trino/assets/344835/dab053a4-37ed-411d-bed0-355f35970ab4)

We're on Trino 436, and haven't noticed this issue up to Trino 434 (but we may just have missed it!).

The issue happens maybe 1 time out of 100.

cc @theedgeofrage

**Comment by TheEdgeOfRage** [comment] 2024-02-14 11:17
Hey folks, I'm the one who encountered the issue. Just to add some more detail, I'm running this query and cancelling it immediately using a DELETE call on the next URI endpoint. This is done to test our own system to see how it behaves during query cancellation, but occasionally this error creeps in and instead of a USER_CANCELLED I get the GENERIC_INTERNAL_ERROR

**Comment by wendigo** [comment] 2024-02-14 18:39
@findepi

**Comment by dain** [comment] 2024-02-14 22:15
I bet the problem is in `QueryStateMachine.transitionToFailed`.   The first call in that method is cleanupQueryQuietly, which calls `Metadata.cleanupQuery`, which unregisters the query with the language funciton manager.  A few calls down in `transitionToFailed` the throwable is recorded and the state is set.

I think the solution is to move the code that sets `failureCause` to be before we call cleanup.  Once written the `failureCause` can't be overwritten, so it doesn't matter of the exception in this issue happens after that.  Additionally, `failureCause` is not exposed until the state becomes `FAILED` so this _should_ be safe.

**Comment by findepi** [comment] 2024-02-15 10:20
@Pluies the stacktrace is the same as in https://github.com/trinodb/trino/issues/20551, so let me close this issue

@dain  thanks for rewriting https://github.com/trinodb/trino/issues/20551#issuecomment-1926584350 in a better English. 
the solution has been applied https://github.com/trinodb/trino/pull/20582

**Closed by findepi** 2024-02-15 10:20 UTC

**Comment by Pluies** [comment] 2024-02-15 10:23
Awesome, thank you very much! 🥳
