### ISSUE TITLE
[Pinot connector] Some pass-through queries give incorrect result or are failing

### ISSUE THREAD

**Issue by jpohanka** [trinodb/trino#9137] opened 2021-09-07 09:08 UTC
**Trino version**: 361

**Description**:

Lets assume that we have a Pinot table `tab` and in this table, we have the following columns:

- `col_int` - an integer dimensional column
- `col_str1` - a string dimensional column
- `col_str2` - another string dimensional column
- `quant1` - a double column for some quantity
- `quant2` - a double column for another quantity

Lets assume that:

- for the value `SOME_STRING_VALUE` for column `col_str1` there are records in the table `tab`
- for the value `another_string_value` for column `col_str2` there are records in the table `tab`
- for the value `int_value_1` for column `col_int` there are records in the table `tab`.

The following are examples of queries returning either incorrect results or failing:

---
### Case 1a

The following pass-through query returns `NULL` value as the result:

```
SELECT * FROM pinot.default."
  SELECT COUNT(*)
  FROM tab
  WHERE col_str1 = 'SOME_STRING_VALUE'
";
```

When reading the logical query plan in Trino, the string value `SOME_STRING_VALUE` in the `WHERE` clause gets lowercased, hence the Pinot connector in Trino receives the value `some_string_value`.

In Pinot, this query works as expected.

---
### Case 1b

The following pass-through query returns the correct result:

```
SELECT * FROM pinot.default."
  SELECT COUNT(*)
  FROM tab
  WHERE col_str2 = 'another_string_value'
";
```

Since the value `another_string_value` is all lowercase, it filters the correct set of records, and returns the correct result.

We also get the correct result when using integer values in the `WHERE` clause.

```
SELECT * FROM pinot.default."
  SELECT COUNT(*)
  FROM tab
  WHERE col_int = int_value_1
";
```

In Pinot, both queries work as expected.

---
### Case 2

The following pass-through query fails with the message that the DISTINCT operation is not supported:

```
SELECT * FROM pinot.default."
  SELECT DISTINCT col_str1
  FROM
    tab
  WHERE
    col_int = int_value_1
  LIMIT 10
";
```

In Pinot, this query works as expected.

---
### Case 3

The following pass-though query fails:

```
SELECT * FROM pinot.default."
  SELECT col_str1,
         SUM(CASE WHEN col_int = int_value_1 THEN quant1 ELSE 0 END)  AS sum_quant1
  FROM olap_benu
  GROUP BY col_str1
  ORDER BY col_str1
";
```

In Pinot, this query works as expected. Once the `CASE` clause is removed, it works.

---
### Case 4

The following pass-though query fails:

```
SELECT * FROM pinot.default."
  SELECT col_str1,
         SUM(quant1)  AS sum_quant1,
         COUNT(DISTINCT col_str2) AS cnt_str2,
         (SUM(sum_quant2) - SUM(sum_quant1)) / SUM(sum_quant1) AS ratio_quant1
  FROM tab
  WHERE col_int = int_value_1
  GROUP BY col_str1
  ORDER BY col_str1
";
```

In Pinot, this query works as expected. Once the ratio of sums is removed, it works.

**Comment by findepi** [comment] 2021-09-07 09:23
cc @elonazoulay

**Comment by jpohanka** [comment] 2021-09-12 22:02
@elonazoulay  For the Case 1 with the string value - I have noticed from the logical plan, that the string value is lowercased (I use in my tests uppercase values).

**Comment by hashhar** [comment] 2021-09-13 04:25
> @elonazoulay For the Case 1 with the string value - I have noticed from the logical plan, that the string value is lowercased (I use in my tests uppercase values).

That is sadly expected at this point. It seems the root of the issue is https://github.com/trinodb/trino/issues/17.
The fact that we misuse the table name for passing entire queries means that everything within the table name will be lowercased - including predicates.

This is one of the reasons why the only other connector that supports passthrough queries is Elasticsearch which requires the table name to be `base32` encoded to prevent any case translation that might happen.

**Comment by jpohanka** [comment] 2021-09-13 11:12
@hashhar Description updated.

**Comment by elonazoulay** [comment] 2021-10-21 04:52
@jpohanka - you can use `upper(constant)` in the passthrough query for the first one:
```
SELECT * FROM pinot.default."
  SELECT COUNT(*)
  FROM tab
  WHERE col_str1 = upper('SOME_STRING_VALUE')
";
```

**Comment by hashhar** [comment] 2022-03-19 20:45
@elonazoulay Since https://github.com/trinodb/trino/pull/9781 is merged, are there any cases in this bug report which are still unhandled? It seems to me all are addressed?

Can you confirm once?

**Comment by elonazoulay** [comment] 2022-03-20 18:50
This does seem to cover all the use cases, even added specific unit tests for these issues. Thanks!

**Closed** 2022-03-20 19:23 UTC
Labels: bug, correctness
