### ISSUE TITLE
Trino Delta connector is unable to read ABFS paths with spaces

### ISSUE THREAD

**Issue by georgewfisher** [trinodb/trino#17643] opened 2023-05-25 18:53 UTC
## **Summary**

If trying to read a Delta table in Trino with a space in a path, the query fails.
The breaking change was this, which added an extra decoding step to abfs paths: https://github.com/trinodb/trino/pull/15381

*Next steps*: understand motivations behind decoding added here https://github.com/trinodb/trino/pull/15381 and fix.

## **Repro Steps**

This is the example that alerted me to the issue:
```sql
create table delta.test.timestamp_part with (partitioned_by = ARRAY[ 'ts' ]) as 
select *, CAST(CAST(current_timestamp AS timestamp(0)) as varchar) as ts 
from tpch.tiny.customer;
```

This creates partitions that look like this:

![image](https://github.com/trinodb/trino/assets/4565745/3cabfb7a-4140-4574-bdc3-1bb9d6f09dcf)

Then:
```sql
select * from delta.test.timestamp_part;
```

Will result in the error:
```
io.trino.spi.TrinoException: HEAD https://XXX.dfs.core.windows.net/XXX/test.db/timestamp_part-f5b65654a59d4b76898d9ca6ac70d295/ts%3D2023-05-25%2009%3A53%3A14/20230525_165313_00000_r3yme-1069470b-4ce6-4574-a8dd-1334c4bcf2a0?timeout=90
StatusCode=404
StatusDescription=The specified path does not exist.
```

Looking at the partition you can see the path now has `ts%3D2023-05-25%2009%3A53%3A14` - the space has been turned into a `%20`

Why? Because:

1. In DeltaLakeSplitManager [here](https://github.com/trinodb/trino/blob/4b17fcf6dc7ff5d540219f59c958d0c350ea34c9/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java#LL342C13-L342C71) (`String path = uri.getPath();`), the input from Delta metadata is:
`ts=2023-05-24%2015%253A02%253A18/20230524_220217_00377_4irfv-6bf24895-2c9e-4765-926d-e0349c3d4d5a`

2. Then, if the path is an abfs path, we get a URLDecoder.decode and then see:
`ts=2023-05-24 15%3A02%3A18/20230524_220217_00377_4irfv-6bf24895-2c9e-4765-926d-e0349c3d4d5a`

All good, but then:

3. In DeltaLakePageSourceProvider split.getPath() [here](https://github.com/trinodb/trino/blob/d4fc17f3b4585315f0d800f989574a711f93dac1/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSourceProvider.java#L154), we see:
`ts=2023-05-24 15:02:18/20230524_220217_00377_4irfv-6bf24895-2c9e-4765-926d-e0349c3d4d5a`
The path has been double decoded. Now, when encoded, this will result in the incorrect path.

**Comment by georgewfisher** [comment] 2023-05-25 18:58
Found this is duplicate:
Other issue here: https://github.com/trinodb/trino/issues/17012

**Comment by ebyhr** [comment] 2023-05-25 22:15
Closing as duplicate of #17012

**Closed by ebyhr** 2023-05-25 22:15 UTC
