### ISSUE TITLE
No bucket node map for partitioning

### ISSUE THREAD

**Issue by wobrycki** [trinodb/trino#13960] opened 2022-09-01 15:18 UTC
Trino: 393
Last known Trino version when it was working: 387, 392
Steps to reproduce: Create an iceberg table with partitioning and a bucketing:
```
CREATE TABLE IF NOT EXISTS
     try3_lineitems (
       line_item_id VARCHAR
    )
  WITH ( format = 'PARQUET', partitioning = ARRAY['bucket(line_item_id, 10)'] );
```
Insert anything in the table:
`INSERT INTO "try3_lineitems" (line_item_id) values 'abc';`
Gives:
```
INSERT INTO "try3_lineitems" (line_item_id) values 'abc';

Query 20220901_151104_00062_vijnn, FAILED, 1 node
https://trino:8081/ui/query.html?20220901_151104_00062_vijnn
Splits: 14 total, 2 done (14.29%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 100% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.0
Peak Memory: 115B
0.12 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20220901_151104_00062_vijnn failed: No bucket node map for partitioning: iceberg:IcebergPartitioningHandle{partitioning=[bucket(line_item_id, 1)]}
com.google.common.base.VerifyException: No bucket node map for partitioning: iceberg:IcebergPartitioningHandle{partitioning=[bucket(line_item_id, 1)]}
	at io.trino.operator.exchange.LocalExchange.lambda$createPartitionFunction$8(LocalExchange.java:220)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.trino.operator.exchange.LocalExchange.createPartitionFunction(LocalExchange.java:220)
	at io.trino.operator.exchange.LocalExchange.lambda$new$7(LocalExchange.java:130)
	at io.trino.operator.exchange.LocalExchange.createSink(LocalExchange.java:274)
	at io.trino.operator.exchange.LocalExchange$LocalExchangeSinkFactory.createSink(LocalExchange.java:374)
	at io.trino.operator.exchange.LocalExchangeSinkOperator$LocalExchangeSinkOperatorFactory.createOperator(LocalExchangeSinkOperator.java:57)
	at io.trino.operator.DriverFactory.createDriver(DriverFactory.java:98)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunnerFactory.createDriver(SqlTaskExecution.java:620)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:731)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:164)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:490)
	at io.trino.$gen.Trino_393____20220901_124425_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

The last change I found in the trino repo regarding this error message is on 03.08.2022 Revision 3207925.

**Comment by ebyhr** [comment] 2022-09-02 05:53
@wobrycki I can't reproduce the issue. Could you share config files and the number of workers?

**Comment by wobrycki** [comment] 2022-09-02 07:21
Hi @ebyhr here are the configs:

```
connector.name=iceberg
hive.metastore.uri=__HIVE_METASTORE_URI__
hive.s3.max-connections=500
hive.s3.ssl.enabled=__HIVE_S3_SSL__
hive.s3.endpoint=__HIVE_S3_ENDPOINT__
hive.s3.path-style-access=true
iceberg.file-format=PARQUET
iceberg.compression-codec=ZSTD
iceberg.format-version=1
iceberg.allow-legacy-snapshot-syntax=true
iceberg.unique-table-location=false
```

Where do I find the number of workers?

**Comment by ebyhr** [comment] 2022-09-02 07:24
You can confirm the number in webui.

**Comment by wobrycki** [comment] 2022-09-02 07:43
Thanks. There is 1 active worker.

**Comment by wobrycki** [comment] 2022-09-02 09:41
config.properties:
```
__COORDINATOR_SECTION__
http-server.http.port=8080
node-scheduler.max-splits-per-node=100
query.max-memory=200GB
query.max-memory-per-node=8GB
query.max-stage-count=50
query.max-run-time=24h
task.writer-count=4
discovery.uri=http://trino:8080
internal-communication.shared-secret=SOME_SECRET
```

**Comment by wobrycki** [comment] 2022-09-02 09:47
__COORDINATOR_SECTION__ can be replaced with:
```
coordinator=true
node-scheduler.include-coordinator=__TRINO_NODE_SCHEDULER_INCLUDE_COORDINATOR__
http-server.https.enabled=true
http-server.authentication.type=PASSWORD
http-server.https.port=8081
http-server.https.keystore.path=/trino_keystore.jks
http-server.https.keystore.key=\${ENV:TRINO_KEYSTORE_PASSWORD}
```

**Comment by ebyhr** [comment] 2022-09-06 03:11
Thanks, I can reproduce on 394. Looking into the detail now.

**Comment by findepi** [comment] 2022-09-06 10:41
cc @electrum @djsstarburst

**Comment by findepi** [comment] 2022-09-08 10:21
Reassigning per https://github.com/trinodb/trino/pull/14003#discussion_r965583742

**Closed** 2022-09-09 15:47 UTC
Labels: bug
