### ISSUE TITLE
Inserts on Delta Table Failing when partitioned column is of type `timestamp(3) with time zone`

### ISSUE THREAD

**Issue by vinay-kl** [trinodb/trino#18262] opened 2023-07-12 19:52 UTC
Currently, creating a delta table partitioned on type `timestamp(3) with time zone` is allowed, but inserts fail with the following error.

Reproduction Steps
```
trino> create table delta_prod.dev_30.timestamp_timezone_partition (a int, b timestamp(3) with time zone) WITH (partitioned_by = ARRAY['b']);
CREATE TABLE
trino> 
trino> 
trino> insert into delta_prod.dev_30.timestamp_timezone_partition values (1, now());

Query 20230712_130315_00042_dyrnw, FAILED, 4 nodes
https://bifrostx-test-new.myntra.com/ui/query.html?20230712_130315_00042_dyrnw
Splits: 114 total, 58 done (50.88%)
CPU Time: 0.0s total,     0 rows/s,     0B/s, 75% active
Per Node: 0.0 parallelism,     0 rows/s,     0B/s
Parallelism: 0.1
Peak Memory: 5.64KB
0.33 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20230712_130315_00042_dyrnw failed: unsupported type: timestamp(3) with time zone
io.trino.spi.TrinoException: unsupported type: timestamp(3) with time zone
	at io.trino.plugin.hive.util.HiveWriteUtils.getField(HiveWriteUtils.java:375)
	at io.trino.plugin.hive.util.HiveWriteUtils.createPartitionValues(HiveWriteUtils.java:278)
	at io.trino.plugin.deltalake.AbstractDeltaLakePageSink.createPartitionValues(AbstractDeltaLakePageSink.java:439)
	at io.trino.plugin.deltalake.AbstractDeltaLakePageSink.getWriterIndexes(AbstractDeltaLakePageSink.java:356)
	at io.trino.plugin.deltalake.AbstractDeltaLakePageSink.writePage(AbstractDeltaLakePageSink.java:281)
	at io.trino.plugin.deltalake.AbstractDeltaLakePageSink.appendPage(AbstractDeltaLakePageSink.java:273)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.appendPage(ClassLoaderSafeConnectorPageSink.java:68)
	at io.trino.operator.TableWriterOperator.addInput(TableWriterOperator.java:255)
	at io.trino.operator.Driver.processInternal(Driver.java:407)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:305)
	at io.trino.operator.Driver.tryWithLock(Driver.java:701)
	at io.trino.operator.Driver.process(Driver.java:297)
	at io.trino.operator.Driver.processForDuration(Driver.java:268)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:888)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:556)
	at io.trino.$gen.Trino_419____20230711_105333_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by findepi** [comment] 2023-07-12 20:00
cc @ebyhr @findinpath

**Comment by ebyhr** [comment] 2023-07-12 22:49
Closing as duplicate of #16822

**Closed by ebyhr** 2023-07-12 22:49 UTC
Labels: bug
