### ISSUE TITLE
Trino reading schemas of csv files datatypes wrong (all varchar)

### ISSUE THREAD

**Issue by amirsh-mb** [trinodb/trino#18437] opened 2023-07-27 10:05 UTC
i got a schema stored on glue of csv files that looks like this:

```
CREATE EXTERNAL TABLE `csv_table`(
  `username` string COMMENT 'from deserializer', 
  `password` string COMMENT 'from deserializer',
  `age` int COMMENT ''
)
PARTITIONED BY ( 
  `year` int, 
  `month` int, 
  `day` int)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
WITH SERDEPROPERTIES ( 
  'separatorChar'=',') 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.mapred.TextInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'
LOCATION
  's3://bucket/table'
TBLPROPERTIES (
  'classification'='csv', 
  'skip.header.line.count'='1')
```

The tables reads everything fine except the columns datatypes, it reads all he columns as varchar.
This happens in all tables with csv format, and doesn't happened on tables with parquet format

Trino version: 422

**Comment by ebyhr** [comment] 2023-07-28 07:58
Closing as duplicate of #8940

**Closed by ebyhr** 2023-07-28 07:58 UTC
