### ISSUE TITLE
Slow system.jdbc* query for BigQuery

### ISSUE THREAD

**Issue by yunrougong** [trinodb/trino#4580] opened 2020-07-25 18:58 UTC
When BigQuery connector is enabled, the system.jdbc.* queries (mostly issued by SQL client like DBeaver), take minutes to run. 

```
SELECT TABLE_CAT, TABLE_SCHEM, TABLE_NAME, TABLE_TYPE, REMARKS,
  TYPE_CAT, TYPE_SCHEM, TYPE_NAME,   SELF_REFERENCING_COL_NAME, REF_GENERATION
FROM system.jdbc.tables
WHERE TABLE_NAME LIKE 'prospects' ESCAPE '\'
ORDER BY TABLE_TYPE, TABLE_CAT, TABLE_SCHEM, TABLE_NAME
```
The full thread is here
https://prestosql.slack.com/archives/CGB0QHWSW/p1595525453380400

**Comment by ebyhr** [comment] 2020-07-26 07:09
Could you share the following information?
* Table numbers in BigQuery
* Debug log for `io.prestosql.plugin.bigquery`

**Comment by ebyhr** [comment] 2022-01-21 07:13
Thanks for our report. I confirmed the metadata access in BigQuery connector is slow comparing to other connectors when there're many objects.

**Comment by ebyhr** [comment] 2023-06-13 15:07
Closing as duplicate of #10741

**Closed by ebyhr** 2023-06-13 15:07 UTC
