### ISSUE TITLE
TestS3WrongRegionPicked is flaky

### ISSUE THREAD

**Issue by homar** [trinodb/trino#14631] opened 2022-10-14 07:40 UTC
```
Error:  io.trino.plugin.hive.s3.TestS3WrongRegionPicked.testS3WrongRegionSelection  Time elapsed: 4.926 s  <<< FAILURE!
java.lang.AssertionError: 

Expecting throwable message:
  <"Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)), SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey), WebIdentityTokenCredentialsProvider: You must specify a value for roleArn and roleSessionName, com.amazonaws.auth.profile.ProfileCredentialsProvider@42d4401d: profile file cannot be null, com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@28fac5b2: The requested metadata is not found at http://169.254.169.254/latest/meta-data/iam/security-credentials/]">
to contain:
  <"Status Code: 400">
but did not.

Throwable that failed the check:

com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)), SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey), WebIdentityTokenCredentialsProvider: You must specify a value for roleArn and roleSessionName, com.amazonaws.auth.profile.ProfileCredentialsProvider@42d4401d: profile file cannot be null, com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@28fac5b2: The requested metadata is not found at http://169.254.169.254/latest/meta-data/iam/security-credentials/]
	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:136)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1266)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:842)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:792)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:753)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:713)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:695)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:559)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:539)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5453)
```

**Comment by ebyhr** [comment] 2022-10-14 07:41
Let me close as duplicate of #14568

**Closed by ebyhr** 2022-10-14 07:41 UTC
