### ISSUE TITLE
Support Iceberg REST Catalog OAuth2 endpoint

### ISSUE THREAD

**Issue by nqvuong1998** [trinodb/trino#24138] opened 2024-11-15 07:30 UTC
Trino lacks functionality to configure the [oauth2 endpoint](https://projectnessie.org/nessie-latest/trino/#oauth2-support) and is therefore unable to work with any Iceberg REST catalog implementation and demands a standard OAuth2 server like Keycloak or ADFS.

**Comment by ebyhr** [comment] 2024-11-15 07:33
Duplicate of #23086

**Closed by ebyhr** 2024-11-15 07:33 UTC
