### ISSUE TITLE
Flaky test TestRaptorMySqlConnectorTest `No catalog 'raptor'`

### ISSUE THREAD

**Issue by findinpath** [trinodb/trino#21377] opened 2024-04-03 18:48 UTC
https://github.com/trinodb/trino/actions/runs/8539890770/job/23395730413?pr=18521

```
io.trino.testing.QueryFailedException: No catalog 'raptor'
	at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:133)
	at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:501)
	at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:484)
	at io.trino.testing.QueryAssertions.copyTable(QueryAssertions.java:517)
	at io.trino.testing.QueryAssertions.copyTable(QueryAssertions.java:510)
	at io.trino.testing.QueryAssertions.copyTpchTables(QueryAssertions.java:503)
	at io.trino.plugin.raptor.legacy.RaptorQueryRunner.copyTables(RaptorQueryRunner.java:90)
	at io.trino.plugin.raptor.legacy.TestRaptorMySqlConnectorTest.createRaptorMySqlQueryRunner(TestRaptorMySqlConnectorTest.java:80)
	at io.trino.plugin.raptor.legacy.TestRaptorMySqlConnectorTest.createQueryRunner(TestRaptorMySqlConnectorTest.java:41)
	at io.trino.testing.AbstractTestQueryFramework.init(AbstractTestQueryFramework.java:113)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
	Suppressed: java.lang.Exception: SQL: CREATE TABLE IF NOT EXISTS nation AS SELECT * FROM tpch.tiny.nation
		at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:508)
		... 15 more
Caused by: java.lang.IllegalArgumentException: No catalog 'raptor'
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220)
	at io.trino.connector.WorkerDynamicCatalogManager.getConnectorServices(WorkerDynamicCatalogManager.java:209)
	at io.trino.connector.ConnectorCatalogServiceProvider.getService(ConnectorCatalogServiceProvider.java:40)
	at io.trino.split.PageSinkManager.providerFor(PageSinkManager.java:78)
	at io.trino.split.PageSinkManager.createPageSink(PageSinkManager.java:48)
	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createPageSink(TableWriterOperator.java:139)
	at io.trino.operator.TableWriterOperator$TableWriterOperatorFactory.createOperator(TableWriterOperator.java:128)
	at io.trino.operator.DriverFactory.createDriver(DriverFactory.java:105)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunnerFactory.createDriver(SqlTaskExecution.java:665)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:876)
	at io.trino.execution.executor.dedicated.SplitProcessor.run(SplitProcessor.java:76)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.lambda$run$0(TaskEntry.java:191)
	at io.trino.$gen.Trino_testversion____20240403_140054_570.run(Unknown Source)
	at io.trino.execution.executor.dedicated.TaskEntry$VersionEmbedderBridge.run(TaskEntry.java:192)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:104)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:149)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:165)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:88)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:120)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:935)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:805)
	... 18 more
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:578)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:752)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:153)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:62)
	... 21 more
```

**Comment by martint** [comment] 2024-04-03 19:13
Duplicate of https://github.com/trinodb/trino/issues/20326

**Closed by martint** 2024-04-03 19:13 UTC
Labels: bug
