### ISSUE TITLE
Will user-defined functions be implemented

### ISSUE THREAD

**Issue by guobj** [trinodb/trino#14181] opened 2022-09-19 07:52 UTC
I found that [#8](https://github.com/trinodb/trino/issues/8) mentioned that the user-defined function will be implemented in the future, and the code of #8 has been merged in 395, so when will the user-defined function be implemented?

**Comment by nineinchnick** [comment] 2022-09-19 08:05
This is a duplicate of #13851

**Closed by nineinchnick** 2022-09-19 08:05 UTC
