### ISSUE TITLE
with子句临时表执行多次问题

### ISSUE THREAD

**Issue by pk8est** [trinodb/trino#12454] opened 2022-05-18 09:46 UTC
把下面这条sql分别在mysql和trino执行，在mysql中t1会生成临时表，只执行一次，t2_num等于t3_num; 而在trino中，t1表执行了两次，t2_num不等于t3_num, 有没有办法让trino的执行效果像mysql一样
```sql
WITH t1(num) as (
	SELECT FLOOR(RAND() * 10)
)
,t2(num) as (
	SELECT * from t1
)
,t3(num) as (
	SELECT * from t1
)

SELECT t2.num as t2_num,t3.num as t3_num from t2,t3
```
```
# in mysql
+----------+----------+
|  t2_num  |  t3_num  |
+----------+----------+
|    1     |    1     |
+----------+----------+

# in trino
+----------+----------+
|  t2_num  |  t3_num  |
+----------+----------+
|    8     |    6     |
+----------+----------+
```

**Comment by ebyhr** [comment] 2022-05-18 09:54
Let me close as duplicate of #10. Please post in English from next time.

**Closed by ebyhr** 2022-05-18 09:54 UTC
