### ISSUE TITLE
Fix the docs about  support for views on Nessie catalog and add support for it.

### ISSUE THREAD

**Issue by mariotaddeucci** [trinodb/trino#18742] opened 2023-08-19 22:15 UTC
Actually nessie catalog supports views.

On trino docs, there's no explict info like rest or odbc metastore informing about no support for views.
After reading the docs, I tried the nessie catalog but when tried to create a view i got the error.

`SQL Error [13]: Query failed (#20230819_220413_00001_37y5z): createView is not supported for Iceberg Nessie catalogs`

For versions above 424 should add the same note like rest and odbc saying theres no support for views using nessie but would be nice to add support for this feature on new releases.

**Comment by ebyhr** [comment] 2023-08-20 00:31
Closing as duplicate of #17768

**Closed by ebyhr** 2023-08-20 00:31 UTC
