### ISSUE TITLE
Iceberg Invalid descendant for DeleteNode or UpdateNode: io.trino.sql.planner.plan.ExchangeNode

### ISSUE THREAD

**Issue by aletc1** [trinodb/trino#12462] opened 2022-05-18 14:56 UTC
When doing ```UPDATE``` with a ```WHERE IN``` condition, if the values in the IN are EMPTY, then the command throws exception.

The expected result is to succeed doing nothing (e.g 0 updated rows). Tested with trino version 381.

To reproduce just put a condition ```WHERE 1=2``` in order to force this.

```sql
CREATE TABLE axprod.main.test2 (
    order_date TIMESTAMP(6),
    customer VARCHAR
)
WITH (partitioning = ARRAY['month(order_date)'])
insert into axprod.main.test2 values (null, cast('A' as varchar))
insert into axprod.main.test2 values (current_timestamp(6), cast('B' as varchar))

update axprod.main.test2 set order_date = cast('2022-01-01 23:50' as timestamp(6)) where customer in (select customer from axprod.main.test2 where 1=2)
```

This might seems silly (the 1=2) but in real world scenarios there might be cases when the select inside the IN returns nothing. 
As a workaround you can just first SELECT COUNT(1) and then do the UPDATE if needed, but this might be expensive because the SELECT will run twice.

P.S: Great product and thanks for implementing Iceberg v2

**UPDATE**: Also triggers in other cases with data, not only limited to empty queries. I have tested the DELETE also (same conditions) and it worked.

**Comment by findepi** [comment] 2022-05-18 15:47
Looks like a duplicate of https://github.com/trinodb/trino/issues/12422.

**Closed by findepi** 2022-05-18 15:47 UTC
