### ISSUE TITLE
[Iceberg] partitioned writes with transform columns have poor distribution.

### ISSUE THREAD

**Issue by damnMeddlingKid** [trinodb/trino#12966] opened 2022-06-23 22:19 UTC
## Summary
When trino writes to an iceberg table that uses transforms in its partition scheme it distributes the data using the iceberg bucket function, which works similarly to a fixed hash distribution.

This can result in a skewed task distribution when there are a few large partitions, there are currently no knobs that can be tuned in order to fix this skew.

I've mapped out the logic around partitioned writes, there are 3 main classes involved LogicalPlanner, IcebergMetadata, ApplyPreferredTableWriterPartitioning and AddExchanges.

## Steps
Heres what happens:

1. IcebergMetadata sees that the partition spec contains transform columns so it creates a partition handle https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java#L700
2. LogicalPlanner sees that the connector has specified a partitionhandle so it creates a partitioningScheme based on this https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java#L591-L595
3. ApplyPreferredTableWriterPartitioning does not match this node because theres no preferred partitioning.
4. AddExchanges creates an exchange node based on the iceberg bucket function https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java#L634-L642

Heres a diagram that maps out all codepaths related to partitioned writes in iceberg.

<p align="center">
<img src="https://user-images.githubusercontent.com/422763/175412658-204a6c05-007f-4fff-8548-6b13d813b69e.png" width=300>
</p>

Ideally what we would like is either a scaled write or a redistributed write, those will both round robin the data.

## Possible solutions
- Add some logic to make it possible to choose a scaled/redistributed write, i've tried doing this with our local fork and it worked well but i don't know if there are downsides to not using the connector specific behaviour.
- In a related issue @sopel39 suggested an adaptive exchange that could detect skew and redistribute at runtime https://github.com/trinodb/trino/issues/10791#issuecomment-1131489696

**Comment by findepi** [comment] 2022-06-24 11:58
> This can result in a skewed task distribution when there are a few large partitions, there are currently no knobs that can be tuned in order to fix this skew.

I think this issue is a duplicate of https://github.com/trinodb/trino/issues/10791

> Add some logic to make it possible to choose a scaled/redistributed write,

We could do that, e.g. conditionally disable `io.trino.plugin.iceberg.IcebergMetadata#getInsertLayout` and friends, but I would rather we spend time on things that work out of the box for the end-users: #10791

**Comment by damnMeddlingKid** [comment] 2022-06-24 14:59
thanks for the quick reply!.

> I think this issue is a duplicate of https://github.com/trinodb/trino/issues/10791

thanks for confirming that, i was looking through that issue while debugging but didn't know exactly which part of the problem it was referencing.

 I didn't really understand what was wrong with scale writers because it works fine for iceberg when there are identity partition columns, we have seen some issues with hive where writers might OOM before scaling. 

I'd like to work on this issue, do you think the adaptive exchange is the way forward her e?

also should i add in my context to that issue ?.

> We could do that, e.g. conditionally disable io.trino.plugin.iceberg.IcebergMetadata#getInsertLayout and friends, but I would rather we spend time on things that work out of the box for the end-users: https://github.com/trinodb/trino/issues/10791

agreed!, I wanted to raise this option to get thoughts on if it is a safe solution because we will likely need to apply this change to our internal fork as an emergency fix for our ETLs.

**Comment by damnMeddlingKid** [comment] 2022-06-24 22:34
moving this summary to #10791

**Closed** 2022-06-24 22:34 UTC
