### ISSUE TITLE
Flaky TestHiveTransactionalTable.testBucketedUnpartitionedDelete

### ISSUE THREAD

**Issue by pajaks** [trinodb/trino#21604] opened 2024-04-18 09:13 UTC
```
2024-04-18T08:20:00.3477630Z tests               | 2024-04-18 14:05:00 INFO: FAILURE     /    io.trino.tests.product.hive.TestHiveTransactionalTable.testBucketedUnpartitionedDelete [TRINO, TRINO] (Groups: profile_specific_tests, hive_transactional) took 2.3 seconds
2024-04-18T08:20:00.3486111Z tests               | 2024-04-18 14:05:00 SEVERE: Failure cause:
2024-04-18T08:20:00.3487947Z tests               | java.lang.AssertionError: [onTrino] Expected row count to be <2>, but was <4>; rows=[[Ann], [Lou], [Ann], [Lou]]
2024-04-18T08:20:00.3490224Z tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.verifySelect(TestHiveTransactionalTable.java:2255)
2024-04-18T08:20:00.3492826Z tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.verifySelectForTrinoAndHive(TestHiveTransactionalTable.java:2247)
2024-04-18T08:20:00.3495614Z tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.lambda$testBucketedUnpartitionedDelete$22(TestHiveTransactionalTable.java:900)
2024-04-18T08:20:00.3498292Z tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.withTemporaryTable(TestHiveTransactionalTable.java:1794)
2024-04-18T08:20:00.3500965Z tests               | 	at io.trino.tests.product.hive.TestHiveTransactionalTable.testBucketedUnpartitionedDelete(TestHiveTransactionalTable.java:892)
2024-04-18T08:20:00.3503473Z tests               | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
2024-04-18T08:20:00.3505188Z tests               | 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
2024-04-18T08:20:00.3507111Z tests               | 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2024-04-18T08:20:00.3508992Z tests               | 	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
2024-04-18T08:20:00.3510720Z tests               | 	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
2024-04-18T08:20:00.3512447Z tests               | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
2024-04-18T08:20:00.3514050Z tests               | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
2024-04-18T08:20:00.3515783Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
2024-04-18T08:20:00.3517489Z tests               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
2024-04-18T08:20:00.3518402Z tests               | 	at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by pajaks** [comment] 2024-04-18 09:14
https://github.com/trinodb/trino/actions/runs/8734409850/job/23965081889

**Comment by ebyhr** [comment] 2024-04-22 00:09
Closing as duplicate of #15187

**Closed by ebyhr** 2024-04-22 00:09 UTC
Labels: Flaky Tests
