### ISSUE TITLE
Trino Coordinator gets OOM-killed by querying large iceberg table with DBeaver

### ISSUE THREAD

**Issue by ckesslau** [trinodb/trino#13194] opened 2022-07-15 12:15 UTC
We currently try to updated our trino cluster from version 363 to version 388. We noticed that we can easily get our trino coordinator killed with OOM errors by doing queries from DBeaver on our biggest iceberg table.

**In version 363** a `select *` query on a large table returns results fast (~ 2 seconds) and is then marked as USER CANCLED in trino. In DBeaver only the first 200 rows are shown and another `select *` query is sent if you scroll to the end of this 200-rows page
that again is shown as USER CANCLED and another 200 rows are added to the result list and so on.

**In version 388** the same query returns the first result way slower (~ 8 seconds) and is then marked as USER CANCLED, too. We can than scroll down about one or two extra pages before the trino coordinator gets OOM killed (coordinator logs bellow: [log 363.txt](https://github.com/trinodb/trino/files/9120588/log.363.txt)
[Log 388.txt](https://github.com/trinodb/trino/files/9120589/Log.388.txt)). Memory usage seems to climb up for every new page that gets queried (see screenshots bellow). If we use a higher page size (e. g. 500 instead of 200) we can load more pages but eventually run into the OOM problem as well. 

Query history in version 363:
![Query history v363](https://user-images.githubusercontent.com/91946110/179219440-6e89d9f0-98ce-48e4-b77b-e36e9e3c0a81.PNG)

Query history in version 388:
![Query history v388](https://user-images.githubusercontent.com/91946110/179219442-17c2b483-b612-459c-8964-3f010636c532.PNG)

In version 363 (right side) the data seems to be served from the buffer directly. Also, the time for query planing doubled in the new version 388. 
![Query comparison v388 vs v363](https://user-images.githubusercontent.com/91946110/179219436-713458b1-75e3-4486-9ff2-9e721c6572fd.PNG)

We could not reproduce this behaviour for our other iceberg tables or tables from another catalog, but none of them has that much columns and data.
We used the same trino driver in DBeaver for all those queries, the only difference is the trino version itself. For us, this behaviour is quit puzzling. Can you explain it?
Are there any new configuration parameters we should be aware of to at least not get the coordinator killed? Is there anything else we can try?

**Comment by electrum** [comment] 2022-07-21 22:46
Can you show the table definition (`DESCRIBE` or `SHOW CREATE TABLE`) and the query being run? How much memory does the coordinator have?

**Comment by electrum** [comment] 2022-07-21 22:49
Also, it might help to see the number of partitions, files, etc., to see if that's a clue. Could you show the output of the [$partitions](https://trino.io/docs/current/connector/iceberg.html#partitions-table) and [$files](https://trino.io/docs/current/connector/iceberg.html#files-table) tables?

What would be most helpful is if you can reproduce this by creating a large table, similar to your problem table, by inserting data from the TPC-H or TPC-DS connectors.

**Comment by ckesslau** [comment] 2022-08-02 11:15
Sorry for the late reply.

The query is a simple `SELECT *` (see screenshots of trino UI). The table has the following `CREATE` statement:
```sql
CREATE TABLE iceberg.default.boxdata (
   _partition_id bigint,
   _partition_offset bigint,
   portal_id bigint,
   box_time_event timestamp(6) with time zone,
   column_1 varchar,
   column_2 varchar,
   column_3 varchar,
   column_4 varchar,
   column_5 bigint,
   column_6 double,
   column_7 boolean,
   column_8 boolean,
   column_9 double,
   column_10 varchar,
   column_11 varchar,
   column_12 varchar,
   column_13 double,
   column_14 varchar,
   column_15 bigint,
   column_16 bigint,
   column_17 varchar,
   column_18 boolean,
   column_19 bigint,
   column_20 boolean,
   column_21 boolean,
   column_22 boolean,
   column_23 double,
   column_24 varchar,
   column_25 bigint,
   column_26 bigint,
   column_27 bigint,
   column_28 timestamp(6) with time zone,
   column_29 bigint,
   column_30 boolean,
   column_31 bigint,
   column_32 bigint,
   column_33 varchar,
   column_34 bigint,
   column_35 timestamp(6) with time zone,
   column_36 timestamp(6) with time zone,
   column_37 timestamp(6) with time zone,
   column_38 timestamp(6) with time zone,
   column_39 varchar,
   column_40 varchar,
   column_41 double,
   column_42 varchar,
   column_43 varchar,
   column_44 varchar,
   column_45 boolean,
   column_46 boolean,
   column_47 varchar,
   column_48 varchar,
   column_49 boolean,
   column_50 varchar,
   column_51 varchar,
   column_52 varchar,
   column_53 varchar,
   column_54 bigint,
   column_55 bigint,
   column_56 varchar,
   column_57 varchar,
   column_58 bigint,
   column_59 varchar,
   column_60 bigint,
   column_61 bigint,
   column_62 boolean,
   column_63 boolean,
   column_64 double,
   column_65 boolean,
   column_66 boolean,
   column_67 boolean,
   column_68 bigint,
   column_69 boolean,
   column_70 double,
   column_71 boolean,
   column_72 varchar,
   column_73 varchar,
   column_74 boolean,
   column_75 varchar,
   column_76 bigint,
   column_77 double,
   column_78 timestamp(6) with time zone,
   column_79 varchar,
   column_80 bigint,
   column_81 bigint,
   column_82 varchar,
   column_83 double,
   column_84 double,
   column_85 bigint,
   column_86 bigint,
   column_87 varchar,
   column_88 bigint,
   column_89 bigint,
   column_90 varchar,
   column_91 varchar,
   column_92 double,
   column_93 varchar,
   column_94 varchar,
   column_95 varchar,
   column_96 varchar,
   column_97 varchar,
   column_98 bigint,
   column_99 boolean,
   column_100 double,
   column_101 boolean,
   column_102 varchar,
   column_103 varchar,
   column_104 varchar,
   column_105 varchar,
   column_106 boolean,
   column_107 double,
   column_108 bigint,
   column_109 bigint,
   column_110 varchar,
   column_111 varchar,
   column_112 varchar,
   column_113 varchar,
   column_114 varchar,
   column_115 varchar,
   column_116 timestamp(6) with time zone,
   column_117 bigint,
   column_118 bigint,
   column_119 bigint,
   column_120 bigint,
   column_121 boolean,
   column_122 bigint,
   column_123 bigint,
   column_124 boolean,
   column_125 timestamp(6) with time zone,
   column_126 bigint,
   column_127 varchar,
   column_128 boolean,
   column_129 boolean,
   column_130 boolean,
   column_131 varchar,
   column_132 boolean,
   column_133 varchar,
   column_134 varchar,
   column_135 varchar,
   column_136 varchar,
   column_137 timestamp(6) with time zone,
   column_138 varchar,
   column_139 varchar,
   column_140 varchar,
   column_141 varchar,
   column_142 varchar,
   column_143 varchar,
   column_144 varchar,
   column_145 varchar,
   column_146 boolean,
   column_147 varchar
)
WITH (
   format = 'ORC',
   partitioning = ARRAY['_partition_id','portal_id','day(box_time_event)']
)
```
I replaced the column names and removed the comments from this statement. I hope this helps despite the anonymisation.

**Comment by ckesslau** [comment] 2022-08-02 11:17
We are running our trino servers in k8s. The nodes have 16 vCPUs and 32 GB of RAM but we have to share it with other pods so trino can probably only use around 15GB. We are currently running one coordinator and 10 workers. We use the following settings without a problem for version 363 and older:
```
query.max-memory-per-node=8GB
query.max-total-memory-per-node=10GB
memory.heap-headroom-per-node=2GB
query.max-memory=40GB
query.max-total-memory=44GB
```
The table in question is ~530Gb on hadoop and has 8.1 billion rows in 151 columns. The table is partitioned by three columns, but most queries only use 2 of these partitions. We didn't change the config except of removing query.max-total-memory-per-node and query.max-total-memory (because they were removed from trino).

**Comment by hashhar** [comment] 2022-08-03 06:51
@ckesslau Does your Iceberg have delete files? Also how many snapshots?

cc: @findepi

**Comment by ckesslau** [comment] 2022-08-03 07:55
No, we do not use delete files. 
We regularly insert data into the table from kafka and run iceberg maintenance operations every hour (where we delete all snapshots older than 2 hours). So the number of snapshots is somewhat consistent. Currently, there are 171 snapshots for this table. Should we keep the number of snapshots lower?

**Comment by osscm** [comment] 2022-10-15 19:54
@ckesslau as @electrum has requested, can you please share the $files and 

> Also, it might help to see the number of partitions, files, etc., to see if that's a clue. Could you show the output of the [$partitions](https://trino.io/docs/current/connector/iceberg.html#partitions-table) and [$files](https://trino.io/docs/current/connector/iceberg.html#files-table) tables?
> 
> What would be most helpful is if you can reproduce this by creating a large table, similar to your problem table, by inserting data from the TPC-H or TPC-DS connectors.

@ckesslau can you please share the above mentioned metadata table content and also the size of the table/partitions you are querying against?

also when you run this query with limit from CLI, you seeing same behavior?

**Comment by ckesslau** [comment] 2022-10-20 08:22
Sorry for the delay.
I recently tested version 399 of Trino and could not reproduce the issue with that version. Unfortunatly a new issue with insert querys to this table stopped me from actually using this version now. 

Are you still interested in the metadata tables?

**Comment by osscm** [comment] 2022-10-22 18:02
Yeah please share, so that we some data point if this happens again or someone else report in the community. 

Though for now we can close the issue as the issue is not reproducible with 399.

**Comment by arghya18** [comment] 2023-01-24 12:48
Hi @ckesslau @electrum 
Is this resolved in latest version? We are also getting this Trino 370. The coordinator having OOM error with a count query on a partitioned table having 16k partitions.

**Comment by hellozeck** [comment] 2024-01-08 04:41
I encountered similar problem.
Version: 405
coordinator: 32G
When I submit a lot of queries in icebery, I keep 2 concurrent, that is, there are only 2 queries at the same time. Most queries only need to run for 10 seconds, and will ooom after a while. I got the jstack file
[Uploading jstack.txt…]()

**Comment by raunaqmorarka** [comment] 2024-10-07 08:10
There have been improvements to iceberg metadata handling on coordinator in recent releases.
Please try this on 455 or newer.

**Closed by raunaqmorarka** 2024-10-07 08:10 UTC
