### ISSUE TITLE
Flaky test TestMemoryConnectorTest.testCustomMetricsScanFilter

### ISSUE THREAD

**Issue by electrum** [trinodb/trino#8793] opened 2021-08-04 18:29 UTC
https://github.com/trinodb/trino/pull/8771/checks?check_run_id=3235051688

```
[ERROR] Tests run: 239, Failures: 1, Errors: 0, Skipped: 28, Time elapsed: 196.537 s <<< FAILURE! - in TestSuite
[ERROR] testCustomMetricsScanFilter(io.trino.plugin.memory.TestMemoryConnectorTest)  Time elapsed: 0.126 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<LongCount{total=[2000]}> but was:<LongCount{total=[1665]}>
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at io.trino.plugin.memory.TestMemoryConnectorTest.testCustomMetricsScanFilter(TestMemoryConnectorTest.java:154)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by electrum** [comment] 2021-08-04 18:36
There are lots of these:
```
2021-08-03T16:56:08.059-0500 WARNING Error while inspecting age of task 20210803_215606_00009_9gh9k.1.0
java.lang.IllegalArgumentException: Expected operatorType to be PagesIndexBuilderOperator but was PageBufferOperator
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:443)
	at io.trino.operator.OperatorStats.add(OperatorStats.java:489)
	at io.trino.operator.OperatorStats.add(OperatorStats.java:438)
	at io.trino.operator.PipelineContext.getPipelineStats(PipelineContext.java:413)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:783)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:467)
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:854)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:276)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:233)
	at io.trino.operator.TaskContext.getTaskStats(TaskContext.java:428)
	at io.trino.execution.SqlTask.getTaskStats(SqlTask.java:353)
	at io.trino.execution.SqlTask.createTaskInfo(SqlTask.java:375)
	at io.trino.execution.SqlTask.getTaskInfo(SqlTask.java:237)
	at io.trino.execution.SqlTaskManager.failAbandonedTasks(SqlTaskManager.java:495)
	at io.trino.execution.SqlTaskManager.lambda$start$4(SqlTaskManager.java:240)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2021-08-03T16:56:08.262-0500 WARNING Error removing old tasks
java.lang.IllegalArgumentException: Expected operatorType to be PagesIndexBuilderOperator but was PageBufferOperator
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:443)
	at io.trino.operator.OperatorStats.add(OperatorStats.java:489)
	at io.trino.operator.OperatorStats.add(OperatorStats.java:438)
	at io.trino.operator.PipelineContext.getPipelineStats(PipelineContext.java:413)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:783)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:467)
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:854)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:276)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:233)
	at io.trino.operator.TaskContext.getTaskStats(TaskContext.java:428)
	at io.trino.execution.SqlTask.getTaskStats(SqlTask.java:353)
	at io.trino.execution.SqlTask.createTaskInfo(SqlTask.java:375)
	at io.trino.execution.SqlTask.getTaskInfo(SqlTask.java:237)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.trino.execution.SqlTaskManager.removeOldTasks(SqlTaskManager.java:475)
	at io.trino.execution.SqlTaskManager.lambda$start$4(SqlTaskManager.java:234)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by electrum** [comment] 2021-08-04 19:24
cc @rzeyde-varada

**Comment by rzeyde-varada** [comment] 2021-08-05 06:19
The flakiness seems to be the same as reported in https://github.com/trinodb/trino/issues/8691#issue-954707530

**Comment by rzeyde-varada** [comment] 2021-08-05 06:25
Not sure about https://github.com/trinodb/trino/issues/8793#issuecomment-892882805 - seems that it happens also in other builds:
https://github.com/trinodb/trino/runs/3245125396?check_suite_focus=true#step:5:28308
https://github.com/trinodb/trino/runs/3244066755?check_suite_focus=true#step:5:21475
https://github.com/trinodb/trino/runs/3160717555?check_suite_focus=true#step:5:21402

**Comment by rzeyde-varada** [comment] 2021-08-05 07:56
Reproduced locally with `TestThriftDistributedQueriesIndexed#testHighCardinalityIndexJoinResult` on Trino 359:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.airlift.compress.zstd.UnsafeUtil (file:/Users/zeyde/.m2/repository/io/airlift/aircompressor/0.16/aircompressor-0.16.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of io.airlift.compress.zstd.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-08-05T02:45:57.143-0500 WARNING Error removing old tasks
java.lang.IllegalArgumentException: Expected operatorType to be PagesIndexBuilderOperator but was PageBufferOperator
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:443)
	at io.trino.operator.OperatorStats.add(OperatorStats.java:478)
	at io.trino.operator.OperatorStats.add(OperatorStats.java:428)
	at io.trino.operator.PipelineContext.getPipelineStats(PipelineContext.java:413)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:783)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:467)
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:854)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:276)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:233)
	at io.trino.operator.TaskContext.getTaskStats(TaskContext.java:417)
	at io.trino.execution.SqlTask.getTaskStats(SqlTask.java:350)
	at io.trino.execution.SqlTask.createTaskInfo(SqlTask.java:372)
	at io.trino.execution.SqlTask.getTaskInfo(SqlTask.java:234)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.trino.execution.SqlTaskManager.removeOldTasks(SqlTaskManager.java:458)
	at io.trino.execution.SqlTaskManager.lambda$start$4(SqlTaskManager.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2021-08-05T02:45:57.148-0500 WARNING Error while inspecting age of task 20210805_074554_00000_zqndc.1.0
java.lang.IllegalArgumentException: Expected operatorType to be PagesIndexBuilderOperator but was PageBufferOperator
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:443)
	at io.trino.operator.OperatorStats.add(OperatorStats.java:478)
	at io.trino.operator.OperatorStats.add(OperatorStats.java:428)
	at io.trino.operator.PipelineContext.getPipelineStats(PipelineContext.java:413)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:783)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:467)
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:854)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:276)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:233)
	at io.trino.operator.TaskContext.getTaskStats(TaskContext.java:417)
	at io.trino.execution.SqlTask.getTaskStats(SqlTask.java:350)
	at io.trino.execution.SqlTask.createTaskInfo(SqlTask.java:372)
	at io.trino.execution.SqlTask.getTaskInfo(SqlTask.java:234)
	at io.trino.execution.SqlTaskManager.failAbandonedTasks(SqlTaskManager.java:478)
	at io.trino.execution.SqlTaskManager.lambda$start$4(SqlTaskManager.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2021-08-05T02:45:57.333-0500 SEVERE Error destroying driver for task 20210805_074554_00000_zqndc.1.0
java.lang.IllegalArgumentException: Expected operatorType to be PagesIndexBuilderOperator but was PageBufferOperator
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:443)
	at io.trino.operator.OperatorStats.add(OperatorStats.java:478)
	at io.trino.operator.OperatorStats.add(OperatorStats.java:428)
	at io.trino.operator.PipelineContext.lambda$driverFinished$0(PipelineContext.java:200)
	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2048)
	at io.trino.operator.PipelineContext.driverFinished(PipelineContext.java:200)
	at io.trino.operator.DriverContext.finished(DriverContext.java:172)
	at io.trino.operator.Driver.destroyIfNecessary(Driver.java:527)
	at io.trino.operator.Driver.tryWithLock(Driver.java:691)
	at io.trino.operator.Driver.tryWithLock(Driver.java:661)
	at io.trino.operator.Driver.isFinished(Driver.java:195)
	at io.trino.operator.index.StreamingIndexedData.loadNextPage(StreamingIndexedData.java:101)
	at io.trino.operator.index.StreamingIndexedData.getNextJoinPosition(StreamingIndexedData.java:89)
	at io.trino.operator.index.IndexLookupSource.getNextJoinPosition(IndexLookupSource.java:94)
	at io.trino.operator.join.DefaultPageJoiner.joinCurrentPosition(DefaultPageJoiner.java:281)
	at io.trino.operator.join.DefaultPageJoiner.processProbe(DefaultPageJoiner.java:240)
	at io.trino.operator.join.DefaultPageJoiner.lambda$processProbe$2(DefaultPageJoiner.java:231)
	at io.trino.operator.join.StaticLookupSourceProvider.withLease(StaticLookupSourceProvider.java:34)
	at io.trino.operator.join.DefaultPageJoiner.processProbe(DefaultPageJoiner.java:224)
	at io.trino.operator.join.DefaultPageJoiner.process(DefaultPageJoiner.java:184)
	at io.trino.operator.join.DefaultPageJoiner.process(DefaultPageJoiner.java:63)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorOperatorAdapter.getOutput(WorkProcessorOperatorAdapter.java:188)
	at io.trino.operator.Driver.processInternal(Driver.java:387)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
	at io.trino.operator.Driver.tryWithLock(Driver.java:683)
	at io.trino.operator.Driver.processFor(Driver.java:284)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_testversion____20210805_074545_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2021-08-05T02:45:57.358-0500 WARNING Error removing old tasks
java.lang.IllegalArgumentException: Expected operatorType to be PagesIndexBuilderOperator but was PageBufferOperator
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:443)
	at io.trino.operator.OperatorStats.add(OperatorStats.java:478)
	at io.trino.operator.OperatorStats.add(OperatorStats.java:428)
	at io.trino.operator.PipelineContext.getPipelineStats(PipelineContext.java:413)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:783)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:467)
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:854)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:276)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:233)
	at io.trino.operator.TaskContext.getTaskStats(TaskContext.java:417)
	at io.trino.execution.SqlTask.getTaskStats(SqlTask.java:350)
	at io.trino.execution.SqlTask.createTaskInfo(SqlTask.java:372)
	at io.trino.execution.SqlTask.getTaskInfo(SqlTask.java:234)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.trino.execution.SqlTaskManager.removeOldTasks(SqlTaskManager.java:458)
	at io.trino.execution.SqlTaskManager.lambda$start$4(SqlTaskManager.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2021-08-05T02:45:57.359-0500 WARNING Error while inspecting age of task 20210805_074554_00000_zqndc.1.0
java.lang.IllegalArgumentException: Expected operatorType to be PagesIndexBuilderOperator but was PageBufferOperator
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:443)
	at io.trino.operator.OperatorStats.add(OperatorStats.java:478)
	at io.trino.operator.OperatorStats.add(OperatorStats.java:428)
	at io.trino.operator.PipelineContext.getPipelineStats(PipelineContext.java:413)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:783)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:467)
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:854)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:276)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:233)
	at io.trino.operator.TaskContext.getTaskStats(TaskContext.java:417)
	at io.trino.execution.SqlTask.getTaskStats(SqlTask.java:350)
	at io.trino.execution.SqlTask.createTaskInfo(SqlTask.java:372)
	at io.trino.execution.SqlTask.getTaskInfo(SqlTask.java:234)
	at io.trino.execution.SqlTaskManager.failAbandonedTasks(SqlTaskManager.java:478)
	at io.trino.execution.SqlTaskManager.lambda$start$4(SqlTaskManager.java:237)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2021-08-05T02:45:57.455-0500 SEVERE Error destroying driver for task 20210805_074554_00000_zqndc.1.0
java.lang.IllegalArgumentException: Expected operatorType to be PagesIndexBuilderOperator but was PageBufferOperator
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:443)
	at io.trino.operator.OperatorStats.add(OperatorStats.java:478)
	at io.trino.operator.OperatorStats.add(OperatorStats.java:428)
	at io.trino.operator.PipelineContext.lambda$driverFinished$0(PipelineContext.java:200)
	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2048)
	at io.trino.operator.PipelineContext.driverFinished(PipelineContext.java:200)
	at io.trino.operator.DriverContext.finished(DriverContext.java:172)
	at io.trino.operator.Driver.destroyIfNecessary(Driver.java:527)
	at io.trino.operator.Driver.tryWithLock(Driver.java:691)
	at io.trino.operator.Driver.tryWithLock(Driver.java:661)
	at io.trino.operator.Driver.isFinished(Driver.java:195)
	at io.trino.operator.index.StreamingIndexedData.loadNextPage(StreamingIndexedData.java:101)
	at io.trino.operator.index.StreamingIndexedData.getNextJoinPosition(StreamingIndexedData.java:89)
	at io.trino.operator.index.IndexLookupSource.getNextJoinPosition(IndexLookupSource.java:94)
	at io.trino.operator.join.DefaultPageJoiner.joinCurrentPosition(DefaultPageJoiner.java:281)
	at io.trino.operator.join.DefaultPageJoiner.processProbe(DefaultPageJoiner.java:240)
	at io.trino.operator.join.DefaultPageJoiner.lambda$processProbe$2(DefaultPageJoiner.java:231)
	at io.trino.operator.join.StaticLookupSourceProvider.withLease(StaticLookupSourceProvider.java:34)
	at io.trino.operator.join.DefaultPageJoiner.processProbe(DefaultPageJoiner.java:224)
	at io.trino.operator.join.DefaultPageJoiner.process(DefaultPageJoiner.java:184)
	at io.trino.operator.join.DefaultPageJoiner.process(DefaultPageJoiner.java:63)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorUtils.lambda$flatten$6(WorkProcessorUtils.java:277)
	at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:319)
	at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:372)
	at io.trino.operator.WorkProcessorOperatorAdapter.getOutput(WorkProcessorOperatorAdapter.java:188)
	at io.trino.operator.Driver.processInternal(Driver.java:387)
	at io.trino.operator.Driver.lambda$processFor$9(Driver.java:291)
	at io.trino.operator.Driver.tryWithLock(Driver.java:683)
	at io.trino.operator.Driver.processFor(Driver.java:284)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.trino.$gen.Trino_testversion____20210805_074545_1.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2021-08-05T02:45:57.797-0500 INFO TIMELINE: Query 20210805_074554_00000_zqndc :: Transaction:[ea7509f0-870e-4525-b27f-aeba8b5e88e8] :: elapsed 3030ms :: planning 658ms :: waiting 229ms :: scheduling 986ms :: running 508ms :: finishing 878ms :: begin 2021-08-05T02:45:54.516-05:00 :: end 2021-08-05T02:45:57.546-05:00
2021-08-05T02:45:58.414-0500 INFO FINISHED in Trino: 3.84s, H2: 285.70ms, total: 4.13s
```

**Comment by findepi** [comment] 2021-08-05 11:41
closing in favor of https://github.com/trinodb/trino/issues/8691

**Closed by findepi** 2021-08-05 11:41 UTC
