### ISSUE TITLE
Predicate pushdown is not working anymore when casting partition columns in JOIN queries

### ISSUE THREAD

**Issue by laithalzyoud** [trinodb/trino#22297] opened 2024-06-06 09:53 UTC
It seems that there is a bug introduced in versions after 439 that causes full table scan when a cast function is used on the partition column (i.e `date(created_ts) > date('2024-05-25')  vs created_ts > date('2024-05-25')` ) when filtering with a JOIN statement. The same behaviour is observed in 446 and 448, this happens with the Iceberg connector.

Example query:
```
SELECT COUNT(*)
FROM table_schema_1.table_name_1 tb 
JOIN table_schema_2.table_name_2 tdd ON tb.some_column = tdd.some_column
WHERE cast(tdd.date_column as date) > date('2024-03-14') and cast(tdd.date_column as date) <= date('2024-03-15')
AND cast(tb.date_column as date) > date('2024-03-14') and cast(tb.date_column as date) <= date('2024-03-15')
```

439 EXPLAIN output:

```
Trino version: 439
Fragment 0 [SINGLE]
    Output layout: [count]
    Output partitioning: SINGLE []
    Output[columnNames = [_col0]]
    │   Layout: [count:bigint]
    │   Estimates: {rows: 1 (9B), cpu: 0, memory: 0B, network: 0B}
    │   _col0 := count
    └─ Aggregate[type = FINAL]
       │   Layout: [count:bigint]
       │   Estimates: {rows: 1 (9B), cpu: ?, memory: 9B, network: 0B}
       │   count := count("count_5")
       └─ LocalExchange[partitioning = SINGLE]
          │   Layout: [count_5:bigint]
          │   Estimates: {rows: ? (?), cpu: 0, memory: 0B, network: 0B}
          └─ RemoteSource[sourceFragmentIds = [1]]
                 Layout: [count_5:bigint]

Fragment 1 [HASH]
    Output layout: [count_5]
    Output partitioning: SINGLE []
    Aggregate[type = PARTIAL]
    │   Layout: [count_5:bigint]
    │   count_5 := count(*)
    └─ InnerJoin[criteria = ("some_column" = "some_column_1"), distribution = PARTITIONED]
       │   Layout: []
       │   Estimates: {rows: ? (0B), cpu: 8.15G, memory: 4.02GB, network: 0B}
       │   Distribution: PARTITIONED
       │   dynamicFilterAssignments = {some_column_1 -> #df_511}
       ├─ RemoteSource[sourceFragmentIds = [2]]
       │      Layout: [some_column:varchar]
       └─ LocalExchange[partitioning = HASH, arguments = ["some_column_1"]]
          │   Layout: [some_column_1:varchar]
          │   Estimates: {rows: 53999254 (4.02GB), cpu: 4.02G, memory: 0B, network: 0B}
          └─ RemoteSource[sourceFragmentIds = [3]]
                 Layout: [some_column_1:varchar]

Fragment 2 [SOURCE]
    Output layout: [some_column]
    Output partitioning: HASH [some_column]
    ScanFilter[table = table_schema_1.table_name_1$data@8240353482974232944 constraint on [leg_type, date_column], dynamicFilters = {"some_column" = #df_511}]
        Layout: [some_column:varchar]
        Estimates: {rows: 51719006 (4.13GB), cpu: 4.13G, memory: 0B, network: 0B}/{rows: 51719006 (4.13GB), cpu: 4.13G, memory: 0B, network: 0B}
        some_column := 3:some_column:varchar
        21:leg_type:varchar
            :: [[B]]
        17:date_column:timestamp(6) with time zone
            :: [[2024-03-15 00:00:00.000000 UTC, 2024-03-16 00:00:00.000000 UTC)]

Fragment 3 [SOURCE]
    Output layout: [some_column_1]
    Output partitioning: HASH [some_column_1]
    TableScan[table = table_schema_2.table_name_2$data@7888920103828421670 constraint on [date_column]]
        Layout: [some_column_1:varchar]
        Estimates: {rows: 53999254 (4.02GB), cpu: 4.02G, memory: 0B, network: 0B}
        some_column_1 := 2:some_column:varchar
        4:date_column:timestamp(6) with time zone
            :: [[2024-03-15 00:00:00.000000 UTC, 2024-03-16 00:00:00.000000 UTC)]
```

448 EXPLAIN output:
```
Trino version: 448
Fragment 0 [SINGLE]
    Output layout: [count]
    Output partitioning: SINGLE []
    Output[columnNames = [_col0]]
    │   Layout: [count:bigint]
    │   Estimates: {rows: 1 (9B), cpu: 0, memory: 0B, network: 0B}
    │   _col0 := count
    └─ Aggregate[type = FINAL]
       │   Layout: [count:bigint]
       │   Estimates: {rows: 1 (9B), cpu: ?, memory: 9B, network: 0B}
       │   count := count(count_5)
       └─ LocalExchange[partitioning = SINGLE]
          │   Layout: [count_5:bigint]
          │   Estimates: {rows: ? (?), cpu: 0, memory: 0B, network: 0B}
          └─ RemoteSource[sourceFragmentIds = [1]]
                 Layout: [count_5:bigint]

Fragment 1 [HASH]
    Output layout: [count_5]
    Output partitioning: SINGLE []
    Aggregate[type = PARTIAL]
    │   Layout: [count_5:bigint]
    │   count_5 := count(*)
    └─ InnerJoin[criteria = (some_column = some_column_1), filter = ((CAST(date_column_2 AS date) > date '2024-03-14') AND (CAST(date_column_2 AS date) <= date '2024-03-15') AND (CAST(date_column AS date) > date '2024-03-14') AND (CAST(date_column AS date) <= date '2024-03-15')), distribution = PARTITIONED]
       │   Layout: []
       │   Estimates: {rows: ? (0B), cpu: 5.36T, memory: 2.35TB, network: 0B}
       │   Distribution: PARTITIONED
       │   dynamicFilterAssignments = {some_column_1 -> #df_492}
       ├─ RemoteSource[sourceFragmentIds = [2]]
       │      Layout: [some_column:varchar, date_column:timestamp(6) with time zone]
       └─ LocalExchange[partitioning = HASH, arguments = [some_column_1::varchar]]
          │   Layout: [some_column_1:varchar, date_column_2:timestamp(6) with time zone]
          │   Estimates: {rows: 27267655719 (2.35TB), cpu: 2.35T, memory: 0B, network: 0B}
          └─ RemoteSource[sourceFragmentIds = [3]]
                 Layout: [some_column_1:varchar, date_column_2:timestamp(6) with time zone]

Fragment 2 [SOURCE]
    Output layout: [some_column, date_column]
    Output partitioning: HASH [some_column]
    ScanFilter[table = table_schema_1.table_name_1$data@8240353482974232944 constraint on [leg_type], dynamicFilters = {some_column = #df_492}]
        Layout: [some_column:varchar, date_column:timestamp(6) with time zone]
        Estimates: {rows: 32746042372 (3.02TB), cpu: 3.02T, memory: 0B, network: 0B}/{rows: 32746042372 (3.02TB), cpu: 3.02T, memory: 0B, network: 0B}
        some_column := 3:some_column:varchar
        date_column := 17:date_column:timestamp(6) with time zone
        21:leg_type:varchar
            :: [[B]]

Fragment 3 [SOURCE]
    Output layout: [some_column_1, date_column_2]
    Output partitioning: HASH [some_column_1]
    TableScan[table = table_schema_2.table_name_2$data@7888920103828421670]
        Layout: [some_column_1:varchar, date_column_2:timestamp(6) with time zone]
        Estimates: {rows: 27267655719 (2.35TB), cpu: 2.35T, memory: 0B, network: 0B}
        some_column_1 := 2:some_column:varchar
        date_column_2 := 4:date_column:timestamp(6) with time zone
```

**Comment by martint** [comment] 2024-07-22 18:55
Duplicate of https://github.com/trinodb/trino/issues/22268

**Closed by martint** 2024-07-22 18:55 UTC
