### ISSUE TITLE
Version 360 - USE statement - java.sql.SQLException: Error executing query

### ISSUE THREAD

**Issue by walter-weinmann** [trinodb/trino#8741] opened 2021-08-01 00:16 UTC
### MySQL Connector

```
2021-08-01 02:13:55,293 [DatabaseSeeder.java] INFO  Start MySQL Database via trino
2021-08-01 02:13:55,296 [AbstractDbmsSeeder.java] INFO  tickerSymbolIntern =mysql
2021-08-01 02:13:55,306 [AbstractJdbcSeeder.java] INFO  tickerSymbolExtern =mysql_trino
java.sql.SQLException: Error executing query
        at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:287)
        at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.executeSQLStmnts(AbstractJdbcSeeder.java:1335)
        at ch.konnexions.db_seeder.jdbc.mysql.MysqlSeeder.setupDatabase(MysqlSeeder.java:143)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSeeder.java:404)
        at ch.konnexions.db_seeder.DatabaseSeeder.main(DatabaseSeeder.java:215)
Caused by: java.io.UncheckedIOException: java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:8080
        at io.trino.jdbc.$internal.client.JsonResponse.execute(JsonResponse.java:148)
        at io.trino.jdbc.$internal.client.StatementClientV1.<init>(StatementClientV1.java:109)
        at io.trino.jdbc.$internal.client.StatementClientFactory.newStatementClient(StatementClientFactory.java:24)
        at io.trino.jdbc.TrinoConnection.startQuery(TrinoConnection.java:750)
        at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:252)
        ... 5 more
Caused by: java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:8080
        at io.trino.jdbc.$internal.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265)
        at io.trino.jdbc.$internal.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
        at io.trino.jdbc.$internal.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
        at io.trino.jdbc.$internal.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
        at io.trino.jdbc.$internal.okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
        at io.trino.jdbc.$internal.okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
        at io.trino.jdbc.$internal.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
        at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at io.trino.jdbc.$internal.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at io.trino.jdbc.$internal.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at io.trino.jdbc.$internal.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at io.trino.jdbc.$internal.client.OkHttpUtil.lambda$userAgent$0(OkHttpUtil.java:65)
        at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at io.trino.jdbc.$internal.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at io.trino.jdbc.$internal.okhttp3.RealCall.execute(RealCall.java:81)
        at io.trino.jdbc.$internal.client.JsonResponse.execute(JsonResponse.java:130)
        ... 9 more
Caused by: java.net.ConnectException: Connection refused: no further information
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:660)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
        at java.base/java.net.Socket.connect(Socket.java:648)
        at io.trino.jdbc.$internal.okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
        at io.trino.jdbc.$internal.okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
        ... 31 more
Processing of the script was aborted, error code=1
```

### Oracle Connector

```
2021-08-01 02:20:54,780 [DatabaseSeeder.java] INFO  Start Oracle Database via trino
2021-08-01 02:20:54,784 [AbstractDbmsSeeder.java] INFO  tickerSymbolIntern =oracle
2021-08-01 02:20:54,792 [AbstractJdbcSeeder.java] INFO  tickerSymbolExtern =oracle_trino
java.sql.SQLException: Error executing query
        at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:287)
        at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)
        at io.trino.jdbc.TrinoStatement.executeQuery(TrinoStatement.java:78)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.executeSQLStmnt(AbstractJdbcSeeder.java:1280)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.countData(AbstractJdbcSeeder.java:365)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSeeder.java:475)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSeeder.java:429)
        at ch.konnexions.db_seeder.DatabaseSeeder.main(DatabaseSeeder.java:233)
Caused by: java.io.UncheckedIOException: java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:8080
        at io.trino.jdbc.$internal.client.JsonResponse.execute(JsonResponse.java:148)
        at io.trino.jdbc.$internal.client.StatementClientV1.<init>(StatementClientV1.java:109)
        at io.trino.jdbc.$internal.client.StatementClientFactory.newStatementClient(StatementClientFactory.java:24)
        at io.trino.jdbc.TrinoConnection.startQuery(TrinoConnection.java:750)
        at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:252)
        ... 7 more
```

### PostgreSQL Connector

```
2021-08-01 02:26:26,167 [DatabaseSeeder.java] INFO  Start PostgreSQL via trino
2021-08-01 02:26:26,170 [AbstractDbmsSeeder.java] INFO  tickerSymbolIntern =postgresql
2021-08-01 02:26:26,178 [AbstractJdbcSeeder.java] INFO  tickerSymbolExtern =postgresql_trino
java.sql.SQLException: Error executing query
        at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:287)
        at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)
        at io.trino.jdbc.TrinoStatement.executeQuery(TrinoStatement.java:78)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.executeSQLStmnt(AbstractJdbcSeeder.java:1280)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.countData(AbstractJdbcSeeder.java:365)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSeeder.java:475)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSeeder.java:429)
        at ch.konnexions.db_seeder.DatabaseSeeder.main(DatabaseSeeder.java:251)
Caused by: java.io.UncheckedIOException: java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:8080
        at io.trino.jdbc.$internal.client.JsonResponse.execute(JsonResponse.java:148)
        at io.trino.jdbc.$internal.client.StatementClientV1.<init>(StatementClientV1.java:109)
        at io.trino.jdbc.$internal.client.StatementClientFactory.newStatementClient(StatementClientFactory.java:24)
        at io.trino.jdbc.TrinoConnection.startQuery(TrinoConnection.java:750)
        at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:252)
        ... 7 more
Caused by: java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:8080
```

### SQLServer Connector

```
2021-08-01 02:28:34,531 [DatabaseSeeder.java] INFO  Start SQL Server via trino
2021-08-01 02:28:34,535 [AbstractDbmsSeeder.java] INFO  tickerSymbolIntern =sqlserver
2021-08-01 02:28:34,543 [AbstractJdbcSeeder.java] INFO  tickerSymbolExtern =sqlserver_trino
java.sql.SQLException: Error executing query
        at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:287)
        at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)
        at io.trino.jdbc.TrinoStatement.executeQuery(TrinoStatement.java:78)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.executeSQLStmnt(AbstractJdbcSeeder.java:1280)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.countData(AbstractJdbcSeeder.java:365)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSeeder.java:475)
        at ch.konnexions.db_seeder.jdbc.AbstractJdbcSeeder.createData(AbstractJdbcSeeder.java:429)
        at ch.konnexions.db_seeder.DatabaseSeeder.main(DatabaseSeeder.java:269)
Caused by: java.io.UncheckedIOException: java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:8080
        at io.trino.jdbc.$internal.client.JsonResponse.execute(JsonResponse.java:148)
        at io.trino.jdbc.$internal.client.StatementClientV1.<init>(StatementClientV1.java:109)
        at io.trino.jdbc.$internal.client.StatementClientFactory.newStatementClient(StatementClientFactory.java:24)
        at io.trino.jdbc.TrinoConnection.startQuery(TrinoConnection.java:750)
        at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:252)
        ... 7 more
Caused by: java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:8080

```

**Comment by ebyhr** [comment] 2021-08-01 00:53
I couldn't reproduce it with Trino server version 360 and JDBC driver version 360. Can you make sure the connection between your application and Trino server? Also, if you could leave the simple steps to reproduce without your application, it's helpful for debugging the issue.

**Comment by walter-weinmann** [comment] 2021-08-01 02:27
@ebyhr thanks a lot for the support.

I use a very stable environment with the official Docker image and the JDBC driver from the Maven repository. It is easy for me to vary the different versions:

Docker 359 / JDBC 359: ok 
Docker 359 / JDBC 360: ok
Docker 360 / JDBC 359: fails  
Docker 360 / JDBC 360: fails

I think the problem is due to the new version of the Docker image.

**Comment by ebyhr** [comment] 2021-08-01 02:54
I tested with a docker image and JDBC driver in Maven. Then, please share your actual code (GitHub url is fine).

**Comment by walter-weinmann** [comment] 2021-08-01 03:03
The whole DBSeeder project can be found [here](https://github.com/KonnexionsGmbH/db_seeder).

The AbstractJdbcSeeder class can be found [here](https://github.com/KonnexionsGmbH/db_seeder/blob/master/src/main/java/ch/konnexions/db_seeder/jdbc/AbstractJdbcSeeder.java).

**Comment by walter-weinmann** [comment] 2021-08-01 03:05
And here is the content of my `db_seeder_mysql.properties` file:

```
connector.name=mysql
case-insensitive-name-matching=true
connection-url=jdbc:mysql://db_seeder_db:3306/?serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false&rewriteBatchedStatements=true
connection-user=kxn_user
connection-password=mysql

```

**Comment by ebyhr** [comment] 2021-08-01 04:03
Additionally, please share the steps to reproduce with command level. I'm not familiar with your application.

**Comment by ebyhr** [comment] 2021-08-01 04:25
> I think the problem is due to the new version of the Docker image.

If the cause is Trino docker image, you should be able to reproduce without your app. I hope you provide "minimum" code so that we can debug quickly.

**Comment by walter-weinmann** [comment] 2021-08-01 06:11
Hi @ebyhr - below you will find a small programme that demonstrates the problem. It runs without errors with version 359 but fails with version 360. I have also added the two debug logs. I did use the Oracle connector and a Oracle database (19c).

[db_seeder_I8741_359.log](https://github.com/trinodb/trino/files/6912203/db_seeder_I8741_359.log)
[db_seeder_I8741_360.log](https://github.com/trinodb/trino/files/6912204/db_seeder_I8741_360.log)

```
package ch.konnexions.db_seeder.samples.trino;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Example program for Issues Oracle Connector.
 *
 * @author walter@konnexions.ch
 * @since 2020-10-22
 */
public final class I8741 {

  private static Connection   connection;
  private static final String connectionHost      = "localhost";
  private static final int    connectionPort      = 1521;

  private static final String driverOriginal      = "oracle.jdbc.driver.OracleDriver";
  private static final String driverTrino         = "io.trino.jdbc.TrinoDriver";

  private static final Logger logger              = LogManager.getLogger(I8741.class);

  private static final String password            = "oracle";

  private static final String service             = "orclpdb1";
  private static final String sqlStmntCreateTable = """
                                                    CREATE TABLE issue_table (
                                                        column_pk        NUMBER         NOT NULL
                                                    )
                                                    """;
  private static final String sqlStmntInsert      = "INSERT INTO issue_table (column_pk) VALUES (?)";
  private static Statement    statement;

  private static final String urlSys              = "jdbc:oracle:thin:@//" + connectionHost + ":" + connectionPort + "/" + service;
  private static final String userName            = "kxn_user";
  private static final String urlTrino            = "jdbc:trino://localhost:8080/db_seeder_oracle/" + userName + "?user=trino";

  private static final String urlUser             = "jdbc:oracle:thin:@//" + connectionHost + ":" + connectionPort + "/" + service;
  private static final String userNameSys         = "SYS AS SYSDBA";

  private static Connection connect(String url, String driver, String user, String password, boolean autoCommit) {
    logger.info("connecting ...");
    logger.info("driver    ='" + driver + "'");
    logger.info("url       ='" + url + "'");
    logger.info("user      ='" + user + "'");
    logger.info("password  ='" + password + "'");
    logger.info("autocommit='" + autoCommit + "'");

    try {
      Class.forName(driver);
    } catch (ClassNotFoundException e) {
      e.printStackTrace();
      System.exit(1);
    }

    Connection connection = null;

    try {
      if (user == null && password == null) {
        connection = DriverManager.getConnection(url);
      } else {
        connection = DriverManager.getConnection(url,
                                                 user,
                                                 password);
      }

      connection.setAutoCommit(autoCommit);
    } catch (SQLException e) {
      e.printStackTrace();
      System.exit(1);
    }

    logger.info("==========> now connected");

    return connection;
  }

  private static void demonstrateTrino() {
    logger.info("Run the demo with the trino JDBC driver ======================");

    connection = connect(urlTrino,
                         driverTrino,
                         null,
                         null,
                         true);

    insertData();

    disconnect(connection);
  }

  private static void disconnect(Connection connection) {
    logger.info("disconnecting ...");

    try {
      if (!(connection.getAutoCommit())) {
        logger.info("commiting ...");
        connection.commit();
      }

      connection.close();

    } catch (SQLException ec) {
      ec.printStackTrace();
      System.exit(1);
    }

    logger.info("==========> now disconnected");
  }

  private static void dropUser(String userName) {
    try {
      int    count    = 0;

      String sqlStmnt = "SELECT COUNT(*) FROM ALL_USERS WHERE username = '" + userName + "'";

      logger.info("next sqlStmnt='" + sqlStmnt + "'");

      ResultSet resultSet = statement.executeQuery(sqlStmnt);

      while (resultSet.next()) {
        count = resultSet.getInt(1);
      }

      resultSet.close();

      if (count > 0) {
        executeDdlStmnts("DROP USER " + userName + " CASCADE");
      }
    } catch (SQLException e) {
      e.printStackTrace();
      System.exit(1);
    }
  }

  private static void executeDdlStmnts(String firstDdlStmnt, String... remainingDdlStmnts) {
    try {
      logger.info("next sqlStmnt='" + firstDdlStmnt + "'");
      statement.execute(firstDdlStmnt);

      for (String sqlStmnt : remainingDdlStmnts) {
        logger.info("next sqlStmnt='" + sqlStmnt + "'");
        statement.execute(sqlStmnt);
      }
    } catch (SQLException e) {
      e.printStackTrace();
      System.exit(1);
    }
  }

  private static void insertData() {
    try {
      logger.info("next sqlStmnt='" + sqlStmntInsert + "'");
      PreparedStatement preparedStatement = connection.prepareStatement(sqlStmntInsert);

      preparedStatement.setLong(1,
                                1);

      if (preparedStatement.executeUpdate() != 1) {
        logger.fatal("Program abort: row not inserted");
      }

      preparedStatement.close();
    } catch (SQLException e) {
      e.printStackTrace();
      System.exit(1);
    }

  }

  /**
   * The main method.
   *
   * @param args the arguments
   */
  public static void main(String[] args) {
    logger.info("Start main() ==================================================");

    resetDatabase();
    setupDatabase();
    demonstrateTrino();

    logger.info("End   main() ==================================================");
  }

  private static void resetDatabase() {
    logger.info("Reset the database ============================================");

    connection = connect(urlSys,
                         driverOriginal,
                         userNameSys,
                         password,
                         false);

    try {
      statement = connection.createStatement();

      dropUser(userName.toUpperCase());

      statement.close();
    } catch (SQLException e) {
      e.printStackTrace();
      System.exit(1);
    }

    disconnect(connection);
  }

  private static void setupDatabase() {
    logger.info("Setup the database ============================================");

    connection = connect(urlSys,
                         driverOriginal,
                         userNameSys,
                         password,
                         false);

    try {
      statement = connection.createStatement();

      executeDdlStmnts("CREATE USER " + userName.toUpperCase() + " IDENTIFIED BY \"" + password + "\"",
                       "ALTER USER " + userName.toUpperCase() + " QUOTA UNLIMITED ON users",
                       "GRANT CREATE SEQUENCE TO " + userName.toUpperCase(),
                       "GRANT CREATE SESSION TO " + userName.toUpperCase(),
                       "GRANT CREATE TABLE TO " + userName.toUpperCase(),
                       "GRANT UNLIMITED TABLESPACE TO " + userName.toUpperCase());

      statement.close();
    } catch (SQLException e) {
      e.printStackTrace();
      System.exit(1);
    }

    disconnect(connection);

    connection = connect(urlUser,
                         driverOriginal,
                         userName.toUpperCase(),
                         password,
                         false);

    try {
      statement = connection.createStatement();

      executeDdlStmnts(sqlStmntCreateTable);

      statement.close();
    } catch (SQLException e) {
      e.printStackTrace();
      System.exit(1);
    }

    disconnect(connection);
  }
}


```

**Comment by ebyhr** [comment] 2021-08-01 13:05
The code works well in my environment. Could you make sure connection between JDBC driver and Trino server again (especially port biding)? What's the `docker ps` result?

**Comment by walter-weinmann** [comment] 2021-08-01 13:42
The fact is that in my environment, the Docker image from version 359 runs without problems, unlike the Docker image from version 360.

### Docker image version 359

```
D:\SoftDevelopment\Projects\db_seeder>docker ps
CONTAINER ID   IMAGE                       COMMAND                  CREATED         STATUS                   PORTS                                            NAMES
fabc9d63a43e   konnexionsgmbh/db_19_3_ee   "/bin/sh -c 'exec $O…"   2 minutes ago   Up 2 minutes (healthy)   0.0.0.0:1521->1521/tcp, 5500/tcp                 db_seeder_db
742dfd1d3d61   trinodb/trino:359           "/usr/lib/trino/bin/…"   3 minutes ago   Up 3 minutes             0.0.0.0:8080->8080/tcp                           db_seeder_trino
1f55bbdd95d5   portainer/portainer-ce      "/portainer"             8 days ago      Up 17 minutes            0.0.0.0:8000->8000/tcp, 0.0.0.0:9000->9000/tcp   portainer

D:\SoftDevelopment\Projects\db_seeder>docker ps -a
CONTAINER ID   IMAGE                       COMMAND                  CREATED         STATUS                   PORTS                                            NAMES
fabc9d63a43e   konnexionsgmbh/db_19_3_ee   "/bin/sh -c 'exec $O…"   2 minutes ago   Up 2 minutes (healthy)   0.0.0.0:1521->1521/tcp, 5500/tcp                 db_seeder_db
742dfd1d3d61   trinodb/trino:359           "/usr/lib/trino/bin/…"   3 minutes ago   Up 3 minutes             0.0.0.0:8080->8080/tcp                           db_seeder_trino
1f55bbdd95d5   portainer/portainer-ce      "/portainer"             8 days ago      Up 17 minutes            0.0.0.0:8000->8000/tcp, 0.0.0.0:9000->9000/tcp   portainer

```
### Docker image version 360

```
D:\SoftDevelopment\Projects\db_seeder>docker ps
CONTAINER ID   IMAGE                       COMMAND                  CREATED         STATUS                   PORTS                                            NAMES
86de08fdfd1f   konnexionsgmbh/db_19_3_ee   "/bin/sh -c 'exec $O…"   2 minutes ago   Up 2 minutes (healthy)   0.0.0.0:1521->1521/tcp, 5500/tcp                 db_seeder_db
1f55bbdd95d5   portainer/portainer-ce      "/portainer"             8 days ago      Up 12 minutes            0.0.0.0:8000->8000/tcp, 0.0.0.0:9000->9000/tcp   portainer

D:\SoftDevelopment\Projects\db_seeder>docker ps -a
CONTAINER ID   IMAGE                       COMMAND                  CREATED         STATUS                     PORTS                                            NAMES
86de08fdfd1f   konnexionsgmbh/db_19_3_ee   "/bin/sh -c 'exec $O…"   2 minutes ago   Up 2 minutes (healthy)     0.0.0.0:1521->1521/tcp, 5500/tcp                 db_seeder_db
0b19761b2d22   trinodb/trino:360           "/usr/lib/trino/bin/…"   2 minutes ago   Exited (1) 2 minutes ago                                                    db_seeder_trino
1f55bbdd95d5   portainer/portainer-ce      "/portainer"             8 days ago      Up 12 minutes              0.0.0.0:8000->8000/tcp, 0.0.0.0:9000->9000/tcp   portainer

```

**Comment by ebyhr** [comment] 2021-08-01 14:07
Why "Docker image version 360" doesn't have running trino docker container? What's the result of `docker logs 0b19761b2d22`?

**Comment by ebyhr** [comment] 2021-08-01 14:25
From Slack
```bash
D:\SoftDevelopment\Projects\db_seeder>docker logs 5dac59c694de
+ set +e
+ grep -s -q node.id /etc/trino/node.properties
+ NODE_ID_EXISTS=0
+ set -e
+ NODE_ID=
+ [[ 0 != 0 ]]
+ exec /usr/lib/trino/bin/launcher run --etc-dir /etc/trino
Aug 01, 2021 2:09:55 PM io.airlift.log.Logger info
INFO: Java version: 11.0.12
2021-08-01T14:09:55.448Z        INFO    main    io.airlift.log.Logging  Logging to stderr
2021-08-01T14:09:55.448Z        INFO    main    Bootstrap       Loading configuration
2021-08-01T14:09:55.523Z        INFO    main    Bootstrap       Initializing logging
2021-08-01T14:09:56.075Z        ERROR   main    io.trino.server.Server  Configuration is invalid
==========
Errors:
1) Configuration property 'http-server.https.port' was not used
Warnings:
1) Configuration property 'discovery-server.enabled' is deprecated and should not be used
==========
D:\SoftDevelopment\Projects\db_seeder>
```

**Comment by ebyhr** [comment] 2021-08-01 14:28
Let me close this issue because version 360's behavior is right.

**Closed by ebyhr** 2021-08-01 14:28 UTC
