### ISSUE TITLE
Is it necessary to implement `SHOW VIEWS` syntax?

### ISSUE THREAD

**Issue by polaris6** [trinodb/trino#12406] opened 2022-05-16 07:35 UTC
At present, Trino doesn't support the `SHOW VIEWS` syntax, which makes it inconvenient to distinguish between `table` and `view` in the `table list`. 
Currently , Spark and Flink support the `SHOW VIEWS` syntax:
https://spark.apache.org/docs/latest/sql-ref-syntax-aux-show-views.html
https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/sql/show/#show-views

Does Trino need to support the `SHOW VIEWS` syntax at present? If necessary, I am willing to do this.

**Comment by polaris6** [comment] 2022-05-16 07:35
cc @findepi @findinpath

**Comment by ebyhr** [comment] 2022-05-16 07:37
Let me close as duplicate of #2999.

**Closed by ebyhr** 2022-05-16 07:37 UTC
