### ISSUE TITLE
SHOW CURRENT ROLES fails

### ISSUE THREAD

**Issue by guyco33** [trinodb/trino#9485] opened 2021-10-04 10:06 UTC
Trino version is `362` 
Issue happens also when `deprecated.legacy-catalog-roles=true`
```
SHOW CURRENT ROLES

java.lang.IllegalStateException: undefined
	at com.google.common.base.Preconditions.checkState(Preconditions.java:494)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitValues(StatementAnalyzer.java:2425)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitValues(StatementAnalyzer.java:360)
	at io.trino.sql.tree.Values.accept(Values.java:55)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:377)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitAliasedRelation(StatementAnalyzer.java:1861)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitAliasedRelation(StatementAnalyzer.java:360)
	at io.trino.sql.tree.AliasedRelation.accept(AliasedRelation.java:71)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:377)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:3185)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1955)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:360)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:377)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:387)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1169)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:360)
	at io.trino.sql.tree.Query.accept(Query.java:107)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:377)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:340)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:91)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:269)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:190)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:806)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:132)
	at io.trino.$gen.Trino_362____20211002_071548_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Probably relates to https://github.com/trinodb/trino/pull/9087

**Comment by kokosing** [comment] 2021-10-04 10:38
It looks related to https://github.com/trinodb/trino/issues/9189, can you please try to use recent master and see if the issue is gone. It should be fixed now.

**Comment by guyco33** [comment] 2021-10-04 10:57
sure @kokosing.  Will check it shortly

**Comment by guyco33** [comment] 2021-10-04 11:49
@kokosing With recent master it doesn't fail but returns with empty result also when `deprecated.legacy-catalog-roles=true`.

**Comment by guyco33** [comment] 2021-10-04 12:17
I expect it to preserve the previous behavior and to implicitly pick the current catalog similar as `show schemas` and `show tables`

**Comment by kokosing** [comment] 2021-10-04 12:48
Let me take a look into this.

**Comment by kokosing** [comment] 2021-10-04 13:15
CC: @dain

**Comment by kokosing** [comment] 2021-10-04 13:38
Possible fix: https://github.com/trinodb/trino/pull/9491

**Comment by guyco33** [comment] 2021-10-04 15:42
I approved that #9491 fixes the issue

**Comment by kokosing** [comment] 2021-10-05 11:49
Fixed in 363.

**Comment by kokosing** [comment] 2021-10-05 11:50
@guyco33 Thank you for raising this issue and helping with tests for the bugfix.

**Closed by kokosing** 2021-10-05 11:49 UTC
Labels: bug
