### ISSUE TITLE
Missing columns for tables using TimescaleDB with Postgres connector

### ISSUE THREAD

**Issue by cemsbr** [trinodb/trino#14715] opened 2022-10-21 19:25 UTC
`show columns` doesn't show `sum(gross_amount) as gross_amount` in materialized view. All other columns can be seen, including `count(*) as quantity` of the same table and the `gross_amount` of the origin table.

If I connect directly to the database using the same user of the connector, it works as expected.

- Connector: postgresql
- Trino version: 400
- Database: timescaledb (continuous aggregate)

Materialized view (_materialized_hypertable_12):
```sql
SELECT time_bucket('1 day'::interval, my_table."time") AS day,
    ...
    sum(my_table.gross_amount) AS gross_amount,
    count(*) AS quantity,
    ...
   FROM my_table;
```

```sql
show columns from catalog.public.my_table;

...
gross_amount decimal(14,2)
...
```

```sql
show columns from catalog._timescaledb_internal._materialized_hypertable_12;

...
-- gross_amount is not here
quantity bigint
...
```

**Comment by cemsbr** [comment] 2022-10-26 22:03
I figured it out. The column type changed from `numeric(14, 2)` in the original table to just `numeric` in the materialized view. I recreated the materialized view casting the sum with `sum(gross_amount)::numeric(14, 2) as gross_amount` and now Trino can read the column.

Probably, the root cause is that there is no mapping for the PostgreSQL `numeric` data type (no size specification).

**Comment by ebyhr** [comment] 2022-10-27 04:44
Closing as not a bug. You can confirm the details at `io.trino.plugin.postgresql.PostgreSqlClient#toColumnMapping` > `Types.NUMERIC`.

**Closed by ebyhr** 2022-10-27 04:44 UTC
