### ISSUE TITLE
Trino hive transactions Invalid method name: 'alter_table_req'

### ISSUE THREAD

**Issue by qiaozhanwei** [trinodb/trino#11622] opened 2022-03-23 01:51 UTC
io.trino.spi.TrinoException: Invalid method name: 'alter_table_req'
  at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.updateTableWriteId(ThriftHiveMetastore.java:1894)
  at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.updateTableWriteId(BridgingHiveMetastore.java:524)
  at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.updateTableWriteId(CachingHiveMetastore.java:944)
  at io.trino.plugin.hive.HiveMetastoreClosure.updateTableWriteId(HiveMetastoreClosure.java:355)
  at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.updateTableWriteId(SemiTransactionalHiveMetastore.java:3673)
  at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore$Committer.prepareInsertExistingTable(SemiTransactionalHiveMetastore.java:1749)
  at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.commitShared(SemiTransactionalHiveMetastore.java:1438)
  at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:1225)
  at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.cleanupQuery(SemiTransactionalHiveMetastore.java:1375)
  at io.trino.plugin.hive.HiveMetadata.cleanupQuery(HiveMetadata.java:3399)
  at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.cleanupQuery(ClassLoaderSafeConnectorMetadata.java:470)
  at io.trino.metadata.MetadataManager$QueryCatalogs.finish(MetadataManager.java:2507)
  at io.trino.metadata.MetadataManager.cleanupQuery(MetadataManager.java:873)
  at io.trino.execution.QueryStateMachine.cleanupQuery(QueryStateMachine.java:948)
  at io.trino.execution.QueryStateMachine.transitionToFinishing(QueryStateMachine.java:838)
  at io.trino.execution.scheduler.SqlQueryScheduler$CoordinatorStagesScheduler.lambda$initialize$3(SqlQueryScheduler.java:949)
  at io.trino.execution.StateMachine.fireStateChangedListener(StateMachine.java:241)
  at io.trino.execution.StateMachine.lambda$fireStateChanged$0(StateMachine.java:233)
  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: org.apache.thrift.TApplicationException: Invalid method name: 'alter_table_req'
  at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
  at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
  at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_alter_table_req(ThriftHiveMetastore.java:2341)
  at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.alter_table_req(ThriftHiveMetastore.java:2328)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:567)
  at io.trino.plugin.base.util.LoggingInvocationHandler.handleInvocation(LoggingInvocationHandler.java:60)
  at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89)
  at com.sun.proxy.$Proxy266.alter_table_req(Unknown Source)
  at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient.alterTransactionalTable(ThriftHiveMetastoreClient.java:596)
  at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient.updateTableWriteId(ThriftHiveMetastoreClient.java:565)
  at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.lambda$updateTableWriteId$48(FailureAwareThriftMetastoreClient.java:426)
  at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.runWithHandle(FailureAwareThriftMetastoreClient.java:474)
  at io.trino.plugin.hive.metastore.thrift.FailureAwareThriftMetastoreClient.updateTableWriteId(FailureAwareThriftMetastoreClient.java:426)
  at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.lambda$updateTableWriteId$80(ThriftHiveMetastore.java:1888)
  at io.trino.plugin.hive.metastore.thrift.ThriftMetastoreApiStats.lambda$wrap$0(ThriftMetastoreApiStats.java:42)
  at io.trino.plugin.hive.util.RetryDriver.run(RetryDriver.java:130)
  at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.updateTableWriteId(ThriftHiveMetastore.java:1886)
  ... 23 more
  Suppressed: org.apache.thrift.TApplicationException: Invalid method name: 'alter_table_req'
    ... 43 more
  Suppressed: org.apache.thrift.TApplicationException: Invalid method name: 'alter_table_req'
    ... 43 more
  Suppressed: org.apache.thrift.TApplicationException: Invalid method name: 'alter_table_req'
    ... 43 more
  Suppressed: org.apache.thrift.TApplicationException: Invalid method name: 'alter_table_req'
    ... 43 more
  Suppressed: org.apache.thrift.TApplicationException: Invalid method name: 'alter_table_req'
    ... 43 more
  Suppressed: org.apache.thrift.TApplicationException: Invalid method name: 'alter_table_req'
    ... 43 more
  Suppressed: org.apache.thrift.TApplicationException: Invalid method name: 'alter_table_req'
    ... 43 more
  Suppressed: org.apache.thrift.TApplicationException: Invalid method name: 'alter_table_req'
    ... 43 more
  Suppressed: org.apache.thrift.TApplicationException: Invalid method name: 'alter_table_req'
    ... 43 more

2022-03-22T13:08:02.619+0800  ERROR transaction-finishing-0 io.trino.transaction.InMemoryTransactionManager Connector threw exception on abort
java.lang.IllegalStateException: Tried to rollback buffered metastore operations after transaction has been committed/aborted
  at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.rollback(SemiTransactionalHiveMetastore.java:1252)
  at io.trino.plugin.hive.HiveMetadata.rollback(HiveMetadata.java:3379)
  at io.trino.plugin.hive.HiveTransactionManager.lambda$rollback$1(HiveTransactionManager.java:70)
  at java.base/java.util.Optional.ifPresent(Optional.java:183)
  at io.trino.plugin.hive.HiveTransactionManager.rollback(HiveTransactionManager.java:68)
  at io.trino.plugin.hive.HiveConnector.rollback(HiveConnector.java:213)
  at io.trino.transaction.InMemoryTransactionManager$TransactionMetadata$ConnectorTransactionMetadata.abort(InMemoryTransactionManager.java:630)
  at io.trino.transaction.InMemoryTransactionManager$TransactionMetadata.safeAbort(InMemoryTransactionManager.java:545)
  at io.trino.transaction.InMemoryTransactionManager$TransactionMetadata.lambda$abortInternal$9(InMemoryTransactionManager.java:536)
  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
  at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131)
  at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
  at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82)
  at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:80)
  at io.trino.$gen.Trino_f322560_dirty____20220322_050548_2.run(Unknown Source)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:835)

**Comment by ebyhr** [comment] 2022-03-23 01:53
Is this duplicate of #7310?

**Comment by qiaozhanwei** [comment] 2022-03-23 02:06
> Is this duplicate of #7310?

yes , this pr https://github.com/trinodb/trino/pull/6180 is buf fix solution ?

**Comment by ebyhr** [comment] 2022-03-23 02:08
Thanks for your check. It should be the solution. Let me close this issue.

**Closed by ebyhr** 2022-03-23 02:08 UTC
