### ISSUE TITLE
Flaky test TestKafkaWithConfluentSchemaRegistryMinimalFunctionality testBasicTopic, testTopicWithKeySubject, etc

### ISSUE THREAD

**Issue by findepi** [trinodb/trino#6412] opened 2020-12-21 16:13 UTC

**Comment by findepi** [comment] 2020-12-21 16:13
https://github.com/prestosql/presto/runs/1588615014

```
2020-12-21T12:13:36.9829495Z [ERROR] Tests run: 240, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 630.32 s <<< FAILURE! - in TestSuite
2020-12-21T12:13:36.9833073Z [ERROR] testBasicTopic(io.prestosql.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality)  Time elapsed: 2.892 s  <<< FAILURE!
2020-12-21T12:13:36.9842543Z org.apache.kafka.common.errors.SerializationException: Error registering Avro schema: {"type":"record","name":"test_record","fields":[{"name":"col_1","type":"long"},{"name":"col_2","type":"string"}]}
2020-12-21T12:13:36.9849943Z Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Register operation timed out; error code: 50002
2020-12-21T12:13:36.9856930Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:279)
2020-12-21T12:13:36.9863535Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:338)
2020-12-21T12:13:36.9870080Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:438)
2020-12-21T12:13:36.9876677Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:430)
2020-12-21T12:13:36.9883916Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:416)
2020-12-21T12:13:36.9892896Z 	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.registerAndGetId(CachedSchemaRegistryClient.java:140)
2020-12-21T12:13:36.9902267Z 	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:196)
2020-12-21T12:13:36.9910784Z 	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:172)
2020-12-21T12:13:36.9919649Z 	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:72)
2020-12-21T12:13:36.9929112Z 	at io.confluent.kafka.serializers.KafkaAvroSerializer.serialize(KafkaAvroSerializer.java:53)
2020-12-21T12:13:36.9936061Z 	at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:62)
2020-12-21T12:13:36.9942163Z 	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:903)
2020-12-21T12:13:36.9947946Z 	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:865)
2020-12-21T12:13:36.9959870Z 	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:752)
2020-12-21T12:13:36.9961884Z 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
2020-12-21T12:13:36.9963619Z 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
2020-12-21T12:13:36.9969075Z 	at io.prestosql.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.sendMessages(TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java:234)
2020-12-21T12:13:37.0032655Z 	at io.prestosql.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.assertTopic(TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java:131)
2020-12-21T12:13:37.0042135Z 	at io.prestosql.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.testBasicTopic(TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java:80)
2020-12-21T12:13:37.0047916Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-12-21T12:13:37.0050506Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-12-21T12:13:37.0053352Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-12-21T12:13:37.0055701Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-12-21T12:13:37.0057840Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-12-21T12:13:37.0059884Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-12-21T12:13:37.0061406Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-12-21T12:13:37.0063069Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-12-21T12:13:37.0065099Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-12-21T12:13:37.0067145Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-12-21T12:13:37.0069288Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-12-21T12:13:37.0071360Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-12-21T12:13:37.0072698Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-12-21T12:13:37.0073184Z 
2020-12-21T12:13:37.0076691Z [ERROR] testTopicWithKeySubject(io.prestosql.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality)  Time elapsed: 1.872 s  <<< FAILURE!
2020-12-21T12:13:37.0081435Z org.apache.kafka.common.errors.SerializationException: Error registering Avro schema: "long"
2020-12-21T12:13:37.0084816Z Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Register schema operation failed while writing to the Kafka store; error code: 50001
2020-12-21T12:13:37.0089410Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:279)
2020-12-21T12:13:37.0092724Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:338)
2020-12-21T12:13:37.0096082Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:438)
2020-12-21T12:13:37.0099486Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:430)
2020-12-21T12:13:37.0102883Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:416)
2020-12-21T12:13:37.0106796Z 	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.registerAndGetId(CachedSchemaRegistryClient.java:140)
2020-12-21T12:13:37.0191265Z 	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:196)
2020-12-21T12:13:37.0194652Z 	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:172)
2020-12-21T12:13:37.0197910Z 	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:72)
2020-12-21T12:13:37.0200528Z 	at io.confluent.kafka.serializers.KafkaAvroSerializer.serialize(KafkaAvroSerializer.java:53)
2020-12-21T12:13:37.0202342Z 	at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:62)
2020-12-21T12:13:37.0203954Z 	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:895)
2020-12-21T12:13:37.0205494Z 	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:865)
2020-12-21T12:13:37.0207240Z 	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:752)
2020-12-21T12:13:37.0208613Z 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
2020-12-21T12:13:37.0209812Z 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
2020-12-21T12:13:37.0214131Z 	at io.prestosql.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.sendMessages(TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java:234)
2020-12-21T12:13:37.0223280Z 	at io.prestosql.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.assertTopic(TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java:131)
2020-12-21T12:13:37.0233174Z 	at io.prestosql.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.testTopicWithKeySubject(TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java:91)
2020-12-21T12:13:37.0239025Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-12-21T12:13:37.0241546Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-12-21T12:13:37.0244340Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-12-21T12:13:37.0246282Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-12-21T12:13:37.0248046Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-12-21T12:13:37.0249961Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-12-21T12:13:37.0251381Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-12-21T12:13:37.0252921Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-12-21T12:13:37.0254804Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-12-21T12:13:37.0256697Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-12-21T12:13:37.0258513Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-12-21T12:13:37.0260430Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-12-21T12:13:37.0261667Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-12-21T12:13:37.0262116Z 
2020-12-21T12:13:37.0265216Z [ERROR] testTopicWithRecordNameStrategy(io.prestosql.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality)  Time elapsed: 2.916 s  <<< FAILURE!
2020-12-21T12:13:37.0289148Z org.apache.kafka.common.errors.SerializationException: Error registering Avro schema: "long"
2020-12-21T12:13:37.0292052Z Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Register schema operation failed while writing to the Kafka store; error code: 50001
2020-12-21T12:13:37.0295559Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:279)
2020-12-21T12:13:37.0307209Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:338)
2020-12-21T12:13:37.0310617Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:438)
2020-12-21T12:13:37.0314034Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:430)
2020-12-21T12:13:37.0386787Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:416)
2020-12-21T12:13:37.0391162Z 	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.registerAndGetId(CachedSchemaRegistryClient.java:140)
2020-12-21T12:13:37.0395697Z 	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:196)
2020-12-21T12:13:37.0399809Z 	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:172)
2020-12-21T12:13:37.0403668Z 	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:72)
2020-12-21T12:13:37.0406371Z 	at io.confluent.kafka.serializers.KafkaAvroSerializer.serialize(KafkaAvroSerializer.java:53)
2020-12-21T12:13:37.0408634Z 	at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:62)
2020-12-21T12:13:37.0410783Z 	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:895)
2020-12-21T12:13:37.0412835Z 	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:865)
2020-12-21T12:13:37.0415160Z 	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:752)
2020-12-21T12:13:37.0417108Z 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
2020-12-21T12:13:37.0418830Z 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
2020-12-21T12:13:37.0424304Z 	at io.prestosql.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.sendMessages(TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java:234)
2020-12-21T12:13:37.0433494Z 	at io.prestosql.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.assertTopic(TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java:131)
2020-12-21T12:13:37.0443661Z 	at io.prestosql.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.testTopicWithRecordNameStrategy(TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java:102)
2020-12-21T12:13:37.0449999Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-12-21T12:13:37.0452320Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-12-21T12:13:37.0454943Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-12-21T12:13:37.0456887Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-12-21T12:13:37.0458854Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-12-21T12:13:37.0460971Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-12-21T12:13:37.0462385Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-12-21T12:13:37.0463929Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-12-21T12:13:37.0468951Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-12-21T12:13:37.0471127Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-12-21T12:13:37.0495415Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-12-21T12:13:37.0497833Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-12-21T12:13:37.0499203Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-12-21T12:13:37.0499691Z 
2020-12-21T12:13:37.0503338Z [ERROR] testTopicWithTopicRecordNameStrategy(io.prestosql.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality)  Time elapsed: 3.048 s  <<< FAILURE!
2020-12-21T12:13:37.0507906Z org.apache.kafka.common.errors.SerializationException: Error registering Avro schema: "long"
2020-12-21T12:13:37.0511054Z Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Register schema operation failed while writing to the Kafka store; error code: 50001
2020-12-21T12:13:37.0514855Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:279)
2020-12-21T12:13:37.0518179Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:338)
2020-12-21T12:13:37.0521473Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:438)
2020-12-21T12:13:37.0524860Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:430)
2020-12-21T12:13:37.0528254Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:416)
2020-12-21T12:13:37.0532360Z 	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.registerAndGetId(CachedSchemaRegistryClient.java:140)
2020-12-21T12:13:37.0536944Z 	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:196)
2020-12-21T12:13:37.0540793Z 	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:172)
2020-12-21T12:13:37.0544636Z 	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:72)
2020-12-21T12:13:37.0547897Z 	at io.confluent.kafka.serializers.KafkaAvroSerializer.serialize(KafkaAvroSerializer.java:53)
2020-12-21T12:13:37.0550310Z 	at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:62)
2020-12-21T12:13:37.0552449Z 	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:895)
2020-12-21T12:13:37.0554665Z 	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:865)
2020-12-21T12:13:37.0556666Z 	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:752)
2020-12-21T12:13:37.0558581Z 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
2020-12-21T12:13:37.0560410Z 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
2020-12-21T12:13:37.0572289Z 	at io.prestosql.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.sendMessages(TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java:234)
2020-12-21T12:13:37.0581517Z 	at io.prestosql.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.assertTopic(TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java:131)
2020-12-21T12:13:37.0591548Z 	at io.prestosql.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.testTopicWithTopicRecordNameStrategy(TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java:115)
2020-12-21T12:13:37.0598819Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-12-21T12:13:37.0601215Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-12-21T12:13:37.0604056Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-12-21T12:13:37.0606140Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-12-21T12:13:37.0608040Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-12-21T12:13:37.0610079Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-12-21T12:13:37.0611623Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-12-21T12:13:37.0613275Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-12-21T12:13:37.0615502Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-12-21T12:13:37.0617542Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-12-21T12:13:37.0619507Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-12-21T12:13:37.0621565Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-12-21T12:13:37.0623060Z 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-12-21T12:13:37.0623537Z 
2020-12-21T12:13:37.4773349Z [INFO] 
2020-12-21T12:13:37.4773962Z [INFO] Results:
2020-12-21T12:13:37.4774407Z [INFO] 
2020-12-21T12:13:37.4774845Z [ERROR] Failures: 
2020-12-21T12:13:37.4778510Z [ERROR]   TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.testBasicTopic » Serialization
2020-12-21T12:13:37.4794067Z [ERROR]   TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.testTopicWithKeySubject » Serialization
2020-12-21T12:13:37.4799918Z [ERROR]   TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.testTopicWithRecordNameStrategy » Serialization
2020-12-21T12:13:37.4806185Z [ERROR]   TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.testTopicWithTopicRecordNameStrategy » Serialization
2020-12-21T12:13:37.4810317Z [INFO] 
2020-12-21T12:13:37.4810903Z [ERROR] Tests run: 240, Failures: 4, Errors: 0, Skipped: 0
```

cc @elonazoulay @kokosing

**Comment by findepi** [comment] 2020-12-22 21:49
https://github.com/prestosql/presto/runs/1595876042 

```
2020-12-22T17:12:43.9134387Z [ERROR] Tests run: 241, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 568.631 s <<< FAILURE! - in TestSuite
2020-12-22T17:12:43.9141766Z [ERROR] testUnsupportedInsert(io.prestosql.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality)  Time elapsed: 3.035 s  <<< FAILURE!
2020-12-22T17:12:43.9148051Z org.apache.kafka.common.errors.SerializationException: Error registering Avro schema: "long"
2020-12-22T17:12:43.9161293Z Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Register operation timed out; error code: 50002
2020-12-22T17:12:43.9167318Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:292)
2020-12-22T17:12:43.9172835Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:352)
2020-12-22T17:12:43.9178549Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:495)
2020-12-22T17:12:43.9184978Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:486)
2020-12-22T17:12:43.9191410Z 	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:459)
2020-12-22T17:12:43.9199093Z 	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.registerAndGetId(CachedSchemaRegistryClient.java:206)
2020-12-22T17:12:43.9207644Z 	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:268)
2020-12-22T17:12:43.9222382Z 	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:244)
2020-12-22T17:12:43.9226935Z 	at io.confluent.kafka.serializers.AbstractKafkaAvroSerializer.serializeImpl(AbstractKafkaAvroSerializer.java:75)
2020-12-22T17:12:43.9230856Z 	at io.confluent.kafka.serializers.KafkaAvroSerializer.serialize(KafkaAvroSerializer.java:59)
2020-12-22T17:12:43.9234212Z 	at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:62)
2020-12-22T17:12:43.9237091Z 	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:895)
2020-12-22T17:12:43.9265741Z 	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:865)
2020-12-22T17:12:43.9267703Z 	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:752)
2020-12-22T17:12:43.9269422Z 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
2020-12-22T17:12:43.9272329Z 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
2020-12-22T17:12:43.9277338Z 	at io.prestosql.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.sendMessages(TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java:250)
2020-12-22T17:12:43.9288470Z 	at io.prestosql.plugin.kafka.schema.confluent.TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.testUnsupportedInsert(TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java:133)
2020-12-22T17:12:43.9296310Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-12-22T17:12:43.9298695Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-12-22T17:12:43.9301914Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-12-22T17:12:43.9304078Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-12-22T17:12:43.9305986Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2020-12-22T17:12:43.9307986Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2020-12-22T17:12:43.9309804Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2020-12-22T17:12:43.9311464Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2020-12-22T17:12:43.9313464Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2020-12-22T17:12:43.9315443Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2020-12-22T17:12:43.9317347Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-12-22T17:12:43.9319171Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-12-22T17:12:43.9320537Z 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by findepi** [comment] 2020-12-27 20:30
https://github.com/prestosql/presto/runs/1608321716

**Comment by kokosing** [comment] 2020-12-27 20:38
Trying to address this with: https://github.com/prestosql/presto/pull/6444

**Comment by findepi** [comment] 2020-12-29 23:30
https://github.com/trinodb/trino/runs/1623444881

**Comment by hashhar** [comment] 2020-12-30 10:06
https://github.com/trinodb/trino/pull/6475/checks?check_run_id=1625441008

**Comment by findepi** [comment] 2021-01-04 20:15
https://github.com/trinodb/trino/runs/1644781366

**Comment by ebyhr** [comment] 2021-01-05 08:14
https://github.com/trinodb/trino/runs/1648257949

**Comment by findepi** [comment] 2021-01-05 08:18
i know @kokosing is trying to fix this. Should this be annotated with `@Flaky` in the interim?

**Comment by kokosing** [comment] 2021-01-05 13:16
> Should this be annotated with @Flaky in the interim?

I end up with marking as flaky: https://github.com/trinodb/trino/pull/6504 😞

**Comment by kokosing** [comment] 2021-01-21 09:39
The issue is about testing infra not being setup data (create a schema in schema registry). So it is not related to Trino code.

**Closed by kokosing** 2021-01-21 09:39 UTC
Labels: bug
