### ISSUE TITLE
Trino Windows Build

### ISSUE THREAD

**Issue by dipsitevikas** [trinodb/trino#10769] opened 2022-01-24 18:31 UTC
Is it not possible to build Trino on windows ? As I see mac OS and Linux only in build requirements ?

**Comment by dipsitevikas** [comment] 2022-01-24 18:36
Cc: @sauliusvl @martint

**Comment by ebyhr** [comment] 2022-01-25 00:07
Closing as duplicate of #2272. Please feel free to join our community Slack https://trino.io/slack.html

**Closed by ebyhr** 2022-01-25 00:07 UTC

**Comment by mosabua** [comment] 2022-01-25 05:48
You can probably build Trino with WSL2. Its worth trying
