### ISSUE TITLE
MySQL connector prints NPE during SELECT

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#443] opened 2019-03-11 12:36 UTC
It happens when I executed a simple SELECT query to mysql on presto-product-tests. The returned result is fine, but NPE message is printed in the server log. 
```sql
presto:sys> select * from mysql.sys.version;
 sys_version | mysql_version 
-------------+---------------
 1.5.1       | 5.7.25        
```
Even if the schema isn't sys, the same message appears.

```sh
2019-03-11T18:14:16.377+0545	INFO	Query-20190311_122916_00007_esdqa-167	stderr	Mon Mar 11 18:14:16 NPT 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2019-03-11T18:14:16.428+0545	INFO	Query-20190311_122916_00007_esdqa-167	stderr	Mon Mar 11 18:14:16 NPT 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2019-03-11T18:14:16.474+0545	INFO	Query-20190311_122916_00007_esdqa-167	stderr	Mon Mar 11 18:14:16 NPT 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2019-03-11T18:14:16.547+0545	INFO	Query-20190311_122916_00007_esdqa-172	stderr	Mon Mar 11 18:14:16 NPT 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2019-03-11T18:14:16.619+0545	INFO	20190311_122916_00007_esdqa.1.0-0-108	stderr	Mon Mar 11 18:14:16 NPT 2019 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
2019-03-11T18:14:16.679+0545	ERROR	20190311_122916_00007_esdqa.1.0-0-108	io.prestosql.operator.Driver	Error closing operator 0 for task 20190311_122916_00007_esdqa.1.0
java.lang.NullPointerException
	at com.mysql.jdbc.MysqlIO.clearInputStream(MysqlIO.java:901)
	at com.mysql.jdbc.RowDataDynamic.close(RowDataDynamic.java:172)
	at com.mysql.jdbc.ResultSetImpl.realClose(ResultSetImpl.java:6676)
	at com.mysql.jdbc.ResultSetImpl.close(ResultSetImpl.java:851)
	at io.prestosql.plugin.jdbc.JdbcRecordCursor.close(JdbcRecordCursor.java:219)
	at io.prestosql.spi.connector.RecordPageSource.close(RecordPageSource.java:76)
	at io.prestosql.operator.TableScanOperator.finish(TableScanOperator.java:185)
	at io.prestosql.operator.TableScanOperator.close(TableScanOperator.java:174)
	at io.prestosql.operator.Driver.closeAndDestroyOperators(Driver.java:546)
	at io.prestosql.operator.Driver.processInternal(Driver.java:406)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at io.prestosql.$gen.Presto_null__testversion____20190311_122423_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


2019-03-11T18:14:16.717+0545	INFO	query-execution-2	io.prestosql.event.QueryMonitor	TIMELINE: Query 20190311_122916_00007_esdqa :: Transaction:[e4d7f31b-7737-4c6e-a529-4b1710170547] :: elapsed 337ms :: planning 65ms :: scheduling 174ms :: running 81ms :: finishing 17ms :: begin 2019-03-11T18:14:16.371+05:45 :: end 2019-03-11T18:14:16.708+05:45
```

**Comment by findepi** [comment] 2019-03-11 14:41
Quoting @electrum's old comment from https://github.com/prestodb/presto/issues/10644

> This seems to be a bug in the MySQL JDBC driver. It happens on close, after the data has been read, so it doesn't actually harm anything (other than printing a log message). We could try updating the JDBC driver to see if they fixed the bug already.

**Comment by ebyhr** [comment] 2019-03-11 14:49
Thank you for the information. I'll check with newer mysql drivers.

**Comment by sopel39** [comment] 2019-03-13 15:09
The exception only logged and does not cause queries to fail because of `io.prestosql.operator.Driver#addSuppressedException` during operator close/destroy.

**Comment by sopel39** [comment] 2019-03-13 15:13
This should be fixed as it happens during tests too.

**Comment by electrum** [comment] 2019-03-15 00:00
I'm thinking we should have the JDBC connectors suppress logging for errors on close. I noticed that the recently added `testInsertIntoNotNullColumn` for MySQL and PostgreSQL both spew log messages because the driver implicitly closes on error and than throws on explicit close (which seems contrary to the specification).

**Comment by hashhar** [comment] 2021-06-23 18:38
Closing as cannot be reproduced after https://github.com/trinodb/trino/commit/01670f3ffc4ba8535fabfaddac853e4b451fe91b.

Fixed by the driver upgrade as suspected.

**Closed by hashhar** 2021-06-23 18:38 UTC
Labels: bug

**Comment by findepi** [comment] 2021-06-24 11:39
🎉  thanks @hashhar for taking time to check that.
