### ISSUE TITLE
Use HMS store metadata should not be share the schemas

### ISSUE THREAD

**Issue by zhaoyim** [trinodb/trino#11867] opened 2022-04-08 07:53 UTC
![image](https://user-images.githubusercontent.com/12442769/162380705-92db7f4d-77a9-45b4-adc8-2c7e6cb4cfe8.png)

when create schema in iceberg, I only can see the schema in iceberg catalog.  hive schemas only shown in the hive catalog, now  the hive schemas and iceberg schemas show up the same, because we already have catalogs which should use as a domain.

now I think there are 2 option to fix the issue, one use the HMS table DBS CTLG_NAME column, another way is use the DATABASE_PARAMS table. 

could anyone can confirm whether this is an issue? Thanks! if this is an issue, please assign this issue to me, I will try to fix.

**Comment by findepi** [comment] 2022-04-08 08:48
The fact that schemas are shared is expected, as designed.
A schema can hold both Hive and Iceberg tables (or Detla tables FWIW).
These can be supported at the same time with use of table redirections, to deliver seamless user experience.

Closing because it "works as intended".
cc @findinpath for redirections

**Closed by findepi** 2022-04-08 08:48 UTC

**Comment by zhaoyim** [comment] 2022-04-08 09:10
Thanks for clarify!
