### ISSUE TITLE
How to Use UNNEST For Arrays Of Arrays in BigQuery connector

### ISSUE THREAD

**Issue by Asturias-sam** [trinodb/trino#3884] opened 2020-05-29 20:06 UTC
I am running below query in Presto:
```
SELECT location.zone
FROM table 
CROSS JOIN UNNEST(items) as t(item,  quantity, location);

```
I am getting the following error:

Presto error: Unhandled type for Block:

```
array(row("item" row("departmentNumber" bigint,"itemNumber" bigint,"shelfCapacity" row("qty" double,"precision" bigint)),

 "quantity" row("qty" double,"precision" bigint),

 "location" row("zone" varchar,"aisle" bigint)))
```
As you can see for item is having an array shelfCapacity inside it, how to unnest this type of array where you have array inside array ?

**Comment by martint** [comment] 2020-05-29 21:14
Can you paste the complete stacktrace and the schema of your table?

**Comment by som2014** [comment] 2020-05-30 02:33
@martint  On Presto Cli on just getting the able error using the above query.
I used this command show columns from table; 
below is items description 

```
items 
 array(row(item   row(departmentNumber bigint, itemNumber bigint, shelfCapacity row(qty double, precision   bigint, uom varchar)), quantity row(qty double, precision bigint), location row(zone varchar, aisle bigint)))
```
-- | --

**Comment by som2014** [comment] 2020-05-30 03:07
@martint i have updated the stack trace but this query run fine in big query:

```
select 
item_detail.location.zone, 
count(*)
FROM table 
CROSS JOIN UNNEST(items) as item_detail
group by 1;
```

**Comment by martint** [comment] 2020-05-30 03:13
Thanks. That appears to be a bug in the BigQuery connector. 

@davidrabinowitz, is this something you can look into?

**Comment by davidrabinowitz** [comment] 2020-05-30 04:27
@som2014 Can you please add the schema of the BigQuery table?

**Comment by som2014** [comment] 2020-05-30 04:34
Below is the details:

```
Field name | Type | Mode | Policy tags | Description

        items | RECORD | REPEATED|  |
```

**Comment by som2014** [comment] 2020-06-01 06:10
@davidrabinowitz  is this a bug  any work around ?

**Comment by ebyhr** [comment] 2020-06-01 07:17
@som2014 Can you share the simple steps to reproduce? e.g. CREATE TABLE and INSERT statement

I sent an invitation for the community Slack so that we can talk quickly: https://prestosql.io/slack.html

**Comment by davidrabinowitz** [comment] 2020-06-01 15:16
@som2014 I'm checking this out. Will update when I have more details.

**Comment by davidrabinowitz** [comment] 2020-06-01 22:36
Hi @som2014 I'm afraid I cannot reproduce the issue. Based on the schema you have given I've created the following table:
```
Field name                         Type    Mode     Policy tags  Description
items                              RECORD  REPEATED 
items.item                         RECORD  REQUIRED 
items.item.itemNumber              INTEGER NULLABLE 
items.item.shelfCapacity           RECORD  NULLABLE 
items.item.shelfCapacity.qty       FLOAT   REQUIRED 
items.item.shelfCapacity.precision INTEGER REQUIRED 
items.item.shelfCapacity.uom       STRING  REQUIRED 
items.quantity                     RECORD  NULLABLE 
items.quantity.qty                 FLOAT   REQUIRED 
items.quantity.precision           INTEGER REQUIRED 
items.location                     RECORD  NULLABLE 
items.location.zone                STRING  NULLABLE 
items.location.aisle               INTEGER NULLABLE 
```
I've added couple of record to it and ran a simple select *:
```
                                                                                                                                   items                                                                                                                                    
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 [{item={itemNumber=3, shelfCapacity={qty=13.0, precision=3, uom=idk}}, quantity={qty=13.0, precision=3}, location={zone=c, aisle=3}}, {item={itemNumber=4, shelfCapacity={qty=14.0, precision=4, uom=rdk}}, quantity={qty=14.0, precision=4}, location={zone=d, aisle=4}}] 
 [{item={itemNumber=1, shelfCapacity={qty=10.0, precision=2, uom=idk}}, quantity={qty=10.0, precision=2}, location={zone=a, aisle=1}}, {item={itemNumber=2, shelfCapacity={qty=11.0, precision=3, uom=rdk}}, quantity={qty=11.0, precision=3}, location={zone=b, aisle=2}}] 
(2 rows)
```

I then ran your query, 
```
SELECT location.zone
FROM table 
CROSS JOIN UNNEST(items) as t(item,  quantity, location);
```
and got this result:
```
 zone 
------
 a    
 b    
 c    
 d    
(4 rows)
```

BTW, please note that this schema does not contain an array of arrays, but an array of structs, containing other structs. Can you provide more details? Which Presto version are you using? Is it possible to generate sample data that reproduces the problem?

**Comment by som2014** [comment] 2020-06-02 04:24
Current Presto Version : 333

Sample Data which i am getting the above error : 
```
[[[1, "SR GUMMI BEARS BAG", 567280059, 567280059, null, "00634418523778", 58766565, null], [8.0, 0, "EACH"], ["A", 8, 11, null]]]
[[[1, "M MS PB SUP 9.6OZ", 562868534, 562868534, null, "00040000513018", 39336973, null], [42.0, 0, "EACH"], ["A", 3, 1, null]]]
```

**Comment by davidrabinowitz** [comment] 2020-06-02 05:23
Thanks for that. It seems that the schema is a bit different, for example `location` has 4 fields rather than 2 . Can you please send the full schema so I can test this?

**Comment by som2014** [comment] 2020-06-02 05:44
@davidrabinowitz  sorry for that i thought the problem was having nested structure inside the structure so i simplify the schema , will share it soon.

**Comment by som2014** [comment] 2020-06-02 06:45
Below is schema :

items | RECORD | REPEATED |   |  
-- | -- | -- | -- | --
items. item | RECORD | REQUIRED |   |  
items.item. departmentNumber | INTEGER | NULLABLE |   |  
items.item. description | STRING | NULLABLE |   |  
items.item. itemNumber | INTEGER | NULLABLE |   |  
items.item. primeItemNumber | INTEGER | NULLABLE |   |  
items.item. gtin | STRING | NULLABLE |   |  
items.item. primeGtin | STRING | NULLABLE |   |  
items.item. replenishmentGroupNumber | INTEGER | NULLABLE |   |  
items.item. shelfCapacity | RECORD | NULLABLE |   |  
items.item.shelfCapacity. qty | FLOAT | REQUIRED |   | 
items.item.shelfCapacity. precision | INTEGER | REQUIRED |   | 
items.item.shelfCapacity. uom | STRING | REQUIRED |   |
items. quantity | RECORD | NULLABLE |   |  
items.quantity. qty | FLOAT | REQUIRED |   | 
items.quantity. precision | INTEGER | REQUIRED |   |
items.quantity. uom | STRING | REQUIRED |   | 
items. location | RECORD | NULLABLE |   |  
items.location. zone | STRING | NULLABLE |   |  
items.location. aisle | INTEGER | NULLABLE |   |  
items.location. section | INTEGER | NULLABLE |   |  
items.location. sgln | STRING | NULLABLE |   |

**Comment by davidrabinowitz** [comment] 2020-06-02 21:34
I've taken ran Prestosql 333 with a table using your data. Unfortunately I couldn'r reproduce this bug:
```
> select * from p3884a;
                                                                                                                                                                  items                                                                                                                                                                   
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 [{item={departmentNumber=91, description=VOILA FS FAJITA CHKN, itemNumber=554268888, primeItemNumber=554268888, gtin=NULL, primeGtin=00014500015136, replenishmentGroupNumber=14185212, shelfCapacity={qty=8.0, precision=0, uom=EACH}}, quantity={qty=8.0, precision=0, uom=EACH}, location={zone=A, aisle=6, section=5, sgln=NULL}}]   
 [{item={departmentNumber=95, description=GSHR MEGA PAK 20CT, itemNumber=573338692, primeItemNumber=573338692, gtin=NULL, primeGtin=00016000147096, replenishmentGroupNumber=15688504, shelfCapacity={qty=10.0, precision=0, uom=EACH}}, quantity={qty=10.0, precision=0, uom=EACH}, location={zone=A, aisle=22, section=12, sgln=NULL}}] 
(2 rows)
```
And the second query:
```
> SELECT location.zone FROM p3884a CROSS JOIN UNNEST(items) as t(item,  quantity, location);
 zone 
------
 A    
 A    
(2 rows)
```

@martint any idea on how to proceed?

**Comment by martint** [comment] 2020-06-05 21:08
@davidrabinowitz, from the stacktrace, the flow would fall through to that case if the type is ArrayType but the value is not a List:

>         if (type instanceof ArrayType && value instanceof List<?>) {

Under what conditions would that happen? Are we reading the wrong column?

**Comment by davidrabinowitz** [comment] 2020-06-08 17:23
Perhaps - as mentioned I was not able to reproduce this issue locally. If you can debug this query and copy the state of the PageSource - which type is it, what is the value - type and contents. Any other variables may help as well.

**Comment by ebyhr** [comment] 2022-09-28 03:42
Let me close this issue as we can't reproduce it. This might be temporary issue in BigQuery side. Please feel free to reopen or file a new issue if you still face the issue.

**Closed by ebyhr** 2022-09-28 03:42 UTC
Labels: bug
