### ISSUE TITLE
iceberg: write split offset to help file splitting

### ISSUE THREAD

**Issue by yittg** [trinodb/trino#14994] opened 2022-11-11 03:39 UTC
Iceberg can split table scan files into parts. Basically it will use a fixed value to split the file into size equaled parts, which can not match the expected bound of internal parts (e.g. row groups of parquet). Corresponding to Trino split, some split will scan two parts and some will scan nothing.

Also iceberg can split a file based on advised offsets if provided. Think we can write the advised split offsets along with other metadata.

WDYT @findepi @ebyhr

**Comment by ebyhr** [comment] 2022-11-11 06:06
Closing as duplicate of #9018. Let's continue there.

**Closed by ebyhr** 2022-11-11 06:06 UTC
