### ISSUE TITLE
Trino stuck on queries after cancelling a query 

### ISSUE THREAD

**Issue by netanelm-upstream** [trinodb/trino#20307] opened 2024-01-09 10:06 UTC
We saw a lot warnings inside the workers:
```
024-01-09T10:00:19.649Z WARN 20240109_100018_00189_48wy3.1.0.0-13-53 com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageReadChannel Failed read retry #1/10 for '<reducted_path>/7bb70d43-f294-4485-b0df-aba17a1c9750.orc'. Sleeping...
java.nio.channels.ClosedByInterruptException
 at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
 at java.base/java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:389)
 at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageReadChannel.read(GoogleCloudStorageReadChannel.java:315)
 at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFSInputStream.read(GoogleHadoopFSInputStream.java:171)
 at java.base/java.io.DataInputStream.read(DataInputStream.java:151)
 at java.base/java.io.DataInputStream.read(DataInputStream.java:151)
 at io.trino.hdfs.FSDataInputStreamTail.readTail(FSDataInputStreamTail.java:59)
 at io.trino.filesystem.hdfs.HdfsInput.readTail(HdfsInput.java:63)
 at io.trino.filesystem.TrinoInput.readTail(TrinoInput.java:43)
 at io.trino.filesystem.tracing.TracingInput.lambda$readTail$3(TracingInput.java:81)
 at io.trino.filesystem.tracing.Tracing.withTracing(Tracing.java:47)
 at io.trino.filesystem.tracing.TracingInput.readTail(TracingInput.java:81)
 at io.trino.plugin.iceberg.TrinoOrcDataSource.readTailInternal(TrinoOrcDataSource.java:54)
 at io.trino.orc.AbstractOrcDataSource.readTail(AbstractOrcDataSource.java:95)
 at io.trino.orc.OrcReader.wrapWithCacheIfTiny(OrcReader.java:326)
 at io.trino.orc.OrcReader.createOrcReader(OrcReader.java:104)
 at io.trino.orc.OrcReader.createOrcReader(OrcReader.java:95)
 at io.trino.plugin.iceberg.IcebergPageSourceProvider.createOrcPageSource(IcebergPageSourceProvider.java:662)
 at io.trino.plugin.iceberg.IcebergPageSourceProvider.createDataPageSource(IcebergPageSourceProvider.java:555)
 at io.trino.plugin.iceberg.IcebergPageSourceProvider.createPageSource(IcebergPageSourceProvider.java:364)
 at io.trino.plugin.iceberg.IcebergPageSourceProvider.createPageSource(IcebergPageSourceProvider.java:263)
 at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:48)
 at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:61)
 at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:259)
 at io.trino.operator.ScanFilterAndProjectOperator$SplitToPages.process(ScanFilterAndProjectOperator.java:190)
 at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:359)
 at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
 at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:346)
 at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
 at io.trino.operator.WorkProcessorUtils$3.process(WorkProcessorUtils.java:346)
 at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
 at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
 at io.trino.operator.WorkProcessorUtils.lambda$processStateMonitor$2(WorkProcessorUtils.java:240)
 at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
 at io.trino.operator.WorkProcessorUtils.getNextState(WorkProcessorUtils.java:261)
 at io.trino.operator.WorkProcessorUtils.lambda$finishWhen$3(WorkProcessorUtils.java:255)
 at io.trino.operator.WorkProcessorUtils$ProcessWorkProcessor.process(WorkProcessorUtils.java:412)
 at io.trino.operator.WorkProcessorSourceOperatorAdapter.getOutput(WorkProcessorSourceOperatorAdapter.java:132)
 at io.trino.operator.Driver.processInternal(Driver.java:395)
 at io.trino.operator.Driver.lambda$process$8(Driver.java:298)
 at io.trino.operator.Driver.tryWithLock(Driver.java:694)
 at io.trino.operator.Driver.process(Driver.java:290)
 at io.trino.operator.Driver.processForDuration(Driver.java:261)
 at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:887)
 at io.trino.execution.executor.timesharing.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
 at io.trino.execution.executor.timesharing.TimeSharingTaskExecutor$TaskRunner.run(TimeSharingTaskExecutor.java:565)
 at io.trino.$gen.Trino_434____20240109_090617_2.run(Unknown Source)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 at java.base/java.lang.Thread.run(Thread.java:840)
```
Issue resolved temporary after restarting the workers, but when someone will cancel a query it will happen again.

After downgrading to 434 issue resolved.
When creating the same scenario on Trino with Azure no issue is seen, but we reproduce it only on GCP.

Version: 435
Connector: iceberg + jdbc catalog

Also discussed in this channel:
https://trinodb.slack.com/archives/CGB0QHWSW/p1703152556411549

**Comment by florianMalbranque** [comment] 2024-02-08 10:33
Similar issue on my side, 

Trino version: 438
Cloud: GCP
Env: GKE
Trino version: 437
Connector: Iceberg

 downgrade to 434 fixes it

**Comment by hashhar** [comment] 2024-02-09 07:22
cc: @elonazoulay @electrum

**Comment by hashhar** [comment] 2024-02-09 07:29
Can you check if setting `gcs.client.max-retries` to `0` reduces the rate of these?
Seems like some other part of code is interrupting the GCS threads between retries.
Might be related to https://github.com/trinodb/trino/pull/20003

**Comment by florianMalbranque** [comment] 2024-02-09 08:08
I am using GCS in S3 API compatibility mode, setting  `hive.s3.max-client-retries=0` in either Iceberg catalog or properties
result in 
`Configuration property 'gcs.client.max-retries' was not used`
Setting 
```
    hive.s3.max-client-retries=0
    hive.s3.max-error-retries=0
```
does not fix the issue either as those parameters are not used by gcs client

**Comment by amir-upstream** [comment] 2024-03-14 09:16
@hashhar  Hey,
We are also experiencing this issue,
Cloud: GCP
Trino version: Happens in version >= 435 
Connector: iceberg

Any leads on resolving this ?

**Comment by hashhar** [comment] 2024-03-14 12:26
@florianMalbranque Do you have `fs.native-gcs.enabled` set to true? Those configs apply to the native impl only.

cc: @wendigo https://github.com/trinodb/trino/pull/20056
cc: @elonazoulay https://github.com/trinodb/trino/pull/20003

**Comment by wendigo** [comment] 2024-03-14 12:48
Can you try with Trino 440?

**Comment by florianMalbranque** [comment] 2024-03-14 13:00
@hashhar @wendigo, I upgraded our Trino installation to 440 and move away from legacy fs to `fs.native-gcs`, The issue appears to be fixed

**Comment by wendigo** [comment] 2024-03-14 13:04
Nice to hear @florianMalbranque !

**Comment by Max-Cheng** [comment] 2024-11-04 06:18
For users using version 435: reverting the commit `95b01b678edcd6ecec009e96bfd24baba04c8b68` will fix this problem.
Similar upstream problem: https://github.com/GoogleCloudDataproc/hadoop-connectors/issues/1180

**Comment by hashhar** [comment] 2024-11-20 11:08
Closing since it's fixed with native client (hence current versions are not affected) and for older versions (even though un-supported) the cause has been identified.

**Closed by hashhar** 2024-11-20 11:08 UTC
