### ISSUE TITLE
EXPLAIN ANALYZE and EXPLAIN ANALYZE VERBOSE do not show estimates

### ISSUE THREAD

**Issue by joshthoward** [trinodb/trino#9356] opened 2021-09-23 19:47 UTC
In Trino version 361 `EXPLAIN ANALYZE` and `EXPLAIN ANALYZE VERBOSE` do not show estimates which were previously displayed in Trino version 358. 

To reproduce run, `EXPLAIN ANALYZE SELECT * FROM tpch.tiny.lineitem;` and `EXPLAIN ANALYZE VERBOSE SELECT * FROM tpch.tiny.lineitem;` on 358 and 361 version.

**Comment by findepi** [comment] 2021-09-23 19:54
cc @sopel39

**Comment by kyo-tom** [comment] 2021-09-26 12:58
can you assign me to this issue ? I will try to solve this problem

**Comment by kyo-tom** [comment] 2021-09-27 04:27
I found that the cause of the problem is that explain analyze statement will be parsed as ExplainAnalyze in version 361,but it will be parsed as Explain before 360.This change will make collectPlanStatistics from true to false in LogicalPlanner

**Comment by kyo-tom** [comment] 2021-09-27 05:53
> I found that the cause of the problem is that explain analyze statement will be parsed as ExplainAnalyze in version 361,but it will be parsed as Explain before 360.This change will make collectPlanStatistics from true to false in LogicalPlanner

can i submit a pr to fix it？

**Comment by findepi** [comment] 2021-09-27 07:43
@kyo-tom absolutely!

**Comment by sopel39** [comment] 2021-09-28 06:51
Fixed via: https://github.com/trinodb/trino/pull/9396

**Closed by sopel39** 2021-09-28 06:51 UTC
Labels: bug
