### ISSUE TITLE
Credential leakage when using kafka connector with schema registry

### ISSUE THREAD

**Issue by derbeneviv** [trinodb/trino#22679] opened 2024-07-16 08:03 UTC
we have a kafka connector with schema registry.  
this schema registry is protected by auth.

According to documentation https://trino.io/docs/current/connector/kafka.html#confluent-table-description-supplier, currently trino doesn't support auth for registry in any other way other then passing credentials in connection string
```
  connector.name=kafka
  kafka.table-description-supplier=CONFLUENT
  kafka.confluent-schema-registry-url=https://${ENV:KAFKA_SCHEMA_REGISTRY_USER}:${ENV:KAFKA_SCHEMA_REGISTRY_PASS}@${ENV:KAFKA_SCHEMA_REGISTRY_URL}
  kafka.hide-internal-columns=false
  kafka.nodes=kfk01:9092,kfk02:9092,kfk03:9092
  kafka.config.resources=/etc/trino/kafka-configuration.properties
  ```

however, if we pass those creds in this way, we can see them in bootstrap log:
```
2024-07-16T07:55:43.303Z        INFO    main    Bootstrap       kafka.timestamp-upper-bound-force-push-down-enabled  false    false                                                                                                                                                      timestamp upper bound force pushing down enabled
2024-07-16T07:55:43.303Z        INFO    main    Bootstrap       kafka.security-protocol                              ----     ----                                                                                                                                                       Kafka communication security protocol
2024-07-16T07:55:43.303Z        INFO    main    Bootstrap       kafka.protobuf-any-support-enabled                   false    false                                                                                                                                                      True to enable supporting encoding google.protobuf.Any types as JSON
2024-07-16T07:55:43.303Z        INFO    main    Bootstrap       kafka.confluent-schema-registry-client-cache-size    1000     1000                                                                                                                                                       The maximum number of subjects that can be stored in the Confluent Schema Registry client cache
*****!!!!!HERE!!!!!!****** ----->
2024-07-16T07:55:43.303Z        INFO    main    Bootstrap       kafka.confluent-schema-registry-url                  ----     [[https://<plaintext_user>:<plaintext_pass>@<registry_url>]]  The url of the Confluent Schema Registry
2024-07-16T07:55:43.303Z        INFO    main    Bootstrap       kafka.confluent-subjects-cache-refresh-interval      1.00s    1.00s                                                                                                                                                      The interval that the topic to subjects cache will be refreshed
2024-07-16T07:55:43.303Z        INFO    main    Bootstrap       kafka.empty-field-strategy                           IGNORE   IGNORE
```

**Comment by ebyhr** [comment] 2024-07-16 10:05
We should add dedicated config properties for user & password auth. Let me close as a duplicate of #12195

**Closed by ebyhr** 2024-07-16 10:05 UTC
