### ISSUE TITLE
Flaky io.trino.execution.resourcegroups.db.TestQueuesDb.testSelectorPriority()

### ISSUE THREAD

**Issue by wendigo** [trinodb/trino#11850] opened 2022-04-07 14:29 UTC
```
Didn't finish within the time-out 60000
```

**Comment by findepi** [comment] 2022-04-08 09:17
@wendigo is it reproducible locally?
in the CI logs (do you have a link?), did you see anything unusual?

**Comment by wendigo** [comment] 2022-04-08 10:53
@findepi nothing unusal in the logs. just a timeout exception

**Comment by findepi** [comment] 2024-02-02 15:31
internal run:

```
[INFO] 
Error:  Failures: 
Error:    TestQueuesDb.testSelectorPriority:272 
expected: QUERY_QUEUE_FULL:131074
 but was: GENERIC_INTERNAL_ERROR:65536
[INFO] 
Error:  Tests run: 3427, Failures: 1, Errors: 0, Skipped: 145
```

**Comment by findepi** [comment] 2024-02-02 16:06
reproduced the above with `@RepeatedTest(100)` on the `testSelectorPriority`

logs involve `Server is shutting down` and `BoundedExecutor is in a failed state`. investigating

**Comment by findepi** [comment] 2024-02-02 16:33
after modifying the test to show the failure i got this

```
Suppressed: java.lang.IllegalStateException: Query not registered: 20240202_162622_00107_xg34p
		at io.trino.metadata.LanguageFunctionManager.getQueryFunctions(LanguageFunctionManager.java:140)
		at io.trino.metadata.LanguageFunctionManager.getFunctions(LanguageFunctionManager.java:155)
		at io.trino.metadata.MetadataManager.getFunctions(MetadataManager.java:2509)
		at io.trino.metadata.MetadataManager.lambda$getFunctions$66(MetadataManager.java:2477)
		at java.base/java.util.Optional.map(Optional.java:260)
		at io.trino.metadata.MetadataManager.getFunctions(MetadataManager.java:2477)
		at io.trino.tracing.TracingMetadata.getFunctions(TracingMetadata.java:1236)
		at io.trino.metadata.FunctionResolver.isFunctionKind(FunctionResolver.java:111)
		at io.trino.metadata.FunctionResolver.isAggregationFunction(FunctionResolver.java:95)
		at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:1232)
		at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:624)
		at io.trino.sql.tree.FunctionCall.accept(FunctionCall.java:121)
		at io.trino.sql.tree.StackableAstVisitor.process(StackableAstVisitor.java:27)
		at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:647)
		at io.trino.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:492)
		at io.trino.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:3512)
		at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeExpression(StatementAnalyzer.java:5037)
		at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelectSingleColumn(StatementAnalyzer.java:4840)
		at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelect(StatementAnalyzer.java:4615)
```

can there be any race around `LanguageFunctionManager`?

**Comment by findepi** [comment] 2024-02-02 16:54
created https://github.com/trinodb/trino/issues/20551 for this new fail mode 
closing this one. the original problem (`Didn't finish within the time-out 60000`) seems to be infrequent so much that no-one will work on this just because the issue exists

**Closed by findepi** 2024-02-02 16:54 UTC
Labels: bug
