### ISSUE TITLE
When you add a new machine and find that the new node has not been fully started successfully, the Connectors receive requests

### ISSUE THREAD

**Issue by duhanmin** [trinodb/trino#18843] opened 2023-08-29 08:38 UTC
```
Caused by: java.sql.SQLException: Query failed (#20230829_083524_00390_us4yp): Unexpected response from http://*****:8889/v1/task/20230829_083524_00390_us4yp.1.1?summarize
	at io.trino.jdbc.AbstractTrinoResultSet.resultsException(AbstractTrinoResultSet.java:1937)
	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:295)
	at io.trino.jdbc.TrinoResultSet$ResultsPageIterator.computeNext(TrinoResultSet.java:255)
	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at io.trino.jdbc.$internal.guava.collect.AbstractIterator.hasNext(AbstractIterato
```

**Comment by ebyhr** [comment] 2023-08-29 08:39
Closing as duplicate of #5190

**Closed by ebyhr** 2023-08-29 08:39 UTC

**Comment by duhanmin** [comment] 2023-08-30 10:07
@ebyhr  I've found a fix
pr will be submitted soon
