### ISSUE TITLE
Iceberg `write.parquet.compression-codec` being set even if file-format is not parquet

### ISSUE THREAD

**Issue by oneonestar** [trinodb/trino#20401] opened 2024-01-17 08:21 UTC
In Trino 436 (Iceberg 1.4.3), `write.parquet.compression-codec` property is also being set even if the file-format is not parquet. This doesn't happen in Trino 428 (Iceberg 1.3.1), not sure about Trino 431 to Trino 435 (Iceberg 1.4.1)
Is this an intended behavior?

```
trino> CREATE TABLE test.property_test (c1 integer) WITH (format = 'ORC');
CREATE TABLE
trino> SELECT * FROM test."property_test$properties";
               key               | value
---------------------------------+-------
 write.format.default            | ORC
 write.parquet.compression-codec | zstd
(2 rows)

trino> CREATE TABLE test.property_test (c1 integer) WITH (format = 'AVRO');
CREATE TABLE
trino> SELECT * FROM test."property_test$properties";
               key               | value
---------------------------------+-------
 write.format.default            | AVRO
 write.parquet.compression-codec | zstd
(2 rows)
```

Ref:
https://github.com/apache/iceberg/pull/8593#issuecomment-1740507634
https://github.com/trinodb/trino/pull/19434/files#diff-f5cd96d1ec33fae497df9613afcefff034f01c99adf961e927ccd76e637c7b81R4707

**Comment by ebyhr** [comment] 2024-11-28 06:34
This is not a bug of Trino Iceberg connector. It should be fixed in Iceberg library though they probably won't fix it, though. https://github.com/apache/iceberg/pull/9503#issuecomment-1919889634

**Closed by ebyhr** 2024-11-28 06:34 UTC
Labels: bug, iceberg
