### ISSUE TITLE
Fix json_array_get() function

### ISSUE THREAD

**Issue by oneonestar** [trinodb/trino#2573] opened 2020-01-22 01:49 UTC
According to the [documentation](https://prestosql.io/docs/current/functions/json.html), `json_array_get()` is broken:
> The semantics of this function are broken. If the extracted element is a string, it will be converted into an invalid JSON value that is not properly quoted (the value will not be surrounded by quotes and any interior quotes will not be escaped).
> We recommend against using this function. It cannot be fixed without impacting existing usages and may be removed in a future release.

We could fix the behavior of the existing functions, or create better functions to replace them.

Related to: https://github.com/prestosql/presto/pull/2446#discussion_r369233354

**Comment by hashhar** [comment] 2024-09-03 19:45
Now with SQL 2023 JSON functions we have better alternatives which are unaffected. Closing.

Feel free to reopen if still relevant.

**Closed by hashhar** 2024-09-03 19:45 UTC

**Comment by alex-baransky** [comment] 2025-05-17 20:44
@hashhar looking for an alternative to json_array_get() where I can extract a json value by index. What functions in SQL 2023 are you referring to? Or is there correct syntax to refer to element position like '$.[0].[1]'? I'm having trouble with this type of syntax, thanks!

**Comment by martint** [comment] 2025-05-17 21:26
You can use `json_query`. For instance:

```sql
SELECT json_query('["a", "b", "c"]', 'strict $[1]');
```

which outputs:

```
 _col0
-------
 "b"
(1 row)
```

See https://trino.io/docs/current/functions/json.html#json-query

**Comment by alex-baransky** [comment] 2025-05-19 19:37
Hm doesn't seem to be working for me, getting NULL for the value I'm trying to extract.

I have a JSON that looks like this:
`{
      "stringA":
      {
         "key1": 1,
         "key2": 2,
         "key3": 3
      }
}`

The key "stringA" can also have names "stringB" or "stringC." I want to be able to extract the values from the nested array which has consistent key names, regardless of what the outer key name is.

My syntax is `json_query(json_col, 'strict $[0].key1')`, but this is always returning NULL. I've tried [1] and [-1] but nothing is returning anything for me. Do you see anything wrong with this syntax? Thanks so much for your help!

**Comment by hashhar** [comment] 2025-05-21 09:38
You don't have an array so `$[0]` won't work. You have a JSON object.

This should have worked but I can't get `json_query` to accept parameters. You'll notice however that `json_exsts` is working correctly.

```sql
trino> select * from memory.default.test;
                      json_col                      |   key
----------------------------------------------------+---------
 { "stringB": { "key1": 1, "key2": 2, "key3": 3 } } | key1
 { "stringB": { "key1": 1, "key2": 2, "key3": 3 } } | stringB
 { "stringA": { "key1": 1, "key2": 2, "key3": 3 } } | stringA
(3 rows)

trino> SELECT json_query(json_col, 'strict $[$keyname]' PASSING "key" AS "keyname"), key, json_exists(json_col, 'lax $.keyvalue()?(@.name == $KeyName).value' PASSING "key" AS "KeyName") FROM memory.default.test;
 _col0 |   key   | _col2
-------+---------+-------
 NULL  | stringB | true
 NULL  | key1    | false
 NULL  | stringA | true
(3 rows)
```

**Comment by hashhar** [comment] 2025-05-21 09:38
cc: @kasiafi Possibly a bug in json-path parsing.

```
trino> SELECT json_query(json_col, 'strict $.$keyname' PASSING "key" AS "keyname"), key, json_exists(json_col, 'lax $.keyvalue()?(@.name == $KeyName).value' PASSING "key" AS "KeyName") FROM memory.default.test;
Query 20250521_093648_00037_52x6d failed: line 1:39: no viable alternative at input '.$keyname'
io.trino.sql.parser.ParsingException: line 1:39: no viable alternative at input '.$keyname'
	at io.trino.sql.jsonpath.PathParser$1.syntaxError(PathParser.java:60)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)
	at io.trino.grammar.jsonpath.JsonPathParser.accessorExpression(JsonPathParser.java:1081)
	at io.trino.grammar.jsonpath.JsonPathParser.pathExpression(JsonPathParser.java:331)
	at io.trino.grammar.jsonpath.JsonPathParser.path(JsonPathParser.java:154)
	at io.trino.sql.jsonpath.PathParser.parseJsonPath(PathParser.java:112)
	at io.trino.sql.analyzer.JsonPathAnalyzer.analyzeJsonPath(JsonPathAnalyzer.java:109)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.analyzeJsonPathInvocation(ExpressionAnalyzer.java:2975)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitJsonQuery(ExpressionAnalyzer.java:2793)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.visitJsonQuery(ExpressionAnalyzer.java:646)
	at io.trino.sql.tree.JsonQuery.accept(JsonQuery.java:136)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.ExpressionAnalyzer$Visitor.process(ExpressionAnalyzer.java:676)
	at io.trino.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:497)
	at io.trino.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:3635)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeExpression(StatementAnalyzer.java:5157)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelectSingleColumn(StatementAnalyzer.java:4960)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.analyzeSelect(StatementAnalyzer.java:4735)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:3093)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:524)
	at io.trino.sql.tree.QuerySpecification.accept(QuerySpecification.java:155)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:543)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:551)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:1554)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:524)
	at io.trino.sql.tree.Query.accept(Query.java:130)
	at io.trino.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.trino.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:543)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:503)
	at io.trino.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:492)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:98)
	at io.trino.sql.analyzer.Analyzer.analyze(Analyzer.java:87)
	at io.trino.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:285)
	at io.trino.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:218)
	at io.trino.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:884)
	at io.trino.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:158)
	at io.trino.$gen.Trino_475____20250521_092131_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:128)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:74)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:80)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
	at java.base/java.lang.Thread.run(Thread.java:1447)
Caused by: org.antlr.v4.runtime.NoViableAltException
	at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2014)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:445)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:371)
	at io.trino.grammar.jsonpath.JsonPathParser.accessorExpression(JsonPathParser.java:811)
	... 41 more
```

**Comment by kasiafi** [comment] 2025-05-23 14:34
@hashhar it is not a bug. Per spec, the member accessor can be only an identifier or a string literal, and this is reflected in the grammar.

In `json_exists` the parameter works because you use it in a different context: `@.name == $KeyName`
