### ISSUE TITLE
Flaky TestClickHouseTypeMapping.testUnsupportedDate[2149-06-07](2)

### ISSUE THREAD

**Issue by gaurav8297** [trinodb/trino#15504] opened 2022-12-22 10:56 UTC
Pr: https://github.com/trinodb/trino/pull/15459
Github action: https://github.com/trinodb/trino/actions/runs/3735266296/jobs/6338808932

I ran it locally and it's running fine so it could be flaky

```
Error:  io.trino.plugin.clickhouse.TestClickHouseTypeMapping.testUnsupportedDate[2149-06-07](2)  Time elapsed: 0.561 s  <<< FAILURE!
java.lang.AssertionError: Expected query to fail: INSERT INTO test_unsupported_date3v8iz2u71h VALUES (DATE '2149-06-07')
	at org.testng.Assert.fail(Assert.java:94)
	at io.trino.testing.QueryAssertions.assertQueryFails(QueryAssertions.java:291)
	at io.trino.testing.AbstractTestQueryFramework.assertQueryFails(AbstractTestQueryFramework.java:400)
	at io.trino.plugin.clickhouse.BaseClickHouseTypeMapping.testUnsupportedDate(BaseClickHouseTypeMapping.java:664)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
cc @hashhar

**Comment by hashhar** [comment] 2022-12-22 12:36
I can't reproduce locally at all, there's actually a runtime validation in the code to disallow such date so I'm not sure how the insert is possible (which is even more worrying) - I'll take a look.

This could be a possible correctness issue since these values get written incorrectly to ClickHouse. Thanks for pointing this out @gaurav8297.

Just FYI @tangjiangling.

**Comment by hashhar** [comment] 2022-12-23 08:46
I'm unable to reproduce this at all and don't see any way this could be triggered unless the type mapping being constructed was wrong somehow.

I'm closing for now but please re-open if you see this ever again.

**Closed by hashhar** 2022-12-23 08:46 UTC
