### ISSUE TITLE
Creating schema complains 'Session catalog must be set' even if I specify catalog in query

### ISSUE THREAD

**Issue by ppalucha** [trinodb/trino#8816] opened 2021-08-06 10:53 UTC
Query:
```
CREATE SCHEMA IF NOT EXISTS hive.my_table WITH (location = 's3://my_bucket/my_data');
```
Expected result: schema created
Actual result: error "Session catalog must be set"
Works fine if catalog is set, e.g. using `--catalog` argument to CLI.

Tested on version: 359

**Comment by ppalucha** [comment] 2021-08-06 11:01
Stack trace:
```
Query 20210806_110042_00957_uhfzg failed: line 1:1: Session catalog must be set
io.trino.spi.TrinoException: line 1:1: Session catalog must be set
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:48)
	at io.trino.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:43)
	at io.trino.metadata.MetadataUtil.lambda$getSessionCatalog$2(MetadataUtil.java:106)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at io.trino.metadata.MetadataUtil.getSessionCatalog(MetadataUtil.java:105)
	at io.trino.execution.CreateSchemaTask.getCreatePrincipal(CreateSchemaTask.java:121)
	at io.trino.execution.CreateSchemaTask.internalExecute(CreateSchemaTask.java:103)
	at io.trino.execution.CreateSchemaTask.execute(CreateSchemaTask.java:72)
	at io.trino.execution.CreateSchemaTask.execute(CreateSchemaTask.java:47)
	at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:170)
	at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:237)
	at io.trino.dispatcher.LocalDispatchQuery.lambda$startExecution$7(LocalDispatchQuery.java:143)
	at io.trino.$gen.Trino_359_e____20210806_082423_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by ebyhr** [comment] 2021-08-06 11:12
I couldn't reproduce it with upstream and 359. I guess you are using Starburst distribution (359-e). 
Can you reproduce with the latest version?

**Comment by hashhar** [comment] 2021-08-06 11:32
@ebyhr The code path can be hit if there is a principal attached to the statement which I guess is the case when some authentication is enabled or maybe an explicit username is passed to Trino? See https://github.com/trinodb/trino/pull/8818

**Comment by hashhar** [comment] 2022-02-01 10:51
Fixed by https://github.com/trinodb/trino/commit/3cb2db9dc2b7de23f7c3d83a12dbefb859601bda (Trino 362).

@ppalucha if you are still running into this feel free to re-open.

**Closed by hashhar** 2022-02-01 10:51 UTC
Labels: bug
