### ISSUE TITLE
any plan to support coorinator cluster and multiple discovery.uri 

### ISSUE THREAD

**Issue by mjzfrank** [trinodb/trino#12368] opened 2022-05-13 02:13 UTC
I want to use trino as a jdbc data source , but the coorinator and discovery is single, didn't support HA.I think this part is very importantimportment.
Is there any plan to support it?

**Comment by ebyhr** [comment] 2022-05-13 02:15
Let me close as duplicate of #391. Please feel free to continue there.

**Closed by ebyhr** 2022-05-13 02:15 UTC
