### ISSUE TITLE
Catalog 'clickhouse' does not support table property 'order_by'

### ISSUE THREAD

**Issue by yunfeng79** [trinodb/trino#8331] opened 2021-06-21 08:50 UTC
CREATE TABLE clickhouse.trino_ck (
  id int NOT NULL,
  birthday DATE,
  name VARCHAR,
  age BIGINT,
  logdate DATE
)
WITH (
  engine = 'MergeTree',
  order_by = 'id, birthday',
  partition_by = 'toYYYYMM(logdate)'
);
Error occurred during SQL query execution

mgessage：
 SQL error [18]: Query failed (#20210621_084958_00952_tm6aw): Catalog 'clickhouse' does not support table property 'order_by'

**Comment by hashhar** [comment] 2021-06-21 08:52
This was a mistake in the docs... please try `order_by = ARRAY['id', 'birthday']`

cc: @mosabua this was fixed in https://github.com/trinodb/trino/commit/ea01a506a7a969b45fe32642e0a1f3516fe2cac5.

In case you still run into issues feel free to reopen or join our [Slack](https://trino.io/slack.html) and continue the conversation there.

**Closed by hashhar** 2021-06-21 08:52 UTC

**Comment by yunfeng79** [comment] 2021-06-21 09:25
use DBeaver  (trino)

SQL:
CREATE TABLE clickhouse.trino_ck (
  id int NOT NULL,
  birthday DATE,
  name VARCHAR,
  age BIGINT,
  logdate DATE
)
WITH (
  engine ='MergeTree',
  order_by = ARRAY['id', 'birthday'],
  partition_by ='toYYYYMM(logdate)'
);

@hashhar 
SQL error [18]: Query failed (#20210621_090128_00971_tm6aw): Catalog 'clickhouse' does not support table property 'order_by'
  Query failed (#20210621_090128_00971_tm6aw): Catalog 'clickhouse' does not support table property 'order_by'
  Query failed (#20210621_090128_00971_tm6aw): Catalog 'clickhouse' does not support table property 'order_by'
    io.trino.spi.TrinoException: Catalog 'clickhouse' does not support table property 'order_by'
    Catalog 'dongxin_clickhouse' does not support table property 'order_by'

**Comment by hashhar** [comment] 2021-06-21 10:15
@yunfeng79 This works for me:

```sql
CREATE TABLE clickhouse.default.trino_ck (
	id int NOT NULL,
	birthday DATE NOT NULL,
	name VARCHAR,
	age BIGINT,
	logdate DATE NOT NULL
)
WITH (
	engine ='MergeTree',
	order_by = ARRAY['id', 'birthday'],
	partition_by = ARRAY['toYYYYMM(logdate)']
);
```

**Comment by yunfeng79** [comment] 2021-06-21 10:27
@hashhar SQL 错误 [18]: Query failed (#20210621_102626_01092_tm6aw): Catalog 'clickhouse' does not support table property 'order_by'
  Query failed (#20210621_102626_01092_tm6aw): Catalog 'clickhouse' does not support table property 'order_by'
  Query failed (#20210621_102626_01092_tm6aw): Catalog 'clickhouse' does not support table property 'order_by'
    io.trino.spi.TrinoException: Catalog 'dongxin_clickhouse' does not support table property 'order_by'
    Catalog 'clickhouse' does not support table property 'order_by'

**Comment by hashhar** [comment] 2021-06-21 13:26
Table properties for ClickHouse are supported since Trino 355. What version are you using?

Also can you please run the CLI using `--debug` and share the full stack-trace. It'll make it easier to see the root cause.

**Comment by yunfeng79** [comment] 2021-06-21 13:30
using Trino 353,thank you!

**Comment by yunfeng79** [comment] 2021-06-22 02:08
@hashhar use Trino 358 not support ReplicatedMergeTree ?
SQL 错误 [18]: Query failed (#20210622_020836_00028_zsu72): Invalid value for table property 'engine': Cannot convert [ARRAY[ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/v_event_1399686391344009216_bak1', '{replica}')]] to varchar
  Query failed (#20210622_020836_00028_zsu72): Invalid value for table property 'engine': Cannot convert [ARRAY[ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/v_event_1399686391344009216_bak1', '{replica}')]] to varchar
  Query failed (#20210622_020836_00028_zsu72): Invalid value for table property 'engine': Cannot convert [ARRAY[ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/v_event_1399686391344009216_bak1', '{replica}')]] to varchar
    io.trino.spi.TrinoException: Invalid value for table property 'engine': Cannot convert [ARRAY[ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/v_event_1399686391344009216_bak1', '{replica}')]] to varchar
    Invalid value for table property 'engine': Cannot convert [ARRAY[ReplicatedMergeTree('/clickhouse/tables/{layer}-{shard}/v_event_1399686391344009216_bak1', '{replica}')]] to varchar
      io.trino.spi.TrinoException: line 9:18: Function 'replicatedmergetree' not registered
      line 9:18: Function 'replicatedmergetree' not registered
        io.trino.spi.TrinoException: Function 'replicatedmergetree' not registered
        Function 'replicatedmergetree' not registered

**Comment by hashhar** [comment] 2021-06-22 05:05
From the documentation https://trino.io/docs/current/connector/clickhouse.html

> Currently the connector only supports Log and MergeTree table engines in create table statement. ReplicatedMergeTree engine is not yet supported.
