### ISSUE TITLE
Can't create table partitioned on ROW type's inner field

### ISSUE THREAD

**Issue by rituraj-AU** [trinodb/trino#19282] opened 2023-10-05 19:17 UTC
Query:
```
create table person(address ROW(city VARCHAR)) with (partitioning=ARRAY['address.city']);
```

Error:
```
Query failed: Unable to parse partitioning value: Invalid partition field declaration: address.city
```

I also tried with `partitioning=ARRAY['city']` and `partitioning=ARRAY['address'.'city']`

**Comment by ebyhr** [comment] 2023-10-05 23:51
Closing as duplicate of #15109

**Closed by ebyhr** 2023-10-05 23:51 UTC
