### ISSUE TITLE
Impossible to use SASL_SSL in Kafka event listener

### ISSUE THREAD

**Issue by paragor** [trinodb/trino#24381] opened 2024-12-05 08:27 UTC
Kafka event listener tells that configuration for kafka client should be defined in `kafka-event-listener.client-config-overrides` as key=value separated by comma.
But if value contains `=`, bootsrap of coordinator fails. Param 'sasl.jaas.config' always contains `=`. Example of value:
```
org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin";
```

So it is not possible to send events to kafka with SASL_SSL.

Kafka event listener [documentation](https://trino.io/docs/current/admin/event-listeners-kafka.html#configuration) states that the configuration for the Kafka client should be defined in `kafka-event-listener.client-config-overrides` as key=value pairs separated by commas. However, if a value contains the `=` character, the coordinator's bootstrap process fails. 
For example, the parameter sasl.jaas.config always contains `=`, as shown below:
```
org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin";
```
As a result, it is impossible to send events to Kafka using SASL_SSL.

Error message:
```
io.airlift.bootstrap.ApplicationConfigurationException: Configuration errors:

1) Error: Error invoking configuration method [public KafkaEventListenerConfig KafkaEventListenerConfig.setKafkaClientOverrides(String)]

1 error

======================
Full classname legend:
======================
KafkaEventListenerConfig: "io.trino.plugin.eventlistener.kafka.KafkaEventListenerConfig"
========================
End of classname legend:
========================

	at io.airlift.bootstrap.Bootstrap.configure(Bootstrap.java:240)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:269)
	at io.trino.plugin.eventlistener.kafka.KafkaEventListenerFactory.create(KafkaEventListenerFactory.java:55)
	at io.trino.eventlistener.EventListenerManager.createEventListener(EventListenerManager.java:132)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:5075)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:5083)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:727)
	at io.trino.eventlistener.EventListenerManager.configuredEventListeners(EventListenerManager.java:115)
	at io.trino.eventlistener.EventListenerManager.loadEventListeners(EventListenerManager.java:100)
	at io.trino.server.Server.doStart(Server.java:185)
	at io.trino.server.Server.lambda$start$0(Server.java:94)
	at io.trino.$gen.Trino_466____20241205_062731_1.run(Unknown Source)
	at io.trino.server.Server.start(Server.java:94)
	at io.trino.server.TrinoServer.main(TrinoServer.java:37)
Caused by: java.lang.IllegalArgumentException: Chunk [sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="password";] is not a valid entry
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218)
	at com.google.common.base.Splitter$MapSplitter.split(Splitter.java:527)
	at io.trino.plugin.eventlistener.kafka.KafkaEventListenerConfig.setKafkaClientOverrides(KafkaEventListenerConfig.java:189)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.airlift.configuration.ConfigurationFactory.setConfigProperty(ConfigurationFactory.java:484)
	at io.airlift.configuration.ConfigurationFactory.build(ConfigurationFactory.java:390)
	at io.airlift.configuration.ConfigurationFactory.build(ConfigurationFactory.java:336)
	at io.airlift.configuration.ConfigurationProvider.get(ConfigurationProvider.java:66)
	at io.airlift.configuration.ConfigurationFactory.validateRegisteredConfigurationProvider(ConfigurationFactory.java:249)
	at io.airlift.bootstrap.Bootstrap.configure(Bootstrap.java:228)
	... 18 more

```

configuration of kafka-event-listener:
```
    event-listener.name=kafka
    kafka-event-listener.broker-endpoints=broker.kafka:9092
    kafka-event-listener.client-config-overrides=security.protocol=SASL_SSL,sasl.mechanism=PLAIN,ssl.truststore.location=/etc/trino/kafka.truststore.pem,ssl.truststore.type=PEM,sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin";
    kafka-event-listener.client-id=trino-trino
    kafka-event-listener.completed-event.topic=analytics.trino.completed_events
    kafka-event-listener.created-event.topic=analytics.trino.created_events
    kafka-event-listener.terminate-on-initialization-failure=false
```

**Comment by wendigo** [comment] 2024-12-05 17:39
Did you try providing config through the `kafka.config.resources` ?

In our tests the referenced file is:

```
security.protocol=SASL_PLAINTEXT
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
    username="admin" \
    password="admin-secret";
```

Since this is actively tested, closing this issue as this is clearly misconfiguration issue.

**Closed by wendigo** 2024-12-05 17:39 UTC

**Comment by mattiamatrix** [comment] 2025-03-04 12:28
@wendigo I am trying to setup [Kafka Event Listener](https://trino.io/docs/current/admin/event-listeners-kafka.html#admin-event-listeners-kafka--page-root) and I am having an issue similar to @paragor.

This is my current setup, as I explained here https://github.com/trinodb/trino/issues/25065

_kafka.properties_
```properties
connector.name=kafka
kafka.nodes=<XXX>
kafka.table-description-supplier=FILE
kafka.table-description-dir=/etc/kafka
kafka.hide-internal-columns=false

kafka.config.resources=/etc/kafka-configuration.properties
```

_/etc/kafka-configuration.properties_
```properties
security.protocol=SASL_SSL
sasl.mechanism=AWS_MSK_IAM
sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required;
sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler
```

This works great to setup the Kafka Connector ✅

However, I don't understand how to do the same for the Kafka Event Listener ❌

For the Kafka Event Listener, this is my setup (which is currently not working):
_kafka-event-listener.properties_
```properties
event-listener.name=kafka
kafka-event-listener.broker-endpoints=<XXX>
kafka-event-listener.created-event.topic=query_create
kafka-event-listener.completed-event.topic=query_complete
kafka-event-listener.client-id=trino

kafka-event-listener.client-config-overrides=security.protocol=SASL_SSL,sasl.mechanism=AWS_MSK_IAM,sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler,sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required;
```


I have tried multiple options to enable `SASL_SSL` and `AWS_MSK_IAM`.

If, as suggested by the docs and @paragor, I use:
```properties
kafka-event-listener.client-config-overrides=security.protocol=SASL_SSL,sasl.mechanism=AWS_MSK_IAM,sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler,sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required;
```

The issue is the following:
```
2025-03-04T12:05:45.639Z        ERROR   main    io.trino.server.Server  Unable to create injector, see the following errors:

1) [Guice/ErrorInjectingConstructor]: ConfigException: Invalid value IAMClientCallbackHandler for configuration sasl.client.callback.handler.class: Class IAMClientCallbackHandler could not be found.
  at KafkaEventListener.<init>(Unknown Source)
  at KafkaEventListenerFactory.lambda$create$0(KafkaEventListenerFactory.java:50)
  while locating KafkaEventListener
  at GuiceMBeanExporter.<init>(GuiceMBeanExporter.java:40)
  at MBeanModule.configure(MBeanModule.java:39)
  while locating GuiceMBeanExporter
```

but this is unexpected because the `aws-msk-iam-auth-2.2.0-all.jar` plugin is loaded perfectly since the Kafka Connector catalog works as expected.

Instead, if I try adding `kafka.config.resources` to `kafka-event-listener.properties` I simply get the error 
```
Configuration property 'kafka.config.resources' was not used
```

Looking at the original PR https://github.com/trinodb/trino/pull/23066, Kafka Event Listener should support `kafka.*` configuration settings but apparently it only allows `kafka.security-protocol`.

-----

The problems I see here are two
- Kafka Event Listener doesn't have access to classes loaded by the `aws-msk-iam-auth-2.2.0-all.jar` plugin
- Kafka Event Listener does not allow custom setup for the Kafka Producer via `kafka.config.resources`

**Comment by mattiamatrix** [comment] 2025-03-04 16:36
My bad again 😅 

`aws-msk-iam-auth-2.2.0-all.jar` need to be loaded in both `usr/lib/trino/plugin/kafka/` **and** `/usr/lib/trino/plugin/kafka-event-listener`

**Comment by sudohainguyen** [comment] 2025-03-06 14:18
facing the similar issue
I'm bumping this up too @wendigo

**Comment by Setsushin** [comment] 2025-05-23 09:53
Why a Kafka event listener doesn't support send logs to Kafka with SASL.
I can't understand at all 🙁
