### ISSUE TITLE
Iceberg planning error while joining to partitioned table

### ISSUE THREAD

**Issue by JasonRuckman** [trinodb/trino#7502] opened 2021-04-05 20:41 UTC
When creating a table that has a timestamp using a transformation (in this case a day transformation), when that table is joined to another table the planner throws an error while converting the partition column.  In production use, the query doesn't fail, it just doesn't do any optimization.

This problem does not show up when the table is not joined (as the table statistics are not consulted). 

An example is: 

```
CREATE TABLE test_schema.test_table (a BIGINT, b TIMESTAMP(6) with time zone, c row(d BIGINT, e BIGINT)) WITH (partitioning = ARRAY['a', 'day(b)'])

create table test_schema.test_table_2 (foo BIGINT)

SELECT count(*) FROM test_schema.test_table join test_schema.test_table_2 on test_schema.test_table.a = test_schema.test_table_2.foo
```

Linked is a PR to a forked repo containing a unit test that will expose the issue:

https://github.com/JasonRuckman/trino/pull/1

Attached are logs from a test run
[trino_logs.txt](https://github.com/trinodb/trino/files/6260542/trino_logs.txt)

**Comment by JoJoBizarreAdventure** [comment] 2021-05-17 11:43
@JasonRuckman I want to have a try fixing it. Thanks for your testcase.
Later I want to discuss the solution with you, would you like leave me a hand?

**Comment by JoJoBizarreAdventure** [comment] 2021-05-17 13:03
It seems changing **long epochMicros = (long)value;** in **PartitionTable.java** to **long epochMicros = Long.parseLong(value.toString());** can solve this Exception. 
But there is other errors **Object 'io.trino.spi.type.LongTimestampWithTimeZone@dc5ff71' does not match type long** as below
![vmware_cRFUVwIOhn](https://user-images.githubusercontent.com/64888038/118493007-3a1bc880-b753-11eb-8672-548097185134.png)
I'm checking how Type is defined now.

**Comment by JoJoBizarreAdventure** [comment] 2021-05-17 13:32
![image](https://user-images.githubusercontent.com/64888038/118495935-42c1ce00-b756-11eb-8d88-4fe28270fd7a.png)
It seems that this javaType value is long, which is defined in **AbstractIntType.java**. It should be **LongTimestampWithTimeZone**.
I prefer to modify DateType.java and let it extends AbstractType and FixedWidthType just as AbstractIntType did and change the constructor to **super(signature,LongTimestampWithTimeZone.class).**
Do you think it is possible? @findepi

**Comment by hashhar** [comment] 2021-05-20 15:14
@JoJoBizarreAdventure The issue can be "fixed" by implementing a case for `DateType` in `PartitionTable#convert`.
The partition field is of type `long` (`TimestampType`) but the actual value is the value after applying the transform which is `int` (`DateType`). There is no branch for `DateType` in the `PartitionTable#convert` method.

@phd3 @electrum Longer term we should fix this by introducing a method to convert between Iceberg values to Trino stack values. Currently we are doing it in `PartitionTable#convert` which doesn't seem like the right place and also doesn't have sufficient test coverage. Does something like this already exist (I couldn't find one)? Or should I look at implementing one (where?)?

**Comment by JoJoBizarreAdventure** [comment] 2021-05-21 08:18
> PartitionTable

Ok I will have a try

**Comment by JoJoBizarreAdventure** [comment] 2021-05-21 08:19
> @JoJoBizarreAdventure The issue can be "fixed" by implementing a case for `DateType` in `PartitionTable#convert`.
> The partition field is of type `long` (`TimestampType`) but the actual value is the value after applying the transform which is `int` (`DateType`). There is no branch for `DateType` in the `PartitionTable#convert` method.
> 
> @phd3 @electrum Longer term we should fix this by introducing a method to convert between Iceberg values to Trino stack values. Currently we are doing it in `PartitionTable#convert` which doesn't seem like the right place and also doesn't have sufficient test coverage. Does something like this already exist (I couldn't find one)? Or should I look at implementing one (where?)?

Ok I will have a try

**Comment by chenjian2664** [comment] 2021-05-27 01:51
@hashhar @JoJoBizarreAdventure I think here is no need to add a branch for `DateType`, cuz `PartitionTable#convert` should remember the original type mapping to Trino, which is `TimestampType` not the `DateType`.
It's true that Iceberg finally store the value as `DateType`, but we need to remember Trino type here.

I think the problem is that Iceberg should not use their storage type to infer that type in Trino, especially the partitioned type(after transfrom).

**Comment by findepi** [comment] 2021-07-23 10:19
> Linked is a PR to a forked repo containing a unit test that will expose the issue:
> https://github.com/JasonRuckman/trino/pull/1

@JasonRuckman many thanks for a runnable test case!

the original exception you attached:

```
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')
	at io.trino.plugin.iceberg.PartitionTable.convert(PartitionTable.java:291)
	at io.trino.plugin.iceberg.TableStatisticsMaker.dataFileMatches(TableStatisticsMaker.java:216)
	at io.trino.plugin.iceberg.TableStatisticsMaker.makeTableStatistics(TableStatisticsMaker.java:131)
	at io.trino.plugin.iceberg.TableStatisticsMaker.getTableStatistics(TableStatisticsMaker.java:72)
	at io.trino.plugin.iceberg.IcebergMetadata.getTableStatistics(IcebergMetadata.java:800)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getTableStatistics(ClassLoaderSafeConnectorMetadata.java:281)
	at io.trino.metadata.MetadataManager.getTableStatistics(MetadataManager.java:526)
	at io.trino.cost.TableScanStatsRule.doCalculate(TableScanStatsRule.java:65)
```


seems to be no longer there

however, when i run your test on current `master`, i get 

```
java.lang.NullPointerException
	at org.apache.iceberg.types.Conversions.internalFromByteBuffer(Conversions.java:143)
	at org.apache.iceberg.types.Conversions.fromByteBuffer(Conversions.java:129)
	at io.trino.plugin.iceberg.Partition.lambda$toMap$4(Partition.java:238)
	at java.base/java.util.Map.forEach(Map.java:661)
	at io.trino.plugin.iceberg.Partition.toMap(Partition.java:236)
	at io.trino.plugin.iceberg.TableStatisticsMaker.makeTableStatistics(TableStatisticsMaker.java:146)
	at io.trino.plugin.iceberg.TableStatisticsMaker.getTableStatistics(TableStatisticsMaker.java:72)
	at io.trino.plugin.iceberg.IcebergMetadata.getTableStatistics(IcebergMetadata.java:1009)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.getTableStatistics(ClassLoaderSafeConnectorMetadata.java:303)
	at io.trino.metadata.MetadataManager.getTableStatistics(MetadataManager.java:580)
	at io.trino.cost.TableScanStatsRule.doCalculate(TableScanStatsRule.java:69)
	at io.trino.cost.TableScanStatsRule.doCalculate(TableScanStatsRule.java:40)
```

**Comment by findepi** [comment] 2021-07-23 10:47
This is tracked by https://github.com/trinodb/trino/issues/7999, so closing this one as fixed.

**Closed by findepi** 2021-07-23 10:47 UTC
Labels: bug
