### ISSUE TITLE
Generated UUID not preserved between references to CTE

### ISSUE THREAD

**Issue by padraic-mcatee** [trinodb/trino#20708] opened 2024-02-14 20:12 UTC
Trino version 436

Running the below query, I'd expect the `id` column to match after the join:
```sql
with
    a as (SELECT n, uuid() as id from unnest(sequence(0, 3)) seq(n))
select
    n,
    a1.id as a1_id,
    a2.id as a2_id
from
    a a1
        join a a2 using (n)
order by n
```
Results:
```
+-+------------------------------------+------------------------------------+
|n|a1_id                               |a2_id                               |
+-+------------------------------------+------------------------------------+
|0|3a11f181-9456-449a-909a-450458d29805|5ac40606-b4c4-4994-9e5a-1c47b31b03f9|
|1|0995e59b-ba01-4089-a0fe-1d405a8c3803|a5f21ff7-84f7-4c0f-bcef-b2314826149e|
|2|c9b36736-b94a-4214-8051-f1a177663df1|8287dded-db76-4dec-9610-6db57ab95a4a|
|3|fe2231d4-c0fe-4d84-ab44-c15b1c5ea2e5|14a1a3c2-4890-49a7-b6f6-250a7ce54040|
+-+------------------------------------+------------------------------------+
```

I imagine that the CTE results are "materialized" once for each part of the join, resulting in the uuid's being different. Is this expected behavior?

Compare to postgres behavior:
```sql
with
    a as (SELECT n, gen_random_uuid() as id from generate_series(0, 3) seq(n))
select
    n,
    a1.id as a1_id,
    a2.id as a2_id
from
    a a1
        join a a2 using (n)
order by n
```
Results:
```
+-+------------------------------------+------------------------------------+
|n|a1_id                               |a2_id                               |
+-+------------------------------------+------------------------------------+
|0|37352fc5-d2a9-4193-a88f-bd30ea03abee|37352fc5-d2a9-4193-a88f-bd30ea03abee|
|1|9db3a4df-406a-403b-bcd1-6cef2ea5879e|9db3a4df-406a-403b-bcd1-6cef2ea5879e|
|2|4dc5b279-85a9-403f-8d88-6fcfd65c450e|4dc5b279-85a9-403f-8d88-6fcfd65c450e|
|3|724e3121-b389-4a23-bdb2-86124e403d51|724e3121-b389-4a23-bdb2-86124e403d51|
+-+------------------------------------+------------------------------------+
```

**Comment by wendigo** [comment] 2024-02-14 22:03
@martint

**Comment by martint** [comment] 2024-02-14 22:09
This is a duplicate of https://github.com/trinodb/trino/issues/10

**Closed by martint** 2024-02-14 22:09 UTC
