### ISSUE TITLE
Query against Redshift view fails with transaction error

### ISSUE THREAD

**Issue by electrum** [trinodb/trino#793] opened 2019-05-20 16:53 UTC
```
com.facebook.presto.spi.PrestoException: ERROR: transaction is read-only Detail:
    at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.handleSqlException(JdbcRecordCursor.java:236)
    at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.(JdbcRecordCursor.java:95)
    at com.facebook.presto.plugin.jdbc.JdbcRecordSet.cursor(JdbcRecordSet.java:59)
    at com.facebook.presto.spi.RecordPageSource.(RecordPageSource.java:37)
    at com.facebook.presto.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:42)
    at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:56)
    at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:239)
    at com.facebook.presto.operator.Driver.processInternal(Driver.java:379)
    at com.facebook.presto.operator.Driver.lambda$processFor$8(Driver.java:283)
    at com.facebook.presto.operator.Driver.tryWithLock(Driver.java:675)
    at com.facebook.presto.operator.Driver.processFor(Driver.java:276)
    at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1077)
    at com.facebook.presto.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
    at com.facebook.presto.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
    at com.facebook.presto.$gen.Presto_0_219____20190520_105106_1.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: transaction is read-only Detail:
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:304)
    at com.facebook.presto.plugin.jdbc.JdbcRecordCursor.(JdbcRecordCursor.java:92) ... 16 more
```

**Comment by erichwang** [comment] 2020-10-26 18:37
Not sure what investigation has been done here, but based on the code, "ERROR: transaction is read-only Detail" is an error message coming from the Redshift server, so it might have something to do with an incompatible parameter or usage of Redshift with JDBC in general.

For example, I found this similar error from Redshift in another context when combining Redshift+JDBC+derived table containing group by or Distinct:
https://community.jaspersoft.com/wiki/server-error-when-using-derived-table-redshift

**Comment by ebyhr** [comment] 2021-01-01 12:56
I guess this issue comes from https://stackoverflow.com/questions/56220002/aggregate-query-in-presto-on-redshifts-view-failing-with-error-org-postgresql-u. I tried reproducing it, but I couldn't on version 0.219 (same as questioner's) and Trino upstream.

**Comment by hashhar** [comment] 2024-02-26 09:45
Should be fixed now since https://github.com/trinodb/trino/blob/60c94a326c653b30ea718acb608ebf5cccdf2dbf/plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java#L296-L299 code is present now.

**Closed by hashhar** 2024-02-26 09:45 UTC
