### ISSUE TITLE
Analyze command fails to update statistics on a HIVE table in CDP 7.1.7

### ISSUE THREAD

**Issue by jdhanani1** [trinodb/trino#21106] opened 2024-03-15 18:45 UTC
Trino version: 422.9

Trino is failing to run  `ANALYZE` on hive table in `CDP 7.1.7` . Following error is observed on HIVE side. Seems like Trino is not compatible or not handling CDP 7.1.7.

ERROR org.apache.hadoop.hive.metastore.RetryingHMSHandler: [pool-9-thread-189]: HMSHandler Fatal error: javax.jdo.JDODataStoreException: Insert of object "org.apache.hadoop.hive.metastore.model.MPartitionColumnStatistics@7c92e99b" using statement "INSERT INTO "PART_COL_STATS" ("CS_ID","AVG_COL_LEN","BIT_VECTOR","CAT_NAME","COLUMN_NAME","COLUMN_TYPE","DB_NAME","BIG_DECIMAL_HIGH_VALUE","BIG_DECIMAL_LOW_VALUE","DOUBLE_HIGH_VALUE","DOUBLE_LOW_VALUE","ENGINE","LAST_ANALYZED","LONG_HIGH_VALUE","LONG_LOW_VALUE","MAX_COL_LEN","NUM_DISTINCTS","NUM_FALSES","NUM_NULLS","NUM_TRUES","PART_ID","PARTITION_NAME","TABLE_NAME") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)" failed : ERROR: null value in column "ENGINE" violates not-null constraint

**Comment by wendigo** [comment] 2024-03-15 18:59
CDP 7 uses unsupported Hive metastore version

**Comment by jdhanani1** [comment] 2024-03-15 20:27
Can this support be added?

**Comment by wendigo** [comment] 2024-03-15 20:31
We don't have a testing environment to test against so it's unlikely that we will add support

**Comment by ebyhr** [comment] 2024-03-15 22:42
Closing as duplicate of https://github.com/trinodb/trino/issues/8548

**Closed by ebyhr** 2024-03-15 22:42 UTC
