### ISSUE TITLE
Flaky TestHiveFaultTolerantExecutionConnectorTest.close 

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#11929] opened 2022-04-13 08:24 UTC
```
2022-04-13T03:08:12.254-0500	INFO	pool-3-thread-1	io.trino.testng.services.LogTestDurationListener	Test io.trino.plugin.hive.TestHiveFaultTolerantExecutionConnectorTest.close took 30.49s
Error:  Tests run: 754, Failures: 1, Errors: 0, Skipped: 25, Time elapsed: 919.723 s <<< FAILURE! - in TestSuite
Error:  io.trino.plugin.hive.TestHiveFaultTolerantExecutionConnectorTest.close  Time elapsed: 31.504 s  <<< FAILURE!
java.lang.AssertionError: 
Expected memory reservation on server_0(worker)to be 0 but was 79736; detailed memory usage:
 20220413_080329_03792_nksgw:
   SQL: INSERT INTO invalid_partition_value VALUES (4, 'test' || chr(13))
   state: FAILED
   memoryReservation: 79736
   taggedMemoryReservaton: {HashAggregationOperator=79736}

	at org.testng.Assert.fail(Assert.java:94)
	at io.trino.testing.AbstractTestQueryFramework.assertMemoryPoolReleased(AbstractTestQueryFramework.java:149)
	at io.trino.testing.AbstractTestQueryFramework.lambda$checkQueryMemoryReleased$0(AbstractTestQueryFramework.java:134)
	at io.trino.testing.assertions.Assert.assertEventually(Assert.java:77)
	at io.trino.testing.AbstractTestQueryFramework.checkQueryMemoryReleased(AbstractTestQueryFramework.java:127)
	at io.trino.testing.AbstractTestQueryFramework.close(AbstractTestQueryFramework.java:108)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

https://github.com/trinodb/trino/runs/6003330080

**Comment by findepi** [comment] 2022-04-13 08:41
cc @arhimondr @losipiuk @linzebing

**Comment by arhimondr** [comment] 2022-05-10 22:29
Closing as duplicate of https://github.com/trinodb/trino/issues/11275

**Closed by arhimondr** 2022-05-10 22:29 UTC
Labels: bug, test
