### ISSUE TITLE
Memory leak in Trino JDBC driver when using DatabaseMetaData

### ISSUE THREAD

**Issue by xumanbu** [trinodb/trino#10584] opened 2022-01-13 08:36 UTC
private ResultSet select(String sql)
            throws SQLException
    {
        return getConnection().createStatement().executeQuery(sql);
    }

if connection created by connection pool(eg dbcp..)，connection always in active，TrinoConnection.statements will sustained increase.

this case find in calsite JdbcSchema https://github.com/apache/calcite/blob/master/core/src/main/java/org/apache/calcite/adapter/jdbc/JdbcSchema.java

**Comment by hashhar** [comment] 2022-01-13 10:57
That is expected. `DatabaseMetaData` is created by calling `getMetaData` on an existing connection. It's responsibility of the process that created that initial connection to close it. Also the `DatabaseMetaData` is expected to be re-used so if you close the connection within the `DatabaseMetaData` then re-use becomes impossible.

See for example any other JDBC driver. e.g PostgreSQL https://github.com/pgjdbc/pgjdbc/blob/c12a76f6c42ba3c41d6f4472f3a47d645e9dba33/pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java#L2767-L2770

Closing since this is not a bug.

**Comment by ebyhr** [comment] 2022-01-13 11:25
@xumanbu Just in case, what happens if you use other JDBC drivers and servers?

**Comment by xumanbu** [comment] 2022-01-14 06:00
@hashhar @ebyhr in my case,I use calsite jdbc schema by trino jdbc schedule cache hive metadata,from jvm monitor old heap memory still growth until OOM. wo find too many statement objects in TrinoConnection#statements from dump  file.

this is the solution  by mysql cj :
github.com/mysql/mysql-connector-j/blob/release/8.0/src/main/user-impl/java/com/mysql/cj/jdbc/DatabaseMetaData.java

public java.sql.ResultSet getColumns(final String catalog, final String schemaPattern, final String tableNamePattern, String columnNamePattern)
            throws SQLException {
          .............................
         @Override
                void forEach(String dbStr) throws SQLException {

                    ArrayList<String> tableNameList = new ArrayList<>();

                    java.sql.ResultSet tables = null;
                    ......................

                    for (String tableName : tableNameList) {

                        ResultSet results = null;

                        try {

                            ..................
                    
                        } finally {
                            if (results != null) {
                                try {
                                    results.close();
                                } catch (Exception ex) {
                                }

                                results = null;
                            }
                        }
                    }
                }
            }.doForAll();
        } finally {
            if (stmt != null) {
                stmt.close();
            }
        }

        java.sql.ResultSet results = this.resultSetFactory.createFromResultsetRows(ResultSet.CONCUR_READ_ONLY, ResultSet.TYPE_SCROLL_INSENSITIVE,
                new ResultsetRowsStatic(rows, new DefaultColumnDefinition(fields)));

        return results;
    }

**Comment by findepi** [comment] 2022-01-14 09:50
cc @kokosing

**Comment by kokosing** [comment] 2022-01-14 10:49
cc: @aalbu

**Comment by nineinchnick** [comment] 2022-01-14 12:02
I'm not sure if that'll help, but I saw a similar bug fixed in the MSSQL JDBC driver a while ago: https://github.com/microsoft/mssql-jdbc/pull/806

**Closed** 2022-01-18 08:15 UTC
Labels: bug, jdbc
