### ISSUE TITLE
Hope trino supports iceberg's tag and branche's processing power.

### ISSUE THREAD

**Issue by c8679724** [trinodb/trino#16695] opened 2023-03-23 13:41 UTC
See spark's support for iceberg for details.

https://iceberg.apache.org/releases/#120-release

1. Added support for reading a branch or tag through table identifier and VERSION AS OF (a.k.a. FOR SYSTEM_VERSION AS OF) SQL syntax

2. Added support for writing to a branch through identifier or through write-audit-publish (WAP) workflow settings 

3. Added DDL SQL extensions to create, replace and drop a branch or tag

**Comment by ebyhr** [comment] 2023-03-23 23:47
Closing as duplicate of #16570 & #16569

**Closed by ebyhr** 2023-03-23 23:47 UTC
