### ISSUE TITLE
Elasticsearch Time type field is missing

### ISSUE THREAD

**Issue by beepupa** [trinodb/trino#8608] opened 2021-07-20 07:48 UTC
presto V:359
Elasticsearch V :7.0+
in prestosql
![image](https://user-images.githubusercontent.com/36186038/126282377-1974ffa0-0b4f-4742-adec-803cc7645480.png)
in es

```json
{
  "mappings": {
    "SysOprLog": {
      "_all": {
        "enabled": false
      },
      "properties": {
        "metadataObject": {
          "type": "integer"
        },
        "mail": {
          "analyzer": "ngram_analyzer",
          "type": "text"
        },
        "appName": {
          "analyzer": "ngram_analyzer",
          "type": "text"
        },
        "objectKeyvalue": {
          "analyzer": "ngram_analyzer",
          "type": "text"
        },
        "menuName": {
          "analyzer": "ngram_analyzer",
          "type": "text"
        },
        "oprNickname": {
          "analyzer": "ngram_analyzer",
          "type": "text"
        },
        "oprType": {
          "type": "keyword"
        },
        "templateCode": {
          "analyzer": "ngram_analyzer",
          "type": "text"
        },
        "logClass": {
          "type": "integer"
        },
        "custAppId": {
          "type": "keyword"
        },
        "objectType": {
          "analyzer": "ngram_analyzer",
          "type": "text"
        },
        "oprUsername": {
          "analyzer": "ngram_analyzer",
          "type": "text"
        },
        "createTime": {
          "format": "yyyy-MM-dd HH:mm:ss||strict_date_optional_time||epoch_millis",
          "type": "date"
        },
        "phone": {
          "analyzer": "ngram_analyzer",
          "type": "text"
        },
        "appId": {
          "type": "keyword"
        },
        "ipAdderss": {
          "type": "keyword"
        },
        "action": {
          "type": "keyword"
        },
        "menuId": {
          "type": "keyword"
        },
        "micrservCode": {
          "analyzer": "ngram_analyzer",
          "type": "text"
        },
        "detail": {
          "analyzer": "ngram_analyzer",
          "type": "text"
        },
        "oprId": {
          "type": "keyword"
        },
        "objectId": {
          "analyzer": "ngram_analyzer",
          "type": "text"
        },
        "oprTime": {
          "format": "yyyy-MM-dd HH:mm:ss||strict_date_optional_time||epoch_millis",
          "type": "date"
        },
        "status": {
          "type": "integer"
        }
      }
    }
  }
}
```

**Comment by hashhar** [comment] 2021-07-20 07:51
Temporal types with custom `format` aren't supported yet. It's being documented in https://github.com/trinodb/trino/pull/8464.

cc: @sumannewton @bitsondatadev

**Comment by beepupa** [comment] 2021-07-20 08:14
When I get rid of the format, it's fine

**Comment by beepupa** [comment] 2021-07-20 08:21
> `format`尚不支持具有自定义的时间类型。它被记录在[#8464 中](https://github.com/trinodb/trino/pull/8464)。
> 
> 抄送：@sumannewton @bitsondatadev

thank you

**Comment by sumannewton** [comment] 2021-07-20 08:59
Duplicate of #3395. I am working on this. Takes few more weeks to go.

**Closed** 2021-07-20 09:01 UTC
Labels: duplicate
