### ISSUE TITLE
Query Druid from Trino for mix Upper - lower Case Tables

### ISSUE THREAD

**Issue by gtsiatsios** [trinodb/trino#16689] opened 2023-03-23 10:01 UTC
Describe case:
I am using the latest version of Trino and Druid Image via `docker-compose`. From Trino I am able to connect in Druid using `use druid.druid` . `show tables` actually shows all tables in Druid in lower case. All my table in Druid are mixed upper - lower case letter eg. `TheTableInDruid`. When I query the table `select * from TheTableInDruid` , Trino reports that the table doesn't exist.

Using the following `druid.properties` :

 ```
connector.name=druid
druid.coordinator-url=jdbc:avatica:remote:url=https://theip:XXXX/druid/v2/sql/avatica/
druid.connection-user=ausername
druid.connection-password=apassword
druid.case-insensitive-name-matching=true
```
Tried to create mapping.json with configuration file below without any success:

 ```
connector.name=druid
druid.coordinator-url=jdbc:avatica:remote:url=https://theip:XXXX/druid/v2/sql/avatica/
druid.connection-user=ausername
druid.connection-password=apassword
case-insensitive-name-matching.cnfig-file=/etc/trino/catalog/mapping.json
```

Using the MongoDB connector with `mongodb.case-insensitive-name-matching=true` I have no problem connecting to mongoDB collections with mixed upercase- lowercase letter for example `TheMongoCollection`.

**Comment by ebyhr** [comment] 2023-03-23 23:49
Closing as duplicate of #6850

**Closed by ebyhr** 2023-03-23 23:49 UTC
