### ISSUE TITLE
ODBC connector for PowerBI

### ISSUE THREAD

**Issue by ramyerrabotu** [trinodb/trino#12335] opened 2022-05-11 02:32 UTC
Is there any plans to release OBC connector for power BI?  We have some scenarios where we need to connect powerbi with Trino and there are no free ODBC connectors without any dependency on PowerBI gatewy

**Comment by ebyhr** [comment] 2022-05-11 05:44
Let me close as duplicate of #6886

**Closed by ebyhr** 2022-05-11 05:44 UTC
