### ISSUE TITLE
Add limit pushdown for Kafka connector

### ISSUE THREAD

**Issue by xxzhky** [trinodb/trino#19604] opened 2023-11-01 06:33 UTC
Fixes several issues with LimitNode pushdown logic that could result in extremely long data-scanning time and unnecessary huge data, especially in the presence of large table:

Given a query like:

`select * from kafka.default.std_eca_swda_log limit 10`

The previous resulting plan without these changes is as follows:
> ![image](https://github.com/trinodb/trino/assets/26535161/f14b268d-fe38-416f-ae72-2160da983417)

With these changes, the new plan is:
> ![image](https://github.com/trinodb/trino/assets/26535161/59fce2bb-53ba-46f4-bc6f-3b75960bcd3a)

**Comment by ebyhr** [comment] 2023-11-01 07:09
Please update the title and description.

**Comment by ebyhr** [comment] 2023-11-01 08:36
Closing as duplicate of #7071

**Closed by ebyhr** 2023-11-01 08:36 UTC

**Comment by xxzhky** [comment] 2023-11-01 09:07
@ebyhr did  it(#7071 ) merge into master and to be avaliable for us?

**Comment by ebyhr** [comment] 2023-11-01 09:17
No.

**Comment by xxzhky** [comment] 2023-11-01 09:25
got it. But why is it not available for us? @ebyhr
