### ISSUE TITLE
trino is slow compare to presto

### ISSUE THREAD

**Issue by njalan** [trinodb/trino#20372] opened 2024-01-14 11:56 UTC
Currently We are using trino 406 but the performance is not that good.
Most of the are queries are completed within 3 seconds but in trino it is running much slower.
I found that analysis   and planning   takes too much time.
 
<img width="566" alt="image" src="https://github.com/trinodb/trino/assets/8622340/3fda9831-3e37-4d87-99b8-8ba645274e57">

Below is my config:

coordinator=true
node-scheduler.include-coordinator=false
internal-communication.shared-secret=trino
http-server.http.port=8084
http-server.authentication.type=PASSWORD
http-server.https.enabled=true
http-server.https.port=8443
http-server.https.keystore.path=xxx
http-server.https.keystore.key=xxx
node-scheduler.max-splits-per-node=200
node-scheduler.max-pending-splits-per-task=20
query.max-stage-count=400
query.max-length=65432
query.stage-count-warning-threshold=400
query.max-memory=50GB
query.max-memory-per-node=4GB
task.max-drivers-per-task=16
exchange.http-client.request-timeout=120s
exchange.client-threads=40
query.max-run-time=40s
scheduler.http-client.max-requests-queued-per-destination=4096
query.max-history=200
query.min-expire-age=30m
http-server.log.max-size=67108864B
http-server.log.max-history=5
node-scheduler.max-splits-per-node=400
node-scheduler.max-pending-splits-per-task=60
sql.forced-session-time-zone=Asia/Shanghai
discovery.uri=http://xxxx:8084

Here is my jvm:
  -server
-Xmx160G
-XX:InitialRAMPercentage=80
-XX:MaxRAMPercentage=80
-XX:G1HeapRegionSize=32M
-XX:+ExplicitGCInvokesConcurrent
-XX:+ExitOnOutOfMemoryError
-XX:+HeapDumpOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow
-XX:ReservedCodeCacheSize=512M
-XX:PerMethodRecompilationCutoff=10000
-XX:PerBytecodeRecompilationCutoff=10000
-Djdk.attach.allowAttachSelf=true
-Djdk.nio.maxCachedBufferSize=2000000
-XX:+UnlockDiagnosticVMOptions
-XX:+UseAESCTRIntrinsics
--add-opens=java.base/java.lang=ALL-UNNAMED
-Djava.io.tmpdir=/data/trinossl/jvm
-Dcom.sun.management.jmxremote.authenticate=false
-Dcom.sun.management.jmxremote.ssl=false
-Dcom.sun.management.jmxremote.local.only=false
-Dcom.sun.management.jmxremote.port=38084

**Comment by mosabua** [comment] 2024-01-15 00:34
With this limited information (screenshot is also not available) we can not really tell what is going on. We would need more info like what queries, what catalogs/connectors are used, what is different compared to Presto, ..

**Comment by njalan** [comment] 2024-01-15 05:42
I am using hudi connector in trino 406 but using hive connector in presto.(there is hudi connector for presto)
Below is my sql:
Elapsed Time	23.45s
Queued Time	12.77s
Analysis Time	9.06s
Planning Time	7.45s
Execution Time	10.68s

SELECT so_owner AS so_owner, COUNT(*) AS count
FROM  xxxxx
WHERE so_created_date_local >= from_iso8601_timestamp('2024-01-15T00:00:00') AND so_created_date_local <= from_iso8601_timestamp('2024-01-15T23:59:59') AND (so_owner_store = 'xxxxx' AND trackingsource IN ('xxxxx')) GROUP BY so_owner ORDER BY count DESC
LIMIT 10000

**Comment by hashhar** [comment] 2024-01-15 08:39
see https://github.com/trinodb/trino/issues/17894, if it's the same issue it was improved in newer Trino versions.

Closing since the information suggests it to be the cause. Feel free to reopen if you can observe similar slowness with some connector other than Hudi.

**Closed by hashhar** 2024-01-15 08:39 UTC
