### ISSUE TITLE
Native Parquet writer creates files that cannot be read by Hive and Spark

### ISSUE THREAD

**Issue by davseitsev** [trinodb/trino#6377] opened 2020-12-18 09:36 UTC
Spark can't read parquet files created by presto-parquet writer, it throws exception:
```
org.apache.parquet.io.ParquetDecodingException: Cannot read data due to PARQUET-246: to read safely, set parquet.split.files to false
	at org.apache.parquet.hadoop.ParquetRecordReader.checkDeltaByteArrayProblem(ParquetRecordReader.java:195)
	at org.apache.parquet.hadoop.ParquetRecordReader.initializeInternalReader(ParquetRecordReader.java:177)
	at org.apache.parquet.hadoop.ParquetRecordReader.initialize(ParquetRecordReader.java:140)
```
The exception is thrown in [ParquetRecordReader.java#L195](https://github.com/apache/parquet-mr/blob/master/parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetRecordReader.java#L195) when it tries to get writer version from created_by field. This filed should contain name and version of library that created parquet file, like `parquet-mr version 1.11.0 ...`. But presto-parquet leaves it empty when it creates footer [ParquetWriter.java#L238-L251](https://github.com/prestosql/presto/blob/master/presto-parquet/src/main/java/io/prestosql/parquet/writer/ParquetWriter.java#L238-L251).

I would suggest to add created_by field and make it configurable for compatibility reasons.

**Comment by MariyaR** [comment] 2021-07-09 14:03
Hi,
Can I try this issue? Configuration of created_by field should be done in ParquetWriterConfig or in another place? Thanks in advance.

**Comment by findepi** [comment] 2021-07-12 14:52
Per @rdblue 's https://github.com/trinodb/trino/issues/7953#issuecomment-872544273 closing in favor of that issue, because that one has more conversation already.

**Comment by davseitsev** [comment] 2021-07-13 07:39
@findepi I'm not sure it's the same issue as you mentioned. As far as I understand that one is about support parquet format V1 in Presto writer due to lack of support of format V2 in some engines like Spark (BTW we read parquet V2 in Spark without vectorized reader and it works perfectly). This one is about compatibility between presto native writer and parquet-hadoop library which is used in Spark and some other engines. It doesn't depend on parquet format version, new encodings or so.
I'm pretty sure that implementing support of parquet format V1 in presto native writer without correct `created_by` field won't solve compatibility issue. 
I would say that the issue is on hadoop-library side which throws exception in case of empty `created_by` field but it would be great to fix it on Presto side for compatibility reasons.
Thanks.

**Comment by MariyaR** [comment] 2021-07-19 08:01
@findepi, as far as the issue is reopened, can I try this? Configuration of created_by field should be done in ParquetWriterConfig or in another place? Thanks in advance.

**Comment by findepi** [comment] 2021-09-28 20:39
> org.apache.parquet.io.ParquetDecodingException: Cannot read data due to PARQUET-246: to read safely, set parquet.split.files to false
> 	at org.apache.parquet.hadoop.ParquetRecordReader.checkDeltaByteArrayProblem(ParquetRecordReader.java:195)

This is not the only problem that needs to be overcame to solve the issue from user perspective.

See #9416 and #7953 for more details provided by @joshthoward @anjalinorwood @rdblue and others.

**Comment by findepi** [comment] 2022-01-12 21:29
Reopened as there still is a problem that no Hive version can read timestamps written by the native Parquet writer (also related to https://github.com/trinodb/trino/issues/4608 ).

**Comment by raunaqmorarka** [comment] 2022-06-24 19:26
Should be fixed after https://github.com/trinodb/trino/pull/12658 and https://github.com/trinodb/trino/pull/12857

**Closed by raunaqmorarka** 2022-06-24 19:26 UTC
Labels: bug
