### ISSUE TITLE
Add Trino to Clickhouse mapping: TIMESTAMP(P) WITH TIME ZONE to DateTime64(precision, [timezone])

### ISSUE THREAD

**Issue by maratbakiev2** [trinodb/trino#15977] opened 2023-02-04 23:32 UTC
Hi guys, currently Trino doesn't support this kind of mapping but it would be very useful to have it. working with timestamps is really the basis.

From my experiments it follows that
1. if you do something like
`
insert into clickhouse."default".ts_1
values (TIMESTAMP '2023-02-02 12:00:00 +05:00', TIMESTAMP '2023-02-02 12:00:00 -06:00')
`
then Trino will just ignore timezones and insert into respective columns (which are datetime*(with timezone) in clickhouse value of the string '2023-02-02 12:00:00' and treat it at the time zone that was specified in Clickhouse table column in creattion
2. If you select (from datetimetz type) rows from postgres they first will be converted to time in UTC and then will be again treated as strings without timezone and pasted to Clickhouse.

**Comment by ebyhr** [comment] 2023-02-05 23:00
Closing as duplicate of #10537

**Closed by ebyhr** 2023-02-05 23:00 UTC
