### ISSUE TITLE
Snowflake Connector: Key-pair authentication

### ISSUE THREAD

**Issue by rponsaerts** [trinodb/trino#24424] opened 2024-12-10 02:22 UTC
Hi,

Currently, I don't think it is possible to authenticate to Snowflake using the key-pair method (a private key file) with the Snowflake connector in Trino.

Key-pair authentication using the private key in a file (optionally encrypted using a passphrase) and the public key registered in Snowflake is considered to be a more secure way of authenticating compared to just using username/passwd.

[https://docs.snowflake.com/en/user-guide/key-pair-auth](url)

Can this feature be implemented in the Snowflake connector for Trino?

best,

raf

**Comment by ebyhr** [comment] 2024-12-10 02:53
Duplicate of https://github.com/trinodb/trino/discussions/24286

**Closed by ebyhr** 2024-12-10 02:53 UTC
