### ISSUE TITLE
 failed: Expected Limit input to be sorted by: [vip], but was [create_date, game_cd, equip_name, vip]

### ISSUE THREAD

**Issue by pysenic** [trinodb/trino#9281] opened 2021-09-17 09:25 UTC
version:361
cli:trino-cli-361-executable.jar

The SQL is :
```SQL
select vip
     , game_cd
     , create_date
     , equip_name
     , vip_user_count
     , equip_lv_1_count as total_count
     , lv_1_skin_count  as skin_count
     , lv_1_skin_rate   as skin_rate
     , avg_user_equip_1 as avg_equip
from ads.user_vip_skin_rate
where game_cd = '1001'
  and create_date = '2021-09-09'
  and vip in (0)
  and equip_name in ('黑帮教父')
order by vip limit 100;
```

![image](https://user-images.githubusercontent.com/20294807/133757508-15d98a4a-d7d6-4976-973b-a3edb3a7f5ba.png)

![image](https://user-images.githubusercontent.com/20294807/133758741-f4e81190-52a8-4a25-a716-ca7530258d42.png)

if cast vip as varchar,can be executed normally

![image](https://user-images.githubusercontent.com/20294807/133758258-39ac015a-d217-4929-96fc-3b7655f9b4a4.png)

if change sql vip in (0) to vip in (0,1), can be executed normally
![image](https://user-images.githubusercontent.com/20294807/133760377-0a4afd2c-329c-4e90-bdf1-95e61800179f.png)

catalog is hive,hive's version is 2.3.7

hive show create table :

```
hive (default)> show create table  ads.user_vip_skin_rate;
OK
createtab_stmt
CREATE TABLE `ads.user_vip_skin_rate`(
  `vip` bigint COMMENT 'VIP等级',
  `equip_name` string COMMENT '皮肤名称',
  `vip_user_count` bigint COMMENT 'VIP用户数量',
  `equip_lv_0_count` bigint COMMENT '普通皮肤总数',
  `lv_0_skin_count` bigint COMMENT '该皮肤普通数量',
  `lv_0_skin_rate` double COMMENT '该皮肤普通占比',
  `avg_user_equip_0` double COMMENT '用户该普通皮肤平均数',
  `equip_lv_1_count` bigint COMMENT '限定皮肤总数',
  `lv_1_skin_count` bigint COMMENT '该皮肤限定数量',
  `lv_1_skin_rate` double COMMENT '该皮肤限定占比',
  `avg_user_equip_1` double COMMENT '用户该限定皮肤平均数',
  `equip_lv_2_count` bigint COMMENT '传说皮肤总数',
  `lv_2_skin_count` bigint COMMENT '该皮肤传说数量',
  `lv_2_skin_rate` double COMMENT '该皮肤传说占比',
  `avg_user_equip_2` double COMMENT '用户该传说皮肤平均数')
COMMENT 'AD 皮肤保有量-比率报表'
PARTITIONED BY (
  `game_cd` string,
  `create_date` string)
ROW FORMAT SERDE
  'org.apache.hadoop.hive.ql.io.orc.OrcSerde'
STORED AS INPUTFORMAT
  'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat'
OUTPUTFORMAT
  'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat'
LOCATION
  'hdfs://HDFS43374/usr/hive/warehouse/ads.db/user_vip_skin_rate'
TBLPROPERTIES (
  'transient_lastDdlTime'='1631269615')
Time taken: 0.101 seconds, Fetched: 30 row(s)
```

presto show create table is :

```
trino:ods> show create table ads.user_vip_skin_rate;
                                        Create Table
--------------------------------------------------------------------------------------------
 CREATE TABLE hive.ads.user_vip_skin_rate (
    vip bigint COMMENT U&'VIP\7B49\7EA7',
    equip_name varchar COMMENT U&'\76AE\80A4\540D\79F0',
    vip_user_count bigint COMMENT U&'VIP\7528\6237\6570\91CF',
    equip_lv_0_count bigint COMMENT U&'\666E\901A\76AE\80A4\603B\6570',
    lv_0_skin_count bigint COMMENT U&'\8BE5\76AE\80A4\666E\901A\6570\91CF',
    lv_0_skin_rate double COMMENT U&'\8BE5\76AE\80A4\666E\901A\5360\6BD4',
    avg_user_equip_0 double COMMENT U&'\7528\6237\8BE5\666E\901A\76AE\80A4\5E73\5747\6570',
    equip_lv_1_count bigint COMMENT U&'\9650\5B9A\76AE\80A4\603B\6570',
    lv_1_skin_count bigint COMMENT U&'\8BE5\76AE\80A4\9650\5B9A\6570\91CF',
    lv_1_skin_rate double COMMENT U&'\8BE5\76AE\80A4\9650\5B9A\5360\6BD4',
    avg_user_equip_1 double COMMENT U&'\7528\6237\8BE5\9650\5B9A\76AE\80A4\5E73\5747\6570',
    equip_lv_2_count bigint COMMENT U&'\4F20\8BF4\76AE\80A4\603B\6570',
    lv_2_skin_count bigint COMMENT U&'\8BE5\76AE\80A4\4F20\8BF4\6570\91CF',
    lv_2_skin_rate double COMMENT U&'\8BE5\76AE\80A4\4F20\8BF4\5360\6BD4',
    avg_user_equip_2 double COMMENT U&'\7528\6237\8BE5\4F20\8BF4\76AE\80A4\5E73\5747\6570',
    game_cd varchar,
    create_date varchar
 )
 COMMENT U&'AD \76AE\80A4\4FDD\6709\91CF-\6BD4\7387\62A5\8868'
 WITH (
    format = 'ORC',
    partitioned_by = ARRAY['game_cd','create_date']
 )
(1 row)

Query 20210917_092512_02922_u69sx, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0.29 [0 rows, 0B] [0 rows/s, 0B/s]

trino:ods>
```

**Comment by hashhar** [comment] 2021-09-17 09:36
This seems like a duplicate of https://github.com/trinodb/trino/issues/9171. The root cause sounds the same.

Closing in favour of https://github.com/trinodb/trino/issues/9171.

cc: @raunaqmorarka

**Closed by hashhar** 2021-09-17 09:36 UTC
