### ISSUE TITLE
Product Tests  (default, suite-cassandra, ) failed

### ISSUE THREAD

**Issue by guiyanakuang** [trinodb/trino#16218] opened 2023-02-22 10:11 UTC
Product Tests  (default, suite-cassandra, ) failed
https://github.com/trinodb/trino/actions/runs/4234468075/jobs/7361026240

messgae:
> tests               | 2023-02-22 05:13:15 INFO: [16 of 30] io.trino.tests.product.cassandra.TestSelect.testSelectUserDefinedType (Groups: profile_specific_tests, cassandra)
tests               | 2023-02-22 05:13:15 INFO: Using native clock for microsecond precision
tests               | 2023-02-22 05:13:17 INFO: Using native clock for microsecond precision
cassandra           | WARN  23:28:17 An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
cassandra           | io.netty.handler.codec.DecoderException: org.apache.cassandra.transport.ProtocolException: Invalid or unsupported protocol version (5); the lowest supported version is 3 and the greatest is 4
cassandra           | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
cassandra           | 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:375) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
cassandra           | 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:342) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
cassandra           | 	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
cassandra           | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:250) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
cassandra           | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:236) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
cassandra           | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:229) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
cassandra           | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1289) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
cassandra           | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:250) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
cassandra           | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:236) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
cassandra           | 	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:893) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
cassandra           | 	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:691) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
cassandra           | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:408) [netty-all-4.0.39.Final.jar:4.0.39.Final]
cassandra           | 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309) [netty-all-4.0.39.Final.jar:4.0.39.Final]
cassandra           | 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140) [netty-all-4.0.39.Final.jar:4.0.39.Final]
cassandra           | 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [netty-all-4.0.39.Final.jar:4.0.39.Final]
cassandra           | 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
cassandra           | Caused by: org.apache.cassandra.transport.ProtocolException: Invalid or unsupported protocol version (5); the lowest supported version is 3 and the greatest is 4
cassandra           | 	at org.apache.cassandra.transport.Frame$Decoder.decode(Frame.java:180) ~[apache-cassandra-3.9.jar:3.9]
cassandra           | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ~[netty-all-4.0.39.Final.jar:4.0.39.Final]
cassandra           | 	... 16 common frames omitted

**Comment by nineinchnick** [comment] 2023-02-22 10:18
Duplicate of #12818

**Closed by nineinchnick** 2023-02-22 10:18 UTC
