### ISSUE TITLE
TestMySqlCaseInsensitiveMapping.testSchemaNameClashWithRuleMapping flaky

### ISSUE THREAD

**Issue by losipiuk** [trinodb/trino#8478] opened 2021-07-06 11:45 UTC
```
2021-07-06T10:30:16.4807709Z [ERROR] Tests run: 246, Failures: 2, Errors: 0, Skipped: 10, Time elapsed: 492.14 s <<< FAILURE! - in TestSuite
2021-07-06T10:30:16.4819946Z [ERROR] testSchemaNameClashWithRuleMapping(io.trino.plugin.mysql.TestMySqlCaseInsensitiveMapping)  Time elapsed: 0.222 s  <<< FAILURE!
2021-07-06T10:30:16.4824650Z java.lang.AssertionError: 
2021-07-06T10:30:16.4826226Z 
2021-07-06T10:30:16.4829564Z Expected size:<2> but was:<1> in:
2021-07-06T10:30:16.4832472Z <["casesensitivename"]>
2021-07-06T10:30:16.4843649Z 	at io.trino.plugin.jdbc.BaseCaseInsensitiveMappingTest.testSchemaNameClashWithRuleMapping(BaseCaseInsensitiveMappingTest.java:225)
2021-07-06T10:30:16.4862788Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-07-06T10:30:16.4873494Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-07-06T10:30:16.4883524Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-07-06T10:30:16.4890401Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-07-06T10:30:16.4898479Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-07-06T10:30:16.4905002Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-07-06T10:30:16.4911256Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-07-06T10:30:16.4917789Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-07-06T10:30:16.4925586Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-07-06T10:30:16.4941859Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-07-06T10:30:16.4959851Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-07-06T10:30:16.4968646Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-07-06T10:30:16.4973927Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-07-06T10:30:16.4975889Z 
2021-07-06T10:30:16.4986464Z [ERROR] testTableNameClashWithRuleMapping(io.trino.plugin.mysql.TestMySqlCaseInsensitiveMapping)  Time elapsed: 0.015 s  <<< FAILURE!
2021-07-06T10:30:16.4996243Z java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: Table 'casesensitivename' already exists
2021-07-06T10:30:16.5003905Z 	at io.trino.plugin.mysql.TestingMySqlServer.execute(TestingMySqlServer.java:79)
2021-07-06T10:30:16.5012791Z 	at io.trino.plugin.mysql.TestingMySqlServer.execute(TestingMySqlServer.java:69)
2021-07-06T10:30:16.5022490Z 	at io.trino.plugin.jdbc.BaseCaseInsensitiveMappingTest.withTable(BaseCaseInsensitiveMappingTest.java:323)
2021-07-06T10:30:16.5032705Z 	at io.trino.plugin.jdbc.BaseCaseInsensitiveMappingTest.withTable(BaseCaseInsensitiveMappingTest.java:336)
2021-07-06T10:30:16.5045177Z 	at io.trino.plugin.jdbc.BaseCaseInsensitiveMappingTest.testTableNameClashWithRuleMapping(BaseCaseInsensitiveMappingTest.java:273)
2021-07-06T10:30:16.5055740Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-07-06T10:30:16.5064700Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-07-06T10:30:16.5082918Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-07-06T10:30:16.5089927Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-07-06T10:30:16.5098010Z 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
2021-07-06T10:30:16.5104886Z 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
2021-07-06T10:30:16.5111321Z 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
2021-07-06T10:30:16.5117843Z 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
2021-07-06T10:30:16.5125634Z 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
2021-07-06T10:30:16.5132873Z 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
2021-07-06T10:30:16.5145338Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-07-06T10:30:16.5160967Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-07-06T10:30:16.5168281Z 	at java.base/java.lang.Thread.run(Thread.java:829)
2021-07-06T10:30:16.5177021Z Caused by: java.sql.SQLSyntaxErrorException: Table 'casesensitivename' already exists
2021-07-06T10:30:16.5185403Z 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
2021-07-06T10:30:16.5193967Z 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
2021-07-06T10:30:16.5204452Z 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
2021-07-06T10:30:16.5213482Z 	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)
2021-07-06T10:30:16.5220980Z 	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
2021-07-06T10:30:16.5229746Z 	at io.trino.plugin.mysql.TestingMySqlServer.execute(TestingMySqlServer.java:76)
2021-07-06T10:30:16.5233730Z 	... 17 more
2021-07-06T10:30:16.5236101Z 
2021-07-06T10:30:16.9553574Z [INFO] 
2021-07-06T10:30:16.9556922Z [INFO] Results:
2021-07-06T10:30:16.9558256Z [INFO] 
2021-07-06T10:30:16.9560169Z [ERROR] Failures: 
2021-07-06T10:30:16.9565297Z [ERROR]   TestMySqlCaseInsensitiveMapping>BaseCaseInsensitiveMappingTest.testSchemaNameClashWithRuleMapping:225 
2021-07-06T10:30:16.9568860Z Expected size:<2> but was:<1> in:
2021-07-06T10:30:16.9570877Z <["casesensitivename"]>
2021-07-06T10:30:16.9575550Z [ERROR]   TestMySqlCaseInsensitiveMapping>BaseCaseInsensitiveMappingTest.testTableNameClashWithRuleMapping:273->BaseCaseInsensitiveMappingTest.withTable:336->BaseCaseInsensitiveMappingTest.withTable:323 » Runtime
```

https://github.com/trinodb/trino/runs/2997739739?check_suite_focus=true

cc: @kokosing

**Comment by kokosing** [comment] 2021-07-06 11:53
Duplicate of #8477

**Closed by kokosing** 2021-07-06 11:53 UTC
Labels: test
