### ISSUE TITLE
Cannot Query Managed Iceberg tables registered via Polaris External Catalog in trino

### ISSUE THREAD

**Issue by soumilshah1995** [trinodb/trino#23957] opened 2024-10-29 13:47 UTC
I am able to query unmanned iceberg tables registered via Polaris in trino but I cannot query managed iceberg tables created by snowflake registered in Polaris catalog in trino 

here is my prop
```
connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=https://XXXXsnowflakecomputing.com/polaris/api/catalog
iceberg.rest-catalog.security=OAUTH2
iceberg.rest-catalog.oauth2.credential=XXX:YYY
iceberg.rest-catalog.oauth2.scope=PRINCIPAL_ROLE:SparkPrinRole
iceberg.rest-catalog.warehouse=datalake_external_catalog
iceberg.rest-catalog.vended-credentials-enabled=true
fs.native-s3.enabled=true
s3.endpoint=https://s3.us-east-1.amazonaws.com
s3.region=us-east-1
s3.path-style-access=true

```
![Image](https://github.com/user-attachments/assets/90576f9f-66f2-48c0-b2e5-98df22e22c65)

# trino 
![Image](https://github.com/user-attachments/assets/7c7cf684-1475-4afc-8fb4-751d3551a864)

I tried various approach t show tables or query none of them appears to be working

**Comment by ebyhr** [comment] 2024-10-30 00:50
cc: @mayankvadariya

**Comment by mayankvadariya** [comment] 2024-10-30 01:21
It seems you are hitting https://github.com/trinodb/trino/issues/23715. While it gets fixed, you may want to try creating tables in Snowflake with lowercase database, schema and table name by quoting them. Once all the objects(namespace/table) in the image you shared are lowercase then, those should be queryable through Trino.

**Comment by ebyhr** [comment] 2024-10-30 01:24
Closing as duplicate of #23715. Please feel free to reopen if #23715 doesn't help.

**Closed by ebyhr** 2024-10-30 01:24 UTC
