### ISSUE TITLE
Column type mismatch between partition schema and table schema- table schema is string & partition schema is varchar(50)

### ISSUE THREAD

**Issue by tooptoop4** [trinodb/trino#3646] opened 2020-05-06 11:50 UTC
0. place csv under s3://REDACT/presto_queries/cluster_launch_date=20200506/

1. login to hiveserver2 (v2.3.4) and run
CREATE EXTERNAL TABLE IF NOT EXISTS meta.presto_queries (
userName Varchar(50),
sessionId Varchar(40),
startTime Varchar(30),
secondsTaken Varchar(10),
queryString STRING
)
PARTITIONED BY (cluster_launch_date VARCHAR(8) )
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES (
   "separatorChar" = ","
)
STORED AS TEXTFILE
LOCATION 's3a://REDACT/presto_queries/';

MSCK REPAIR TABLE meta.presto_queries;

2. login to presto 333 and run
SELECT username,
       sessionid,
       starttime,
       secondstaken,
       querystring,
       cluster_launch_date
FROM hive.meta.presto_queries limit 100

error:

io.prestosql.spi.PrestoException: There is a mismatch between the table and partition schemas. The types are incompatible and cannot be coerced. The column 'username' in table 'meta.presto_queries' is declared as type 'string', but partition 'cluster_launch_date=20200506' declared column 'username' as type 'varchar(50)'.
	at io.prestosql.plugin.hive.HiveSplitManager.tablePartitionColumnMismatchException(HiveSplitManager.java:418)
	at io.prestosql.plugin.hive.HiveSplitManager.getTableToPartitionMapping(HiveSplitManager.java:377)
	at io.prestosql.plugin.hive.HiveSplitManager.lambda$getPartitionMetadata$2(HiveSplitManager.java:332)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:783)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1333)
	at io.prestosql.plugin.hive.ConcurrentLazyQueue.poll(ConcurrentLazyQueue.java:37)
	at io.prestosql.plugin.hive.BackgroundHiveSplitLoader.loadSplits(BackgroundHiveSplitLoader.java:283)
	at io.prestosql.plugin.hive.BackgroundHiveSplitLoader.access$300(BackgroundHiveSplitLoader.java:107)
	at io.prestosql.plugin.hive.BackgroundHiveSplitLoader$HiveSplitLoaderTask.process(BackgroundHiveSplitLoader.java:216)
	at io.prestosql.plugin.hive.util.ResumableTasks$1.run(ResumableTasks.java:38)
	at io.prestosql.$gen.Presto_333__0_220____20200506_113534_2.run(Unknown Source)
	at io.airlift.concurrent.BoundedExecutor.drainQueue(BoundedExecutor.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

alternatively another issue is if i set below in hive-site.xml (and restart HMS/HS2) and create another similar table

```
<property>
    <!-- https://community.hortonworks.com/content/supportkb/247055/errorjavalangunsupportedoperationexception-storage.html -->
    <name>metastore.storage.schema.reader.impl</name>
    <value>org.apache.hadoop.hive.metastore.SerDeStorageSchemaReader</value>
</property>
```
then presto select returns 0 rows! But HS2 still returns correct data

**Comment by tooptoop4** [comment] 2020-05-09 13:28
not sure if below will work:

change 2 lines:
https://github.com/prestosql/presto/blob/333/presto-hive/src/main/java/io/prestosql/plugin/hive/HiveSplitManager.java#L375
https://github.com/prestosql/presto/blob/333/presto-hive/src/main/java/io/prestosql/plugin/hive/HiveSplitManager.java#L405

before
if (!tableType.equals(partitionType)) {

after
if (!tableType.equals(partitionType) && !(tableType.equals(HiveType.HIVE_STRING) && partitionType.getHiveTypeName().toString().toLowerCase(Locale.ENGLISH).startsWith("varchar"))) {

**Comment by homar** [comment] 2022-09-21 15:29
I've tested coercion from string to bounded and unbounded varchar and also from bounded varchar to bounded and unbounded varchar.
Everything works fine so I am closing it as cannot reproduce.

**Closed by homar** 2022-09-21 15:29 UTC
Labels: bug
