### ISSUE TITLE
Document requirement about metadata tables in Iceberg JDBC catalog

### ISSUE THREAD

**Issue by miklosbarabas** [trinodb/trino#17744] opened 2023-06-03 10:16 UTC
# Context
Since **Trino release 414**, while using **Iceberg** with **JDBC catalog**, the tables for the catalog are not automatically created anymore. 

[This PR](https://github.com/trinodb/trino/pull/16557/files#diff-679b7ac4be81848b9b33211a518a7fa14d2666f71a2810a41b94f2aec6a4f292R94) introduced a change in behavior since previous versions (<= 413), where before these tables were automatically created. [^1]

# Motivation
Certain use-cases and scenarios could leverage the automated creation of Iceberg JDBC catalog tables (e.g. local development, fresh deployments, etc.). At this point in time the user is forced to create these tables manually.

# Solution
Expose the Iceberg property `initialize-catalog-tables` as a Trino catalog property: `iceberg.jdbc-catalog.initialize-catalog-tables`. This way users could control this behavior.

Note: I assume this is a _catalog property_, so it would not fit under the `extra_properties` _table property_.

[^1]: Note to the maintainers:
The above mentioned PR didn't include any release notes while it was upgrading the underlying catalog dependency (iceberg), which potentially can introduce difference in behavior. I believe such changes should always be mentioned in release notes, for better understanding of the differences in between versions, and to support easier back-tracing of regressions. 
While these type of changes are not necessarily or directly visible to the end users, they occasionally or indirectly can be.

**Comment by ebyhr** [comment] 2023-06-04 23:39
> these tables were automatically created.

This is unexpected behavior. I don't agree with the PR which supports initializing the tables.

**Comment by miklosbarabas** [comment] 2023-06-05 06:11
@ebyhr Thanks for getting back on this. As mentioned in the description, there are 2 quite common scenarios that come to my mind:
- local development setup
- fresh deployment (1st time deployments like deployments to  new environments)

It's not about initializing more than once, it's about being able to initialize _at all_, which you cannot just manually by hand since Trino version 414.

**Comment by ebyhr** [comment] 2023-06-05 06:26
I still disagree with the feature because CREATE TABLE syntax tends to be different among databases. I don't think we want to take such responsibility in the connector.

> local development setups

I would say please initialize the table on your side. 

> fresh deployments (1st time deployments like deployments to new environments)

When do you need to deploy new environments?

**Comment by miklosbarabas** [comment] 2023-06-05 06:30
> When do you need to deploy new environments?
Not sure I understand this question. Whenever there's a new environment created?

**Comment by miklosbarabas** [comment] 2023-06-05 06:33
> still disagree with the feature because CREATE TABLE syntax tends to be different among databases. 

It's solely for the Iceberg connector as you can see it in the PR. Where would you expect difference in those CREATE TABLE syntax, especially if that is defined in the Iceberg lib, and not in Trino?

**Comment by ebyhr** [comment] 2023-06-05 06:38
> Where would you expect difference in those CREATE TABLE syntax, especially if that is defined in the Iceberg lib, and not in Trino?

[JdbcUtil.java](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java)  obviously doesn't work in many databases. If we expose the config and users try to enable it in the unsupported databases, **_we_** (not Iceberg community) will receive the blame.

**Comment by miklosbarabas** [comment] 2023-06-05 06:42
Unsupported databases? This prop is only used by one functionality, this. I'm still struggling to understand how would 
> ... users try to enable it in the unsupported databases
? 
Could you please shed some light how that'd be possible?

**Comment by miklosbarabas** [comment] 2023-06-05 07:09
Would it be also beneficial to ask other Trino maintainers as well about the matter to have a more diverse view of it? 

@electrum @findepi @dain as you had relations with the previous [PR which introduced the change in behavior](https://github.com/trinodb/trino/pull/16557/files#diff-679b7ac4be81848b9b33211a518a7fa14d2666f71a2810a41b94f2aec6a4f292R94), would you mind please sharing your take on this?

**Comment by ebyhr** [comment] 2023-06-05 07:20
The PR exactly disabled the feature, but the actual situation is such table creation wasn't the expected behavior. That's why we have the following code: https://github.com/trinodb/trino/blob/26ef0fd30540711da2c9f8963ae102836cb1db8f/plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestingIcebergJdbcServer.java#L47-L48

**Comment by miklosbarabasForm3** [comment] 2023-06-05 07:35
> The actual situation is such table creation wasn't the expected behavior regardless of the PR. That's why we have the following code:
> 
> https://github.com/trinodb/trino/blob/26ef0fd30540711da2c9f8963ae102836cb1db8f/plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestingIcebergJdbcServer.java#L47-L48

But here in your referenced test you are also relying on the same statement as is being used by this `initialize-catalog-tables` functionality in Iceberg:

https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/src/test/java/org/apache/iceberg/jdbc/TestingTrinoIcebergJdbcUtil.java#L19

https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java#L64

**Comment by ebyhr** [comment] 2023-06-05 07:39
It's just a test and we know it works in our test environment. It's totally different from exposing it to users.

**Comment by miklosbarabasForm3** [comment] 2023-06-05 08:54
> If we expose the config and users try to enable it in the unsupported databases, **_we_** (not Iceberg community) will receive the blame.

While I don't see the reasoning behind your concern of users misusing the proposed functionality (especially with other catalogs / databases which are not scope of this change), I do appreciate your concern on Trino getting the blame instead of underlying dependencies.

From that blame angle, actually the current state (since Trino 414) would potentially cause what you are worried about in that aspect. Let's take the following example:
- A new user wants to use Trino, especially with Iceberg using the JDBC catalog
- The user downloads Trino and configures the Iceberg JDBC catalog appropriately against its RDBMS based on the Trino documentation
- User tries to use Trino with Iceberg JDBC catalog, but Trino fails with the following error, as the catalog tables are _not_ created: 
    ``` ```
- User tries to find something about this in Trino documentation / release notes, but as nothing related is found there, therefor "blames" Trino.

To avoid such situations, I'd imagine having the current state appropriately documented would be due as the minimum. In addition to the documentation bit, the proposed functionality this issue is about would help new users evaluate Trino (with Iceberg) in a easier and quicker fashion. (sparing the pain of the user finding the Iceberg catalog table DDLs and automate the creation of those tables)

**Comment by hashhar** [comment] 2023-06-05 09:15
JDBC catalog has other issues as well, most notably no way to manage schema upgrades on Iceberg version upgrade. In current shape of the JDBC catalog support in Iceberg I don't agree that making it easier to get started with Iceberg JDBC catalog should be a goal.

The fact that the auto-create functionality existed and was removed doesn't meant that the original situation with auto-create was the desired one.

Instead of saying "auto-create JDBC catalog tables" can you state what you would like to accomplish in more functional terms? Would having a procedure to initialize the Iceberg JDBC catalog solve your use-case? It's something the user will need to explicitly invoke and hence be better positioned to handle any issues arising from using Iceberg's `JdbcUtil`.

Or just adding documentation and updating release notes solve your use-case?

**Comment by miklosbarabas** [comment] 2023-06-05 17:53
We definitely can live without this functionality, as we can create those tables separately. 

The idea behind the PR was to potentially streamline the usage of Trino + Iceberg /w JDBC catalog. If that's not the intention from the maintainers point of view, I'm happy to close the PR.

Regarding documentation, this being an existing functionality as part of the last couple of releases, updating documentation to reflect the current behavior would surely help existing and potential new users. This applies to Release notes as well.

**Comment by hashhar** [comment] 2023-06-07 12:17
@jhlodin / @mosabua can you help with documenting the requirement to create the tables when using Iceberg JDBC catalog and also the release note for the same?

**Comment by luanmm** [comment] 2023-09-23 16:48
Hello, dear maintainers. I agree with the statement that Trino team could not be responsible for anything regarding things that breaks Trino in any point of view. But this issue here is much more than that: the Iceberg connector is LIMITING Iceberg features by not exposing this configuration for this connector only.

The proposed configuration is related to a feature that Iceberg's JDBC has. It is not something that would be transferring responsability to Trino. You may see here that this is an Iceberg feature: https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java.

I'm an example of new user that just could not find a way to setup Trino + Iceberg + Postgres (as JDBC metadata store). I just could figure out yet how to do it, just because Trino don't let me to configure this Iceberg property. Really cannot understand the point on why the proposed PR was refused. And, respectfully, it seems that is just a misunderstanding from Trino team about this feature from Iceberg.

Why I, as user, should know in advance what kind of tables Iceberg would use to store it's metadata? It is not an user concern. Iceberg could even (in a new version, for instance) change something in this tables, that would be put in Iceberg JDBC driver the code to update it or recreate it and then, because of the Trino limitation on this flag, everything could broke. Metadata tables are responsability of Iceberg and that is the main point on why the PR should be accepted. Till then, I, as user, blame Trino to block me on this. So I really do not think that the solution for this is putting on the docs how I create by myself this tables in Postgres. Does not make any sense.

Btw, congratulations for the work in Trino. Even not being tested it a lot yet, seems to be a great project.

**Closed** 2024-01-23 07:18 UTC
Labels: docs, iceberg

**Comment by tschaub** [comment] 2024-04-04 15:13
@mattheusv, @luanmm, or @miklosbarabas - can anyone share details on how the necessary tables can be created when using Trino with Iceberg and a Postgres (or similar) metastore?

**Comment by luanmm** [comment] 2024-04-04 15:46
Hello, @tschaub. I couldn't make use of Trino directly to do it.

The main problem is that Trino does not passes to Iceberg the "initialize tables" option - which will do it "automagically" for you if the tables aren't present yet.

I would recommend you to initialize the tables yourself somehow before connecting to your metastore with Trino. I just can't give you more advice on it because I've given up this stack after knowing its limitations.

Good luck! Best regards!

**Comment by patle22cute** [comment] 2024-11-09 05:36
Hi everyone, thanks for all your useful information.
I have a small addition, Configuration property 'iceberg.jdbc-catalog.initialize-catalog-tables' was not used in Trino 464.
So I have a small tweak for you guys, hope it works well for you:
I simply initialize the iceberg_tables and iceberg_namespace_properties tables in the metastore Database
here: https://github.com/trinodb/trino/blob/444/testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-iceberg-jdbc-catalog/create-table.sql
Here, I use Apache Iceberg with the metastore as Postgre, I create the .sql statement in the metastore and that's it.
Hope it's correct :))).
