### ISSUE TITLE
Implement correct type mapping for SQL Server connector

### ISSUE THREAD

**Issue by kokosing** [trinodb/trino#565] opened 2019-03-29 09:28 UTC
See: https://github.com/prestosql/presto/blob/c57cb193aa89931f826a924fd4142f56112b6943/presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java#L96

Testing should follow `TestPostgreSqlTypeMapping` example.

**Comment by nineinchnick** [comment] 2021-03-05 15:18
#4593 would be a duplicate of this but it's the one referenced in code at the moment: https://github.com/trinodb/trino/blob/d7c825ce3fb5b8a16ec6eb417503c728e43282cb/plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java#L280

Looks like this issue could be closed.

**Closed** 2021-03-05 22:04 UTC
