### ISSUE TITLE
You do not understand I have a license for aerospike! I need that you had a plugin to connect to it.https://github.com/trinodb/trino/tree/master/plugin there should be

### ISSUE THREAD

**Issue by vovakaplenko** [trinodb/trino#16408] opened 2023-03-07 13:25 UTC
You do not understand I have a license for aerospike! I need that you had a plugin to connect to it.https://github.com/trinodb/trino/tree/master/plugin there should be

**Comment by ebyhr** [comment] 2023-03-07 22:41
Closing as duplicate of #16410

**Closed by ebyhr** 2023-03-07 22:41 UTC
