### ISSUE TITLE
Nessie/Iceberg commit log author is always set to "trino" instead of the author username

### ISSUE THREAD

**Issue by johanhenriksson** [trinodb/trino#18732] opened 2023-08-18 14:11 UTC
The author in Nessie's commit log is always set to `trino` no matter who is performing the action. It would be great if it instead would show the username of the user (or impersonated user) who executed the query.

**Comment by hashhar** [comment] 2024-05-13 08:24
Closing as unable to reproduce on current master.

**Closed by hashhar** 2024-05-13 08:24 UTC
