### ISSUE TITLE
Could we have an optimizer to deduplicate joins?

### ISSUE THREAD

**Issue by AlvinWo** [trinodb/trino#13409] opened 2022-07-29 08:02 UTC
Like we've discussed in https://github.com/trinodb/trino/issues/13160

when we have a query like this:
```
SELECT a.id_user, a.name, SUM(b.value)
FROM (
  SELECT b.id_user_anon AS id_user, a.name
  FROM user a
  JOIN mapping b
  ON a.id_user = b.id_user
) a
JOIN (
  SELECT b.id_user_anon AS id_user, a.value
  FROM order a
  JOIN mapping b
  ON a.id_user = b.id_user
) b
ON a.id_user = b.id_user
GROUP BY 1,2
;
```

Could we deduplicate `join mapping` twice and only join it once, like
```
SELECT b.id_user_anon AS id_user, a.name, SUM(b.value)
FROM (
  SELECT a.id_user, a.name, b.value
  FROM user a
  JOIN order b
  ON a.id_user = b.id_user
) a
JOIN mapping b
ON a.id_user = b.id_user
GROUP BY 1, 2

```

cc @findepi

**Comment by findepi** [comment] 2022-07-29 09:20
cc @sopel39 @skrzypo987 @raunaqmorarka

**Comment by sopel39** [comment] 2022-07-29 13:30
I think this is duplicate of https://github.com/trinodb/trino/issues/5878

**Comment by sopel39** [comment] 2022-10-04 10:44
Closing as duplicate

**Closed by sopel39** 2022-10-04 10:44 UTC
Labels: enhancement, performance
