### ISSUE TITLE
[Iceberg connector] support `add_files` procedure like `migrate`

### ISSUE THREAD

**Issue by osscm** [trinodb/trino#20752] opened 2024-02-19 20:55 UTC
Spark [supports](https://iceberg.apache.org/docs/latest/spark-procedures/#add_files) it

ref: 
https://trinodb.slack.com/archives/CP1MUNEUX/p1708374679661709
https://trinodb.slack.com/archives/CJ6UC075E/p1648823298141539?thread_ts=1648760083.260499&cid=CJ6UC075E
https://trinodb.slack.com/archives/CGB0QHWSW/p1690365666760099?thread_ts=1687764503.709499&cid=CGB0QHWSW

It will be handy in building pipeline for heavy/bulk insert to Iceberg table, which could be a bit slower in the regular insert way.

**Comment by osscm** [comment] 2024-02-19 20:55
cc @alexjo2144 @findinpath @findepi

**Comment by ebyhr** [comment] 2024-02-19 21:42
Closing as duplicate of https://github.com/trinodb/trino/issues/11744

**Closed by ebyhr** 2024-02-19 21:42 UTC
