### ISSUE TITLE
JDK11 configures JMX Exporter ‘System property 'com.sun.management.jmxremote.rmi.port=null' does match configured RMI server port 9082’

### ISSUE THREAD

**Issue by chenshaojin** [trinodb/trino#7843] opened 2021-05-06 10:43 UTC
config: 
```
config.properties: 
    jmx.rmiregistry.port=9081
    jmx.rmiserver.port=9082
jvm.properties:
  -javaagent:/opt/app/trino/metrics/jmx_prometheus_javaagent-0.12.1-SNAPSHOT.jar=8081:/opt/app/trino/metrics/export-config.yaml
```
error:
```
======================
Full classname legend:
======================
Announcer:                         "io.airlift.discovery.client.Announcer"
DiscoveryModule:                   "io.airlift.discovery.client.DiscoveryModule"
Element:                           "com.google.inject.internal.Element"
GeneratedMethodAccessor27:         "jdk.internal.reflect.GeneratedMethodAccessor27"
JmxAgent9:                         "io.airlift.jmx.JmxAgent9"
JmxModule$JmxAnnouncementProvider: "io.airlift.jmx.JmxModule$JmxAnnouncementProvider"
MergingServiceSelectorFactory:     "io.airlift.discovery.client.MergingServiceSelectorFactory"
ServerMainModule:                  "io.trino.server.ServerMainModule"
ServiceAnnouncement:               "io.airlift.discovery.client.ServiceAnnouncement"
ServiceSelectorProvider:           "io.airlift.discovery.client.ServiceSelectorProvider"
========================
End of classname legend:
========================

	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:568)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
	at com.google.inject.Guice.createInjector(Guice.java:87)
	at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:276)
	at io.trino.server.Server.doStart(Server.java:115)
	at io.trino.server.Server.lambda$start$0(Server.java:77)
	at io.trino.$gen.Trino_355____20210506_102722_1.run(Unknown Source)
	at io.trino.server.Server.start(Server.java:77)
	at io.trino.server.TrinoServer.main(TrinoServer.java:38)
Caused by: java.lang.RuntimeException: System property 'com.sun.management.jmxremote.rmi.port=null' does match configured RMI server port 9082
	at io.airlift.jmx.JmxAgent9.<init>(JmxAgent9.java:69)
	at io.airlift.jmx.JmxAgent9$$FastClassByGuice$$28827706.GUICE$TRAMPOLINE(<generated>)
	at io.airlift.jmx.JmxAgent9$$FastClassByGuice$$28827706.apply(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:33)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
	at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:84)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:33)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
	at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:58)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:206)
	at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:159)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$Factory$1.call(InternalProviderInstanceBindingImpl.java:120)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
	at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$Factory.get(InternalProviderInstanceBindingImpl.java:115)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:33)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:98)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
	at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:171)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.access$300(InternalProviderInstanceBindingImpl.java:139)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory$1.call(InternalProviderInstanceBindingImpl.java:169)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:109)
	at io.airlift.bootstrap.LifeCycleModule.provision(LifeCycleModule.java:54)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:164)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at com.google.inject.internal.SingleMethodInjector.inject(SingleMethodInjector.java:84)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:101)
	at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:245)
	at com.google.inject.internal.Initializer.injectAll(Initializer.java:140)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	... 8 more
```

**Comment by chenshaojin** [comment] 2021-05-10 09:45
```
The problem has been solved！！
jvm config: 
-Dcom.sun.management.jmxremote.rmi.port=9082
-Dcom.sun.management.jmxremote.ssl=false
-Djdk.attach.allowAttachSelf=true
-javaagent:/your path/jmx_prometheus_javaagent-0.12.1-SNAPSHOT.jar=8081:/your path/export-config.yaml

config properties:
jmx.rmiregistry.port=9081
jmx.rmiserver.port=9082
```

**Comment by ebyhr** [comment] 2021-07-24 07:16
Going to close this issue since already resolved.

**Closed by ebyhr** 2021-07-24 07:16 UTC

**Comment by jasonchrion** [comment] 2022-05-10 00:51
> ```
> The problem has been solved！！
> jvm config: 
> -Dcom.sun.management.jmxremote.rmi.port=9082
> -Dcom.sun.management.jmxremote.ssl=false
> -Djdk.attach.allowAttachSelf=true
> -javaagent:/your path/jmx_prometheus_javaagent-0.12.1-SNAPSHOT.jar=8081:/your path/export-config.yaml
> 
> config properties:
> jmx.rmiregistry.port=9081
> jmx.rmiserver.port=9082
> ```

thx!

**Comment by jasonchrion** [comment] 2022-05-10 00:59
> ```
> The problem has been solved！！
> jvm config: 
> -Dcom.sun.management.jmxremote.rmi.port=9082
> -Dcom.sun.management.jmxremote.ssl=false
> -Djdk.attach.allowAttachSelf=true
> -javaagent:/your path/jmx_prometheus_javaagent-0.12.1-SNAPSHOT.jar=8081:/your path/export-config.yaml
> 
> config properties:
> jmx.rmiregistry.port=9081
> jmx.rmiserver.port=9082
> ```

thx!
I encountered the same problem, searched the whole internet but came away empty-handed, got answer here!

**Comment by YuanYunjing** [comment] 2022-08-26 08:19
> ```
> The problem has been solved！！
> jvm config: 
> -Dcom.sun.management.jmxremote.rmi.port=9082
> -Dcom.sun.management.jmxremote.ssl=false
> -Djdk.attach.allowAttachSelf=true
> -javaagent:/your path/jmx_prometheus_javaagent-0.12.1-SNAPSHOT.jar=8081:/your path/export-config.yaml
> 
> config properties:
> jmx.rmiregistry.port=9081
> jmx.rmiserver.port=9082
> ```

Thanks! I can start the trino successfully now,
And I use the config below, without the javaagent, it's ok too?
> -Dcom.sun.management.jmxremote.rmi.port=9082
> -Dcom.sun.management.jmxremote.ssl=false

**Comment by Subhashini2610** [comment] 2023-05-29 12:00
Is javaagent needed here?

**Comment by akenO8** [comment] 2023-06-01 09:31
> ```
> The problem has been solved！！
> jvm config: 
> -Dcom.sun.management.jmxremote.rmi.port=9082
> -Dcom.sun.management.jmxremote.ssl=false
> -Djdk.attach.allowAttachSelf=true
> -javaagent:/your path/jmx_prometheus_javaagent-0.12.1-SNAPSHOT.jar=8081:/your path/export-config.yaml
> 
> config properties:
> jmx.rmiregistry.port=9081
> jmx.rmiserver.port=9082
> ```

trino version: 417
java version: zulu-17
I also encountered the problem of `System property 'com.sun.management.jmxremote.rmi.port=null' does match configured RMI server port`, then I added the parameters you added in jvm config,but reported other errors: `Caused by: java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.util.Map (java.util.ArrayList and java.util.Map are in module java.base of loader 'bootstrap')`
Has anyone had this problem?
(BTW, None of this stuff is in the trino documentation, : ( sad)

**Comment by akenO8** [comment] 2023-06-02 03:20
> ```
> The problem has been solved！！
> jvm config: 
> -Dcom.sun.management.jmxremote.rmi.port=9082
> -Dcom.sun.management.jmxremote.ssl=false
> -Djdk.attach.allowAttachSelf=true
> -javaagent:/your path/jmx_prometheus_javaagent-0.12.1-SNAPSHOT.jar=8081:/your path/export-config.yaml
> 
> config properties:
> jmx.rmiregistry.port=9081
> jmx.rmiserver.port=9082
> ```

In fact, the jmx_prometheus_javaagent effect can be achieved by removing the two configurations in config.properties and using only the configurations in jvm_config.
So I don't quite understand the instructions given in the trino documentation for adding those two port configurations in config.properties.
I am thinking about whether the external jmx_prometheus_javaagent is the jmx index collection method recommended by trino.
Does anyone have the same problem? Thanks for the guidance.
