### ISSUE TITLE
Error fetching result when MAP type contains ARRAY keys 

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#22013] opened 2024-05-17 22:35 UTC
MAP type with ARRAY **_values_** is no problem. 
```sh
SELECT MAP(ARRAY['key'], ARRAY[ARRAY['value']]);
     _col0
---------------
 {key=[value]}
(1 row)
```

Both CLI and JDBC throw an exception when MAP type contains ARRAY **_keys_**.  The query status on server side is FINISHED. 
```sh
trino:tpch> SELECT MAP(ARRAY[ARRAY['key']], ARRAY['value']);
java.lang.RuntimeException: Error fetching next at http://localhost:8080/v1/statement/executing/20240517_223242_00042_6jmft/y1d11c55f3614fff069b833fda9b2c94d50fe0848/1 returned an invalid response: JsonResponse{statusCode=200, headers={content-type=[application/json], date=[Fri, 17 May 2024 22:32:43 GMT], vary=[Accept-Encoding], x-content-type-options=[nosniff]}, hasValue=false} [Error: <Response Too Large>]
	at io.trino.client.StatementClientV1.requestFailedException(StatementClientV1.java:501)
	at io.trino.client.StatementClientV1.executeRequest(StatementClientV1.java:417)
	at io.trino.client.StatementClientV1.advance(StatementClientV1.java:362)
	at io.trino.cli.StatusPrinter.printInitialStatusUpdates(StatusPrinter.java:139)
	at io.trino.cli.Query.renderQueryOutput(Query.java:165)
	at io.trino.cli.Query.renderOutput(Query.java:150)
	at io.trino.cli.Console.process(Console.java:364)
	at io.trino.cli.Console.runConsole(Console.java:294)
	at io.trino.cli.Console.run(Console.java:192)
	at io.trino.cli.Console.call(Console.java:109)
	at io.trino.cli.Console.call(Console.java:79)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at io.trino.cli.Trino.main(Trino.java:47)
Caused by: java.lang.IllegalArgumentException: Unable to create class io.trino.client.QueryResults from JSON response
	at io.trino.client.JsonResponse.execute(JsonResponse.java:139)
	at io.trino.client.StatementClientV1.executeRequest(StatementClientV1.java:401)
	... 18 more
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `io.trino.client.QueryResults`, problem: class java.lang.String cannot be cast to class java.util.List (java.lang.String and java.util.List are in module java.base of loader 'bootstrap')
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1476]
	at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:2014)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:598)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:621)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:293)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:301)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:526)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1493)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:348)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2099)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1249)
	at io.trino.client.JsonCodec.fromJson(JsonCodec.java:104)
	at io.trino.client.JsonResponse.execute(JsonResponse.java:123)
	... 19 more
Caused by: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.List (java.lang.String and java.util.List are in module java.base of loader 'bootstrap')
	at io.trino.client.FixJsonDataUtils$ArrayClientTypeHandler.fixValue(FixJsonDataUtils.java:116)
	at io.trino.client.FixJsonDataUtils$ArrayClientTypeHandler.fixValue(FixJsonDataUtils.java:101)
	at io.trino.client.FixJsonDataUtils$MapClientTypeHandler.fixValue(FixJsonDataUtils.java:150)
	at io.trino.client.FixJsonDataUtils$MapClientTypeHandler.fixValue(FixJsonDataUtils.java:128)
	at io.trino.client.FixJsonDataUtils.fixData(FixJsonDataUtils.java:75)
	at io.trino.client.QueryResults.<init>(QueryResults.java:68)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:126)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:291)
	... 30 more
Query is gone (server restarted?)
```

**Comment by martint** [comment] 2024-05-18 07:08
Duplicate of https://github.com/trinodb/trino/issues/1146

**Closed by martint** 2024-05-18 07:08 UTC
