### ISSUE TITLE
Missing records when reading from a Hive CSV table with "skip.header.line.count" = 1

### ISSUE THREAD

**Issue by orthoxerox** [trinodb/trino#17933] opened 2023-06-16 11:42 UTC
I have a Hive external table over a CSV file from https://catalog.data.gov/dataset/crime-data-from-2020-to-present

```sql
CREATE EXTERNAL TABLE `testdb3.lacrime`(           
  `dr_no` string,                                  
  `date_rptd` string,                              
  `date_occ` string,                               
  `time_occ` string,                               
  `area` string,                                   
  `area_name` string,                              
  `rpt_dist_no` string,                            
  `part_1_2` string,                               
  `crm_cd` string,                                 
  `crm_cd_desc` string,                            
  `mocodes` string,                                
  `vict_age` string,                               
  `vict_sex` string,                               
  `vict_descent` string,                           
  `premis_cd` string,                              
  `premis_desc` string,                            
  `weapon_used_cd` string,                         
  `weapon_desc` string,                            
  `status` string,                                 
  `status_desc` string,                            
  `crm_cd_1` string,                               
  `crm_cd_2` string,                               
  `crm_cd_3` string,                               
  `crm_cd_4` string,                               
  `location` string,                               
  `cross_street` string,                           
  `lat` string,                                    
  `lon` string)                                    
ROW FORMAT DELIMITED FIELDS TERMINATED BY ','                     
STORED AS TEXTFILE
LOCATION                                           
  'hdfs://<...>/testdb3/lacrime'          
TBLPROPERTIES (                                    
  'skip.header.line.count'='1'
)
```

When I query it in Trino (417), some of the records are missing from the result set. For example,

```sql
select area_name, count(*) from testdb3.lacrime
group by area_name
order by 2
```

is different between Trino and Hive, in particular, there's a record missing with dr_no = '220510098', but this detail can be instance-specific, I guess.

If I move the data to an ORC or Parquet table, the line counts are correct.
If I set the 'skip.header.line.count' property to '0',  the line counts are correct, if I ignore the presence of the header.

**Comment by martint** [comment] 2023-06-16 20:19
Does the issue happen if you turn off the "native CSV reader" via the `csv_native_reader_enabled` session property or `csv.native-reader.enabled` config property in your hive connector configuration?

**Comment by orthoxerox** [comment] 2023-06-19 07:14
Since it's a textfile and not a CSV, I tried `text_file_native_reader_enabled` as well, and I get a SQL error `Query failed (#20230619_070437_00022_8kspg): line 1:1: Session property 'csv_native_reader_enabled' does not exist` in both cases.

When I added the config properties to the hive connector config, the error went away.

**Comment by subbareddydagumati** [comment] 2023-10-11 19:52
we are also facing this issue. Any resolution for this issue?

**Comment by tkeller-moxe** [comment] 2023-10-11 20:05
cc: @electrum @dain

**Comment by subbareddydagumati** [comment] 2023-10-12 19:44
Looks like it fixed in latest version. we no longer facing this issue in 428

**Comment by dain** [comment] 2023-10-12 23:09
This was fixed ages ago.  This issue is a duplicate of https://github.com/trinodb/trino/issues/18273

**Closed by dain** 2023-10-12 23:09 UTC
