### ISSUE TITLE
Flaky TestIcebergGlueCatalogConnectorSmokeTest.testDeleteRowsConcurrently

### ISSUE THREAD

**Issue by wendigo** [trinodb/trino#23026] opened 2024-08-13 16:44 UTC
```
Error:  Errors: 
Error:  io.trino.plugin.iceberg.catalog.glue.TestIcebergGlueCatalogConnectorSmokeTest.testDeleteRowsConcurrently
Error:    Run 1: TestIcebergGlueCatalogConnectorSmokeTest>BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently:164->BaseIcebergConnectorSmokeTest.lambda$testDeleteRowsConcurrently$2:160 » IllegalState Task 1 did not complete in time
Error:    Run 2: TestIcebergGlueCatalogConnectorSmokeTest>BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently:164->BaseIcebergConnectorSmokeTest.lambda$testDeleteRowsConcurrently$2:160 » IllegalState Task 1 did not complete in time
Error:    Run 3: TestIcebergGlueCatalogConnectorSmokeTest>BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently:164->BaseIcebergConnectorSmokeTest.lambda$testDeleteRowsConcurrently$2:160 » IllegalState Task 0 did not complete in time
Error:    Run 4: TestIcebergGlueCatalogConnectorSmokeTest>BaseIcebergConnectorSmokeTest.testDeleteRowsConcurrently:164->BaseIcebergConnectorSmokeTest.lambda$testDeleteRowsConcurrently$2:160 » IllegalState Task 0 did not complete in time
```

**Comment by wendigo** [comment] 2024-08-13 16:46
cc @ebyhr

**Comment by wendigo** [comment] 2024-08-13 16:46
https://github.com/trinodb/trino/actions/runs/10372654044/job/28717301885

**Comment by ebyhr** [comment] 2024-08-13 22:16
Closing as duplicate of #21862

**Closed by ebyhr** 2024-08-13 22:16 UTC
